/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.test.activity;

public final class R {
    public static final class anim {
        public static final int slow_enter=0x7f030000;
        public static final int slow_exit=0x7f030001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class interpolator {
        public static final int slow_enter=0x7f040000;
    }
    public static final class string {
        public static final int act_title=0x7f050000;
    }
    public static final class style {
        public static final int SlowDialog=0x7f060000;
    }
}
