/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.test.hwui;

public final class R {
    public static final class anim {
        public static final int accelerate_interpolator_2=0x7f040000;
        public static final int fade_in=0x7f040001;
        public static final int fade_out=0x7f040002;
        public static final int slide_off_left=0x7f040003;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int appwidget_background=0x7f020000;
        public static final int appwidget_bg=0x7f020001;
        public static final int appwidget_bg_focus=0x7f020002;
        public static final int appwidget_bg_press=0x7f020003;
        public static final int btn_toggle_off=0x7f020004;
        public static final int btn_toggle_on=0x7f020005;
        public static final int default_wallpaper=0x7f020006;
        public static final int expander_ic_maximized=0x7f020007;
        public static final int expander_ic_minimized=0x7f020008;
        public static final int gradient=0x7f020009;
        public static final int green_gradient=0x7f02000a;
        public static final int icon=0x7f02000b;
        public static final int large_photo=0x7f02000c;
        public static final int patch=0x7f02000d;
        public static final int patch2=0x7f02000e;
        public static final int progress_vertical_bg_holo_dark=0x7f02000f;
        public static final int progress_vertical_holo_dark=0x7f020010;
        public static final int progress_vertical_primary_holo_dark=0x7f020011;
        public static final int progress_vertical_secondary_holo_dark=0x7f020012;
        public static final int robot=0x7f020013;
        public static final int round_rect_background=0x7f020014;
        public static final int scrubber_progress_vertical_holo_dark=0x7f020015;
        public static final int scrubber_vertical_primary_holo=0x7f020016;
        public static final int scrubber_vertical_secondary_holo=0x7f020017;
        public static final int scrubber_vertical_track_holo_dark=0x7f020018;
        public static final int scrubber_vertical_track_holo_light=0x7f020019;
        public static final int spot_mask=0x7f02001a;
        public static final int sunset1=0x7f02001b;
        public static final int sunset2=0x7f02001c;
        public static final int sunset3=0x7f02001d;
        public static final int very_large_photo=0x7f02001e;
        public static final int widget_header=0x7f02001f;
        public static final int widget_title_bg=0x7f020020;
    }
    public static final class id {
        public static final int button=0x7f070034;
        public static final int button1=0x7f070015;
        public static final int button1a=0x7f070018;
        public static final int button1b=0x7f07001b;
        public static final int button2=0x7f070016;
        public static final int button2a=0x7f070019;
        public static final int button2b=0x7f07001c;
        public static final int button3=0x7f070017;
        public static final int button3a=0x7f07001a;
        public static final int button3b=0x7f07001d;
        public static final int button4=0x7f07001e;
        public static final int button5=0x7f07001f;
        public static final int button6=0x7f070020;
        public static final int button7=0x7f070021;
        public static final int button8=0x7f070022;
        public static final int clickable1=0x7f07000b;
        public static final int clickable2=0x7f07000c;
        public static final int contact_tile_name=0x7f070011;
        public static final int container=0x7f070009;
        public static final int container1=0x7f070027;
        public static final int container2=0x7f070029;
        public static final int container2a=0x7f07002a;
        public static final int container3=0x7f07002c;
        public static final int container3a=0x7f07002d;
        public static final int container3b=0x7f07002e;
        public static final int day=0x7f070003;
        public static final int edittext=0x7f070036;
        public static final int flipper=0x7f07003d;
        public static final int imageview=0x7f070039;
        public static final int invalidateButton=0x7f070033;
        public static final int invalidateStatus=0x7f070024;
        public static final int layersHwCB=0x7f070013;
        public static final int layersNoneCB=0x7f070012;
        public static final int layersSwCB=0x7f070014;
        public static final int layout=0x7f07003a;
        public static final int list=0x7f070008;
        public static final int list1=0x7f070030;
        public static final int list2=0x7f070031;
        public static final int list3=0x7f070032;
        public static final int mini_text=0x7f070010;
        public static final int month=0x7f070002;
        public static final int nestedStatus=0x7f070023;
        public static final int parent=0x7f070001;
        public static final int projection=0x7f07000a;
        public static final int selectedtext=0x7f070037;
        public static final int spantext=0x7f070035;
        public static final int stack_item=0x7f07000e;
        public static final int stack_view=0x7f07000d;
        public static final int textview=0x7f070025;
        public static final int textview1=0x7f070028;
        public static final int textview2=0x7f07002b;
        public static final int textview3=0x7f07002f;
        public static final int textview_icon=0x7f07000f;
        public static final int textviewa=0x7f070026;
        public static final int textviewbackground=0x7f070038;
        public static final int widget_asset=0x7f070005;
        public static final int widget_image=0x7f070006;
        public static final int widget_root=0x7f07003b;
        public static final int widget_text=0x7f070007;
        public static final int widget_top=0x7f07003c;
        public static final int year=0x7f070004;
        public static final int yearToggle=0x7f070000;
    }
    public static final class layout {
        public static final int _advanced_blend=0x7f030000;
        public static final int _advanced_gradient=0x7f030001;
        public static final int _layers=0x7f030002;
        public static final int _lines=0x7f030003;
        public static final int _newlayers=0x7f030004;
        public static final int _paths=0x7f030005;
        public static final int _shaders=0x7f030006;
        public static final int date_picker=0x7f030007;
        public static final int flipper_item=0x7f030008;
        public static final int form=0x7f030009;
        public static final int labels=0x7f03000a;
        public static final int list_activity=0x7f03000b;
        public static final int projection=0x7f03000c;
        public static final int projection_clipping=0x7f03000d;
        public static final int stack=0x7f03000e;
        public static final int stack_item=0x7f03000f;
        public static final int text_fade=0x7f030010;
        public static final int text_large=0x7f030011;
        public static final int text_medium=0x7f030012;
        public static final int text_small=0x7f030013;
        public static final int transforms_and_animations=0x7f030014;
        public static final int view_layer_invalidation=0x7f030015;
        public static final int view_layers=0x7f030016;
        public static final int view_layers_3=0x7f030017;
        public static final int view_layers_4=0x7f030018;
        public static final int view_layers_5=0x7f030019;
        public static final int view_properties=0x7f03001a;
        public static final int widget=0x7f03001b;
        public static final int z_ordering=0x7f03001c;
    }
    public static final class string {
        public static final int complex_string=0x7f050000;
    }
    public static final class style {
        public static final int BottomLeftReorderTextView=0x7f060004;
        public static final int BottomRightReorderTextView=0x7f060006;
        public static final int LeftReorderTextView=0x7f060001;
        public static final int ReorderTextView=0x7f060000;
        public static final int RightReorderTextView=0x7f060002;
        public static final int TopLeftReorderTextView=0x7f060003;
        public static final int TopRightReorderTextView=0x7f060005;
    }
}
