/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.cts.splitapp;

public final class R {
    public static final class array {
        public static final int my_string_array=0x7f060000;
    }
    public static final class attr {
    }
    public static final class bool {
        public static final int my_receiver_enabled=0x7f040000;
		public static int feature_receiver_enabled;
    }
    public static final class color {
        public static final int my_color=0x7f070000;
    }
    public static final class dimen {
        public static final int my_dimen=0x7f080000;
    }
    public static final class drawable {
        public static final int image=0x7f020000;
    }
    public static final class integer {
        public static final int my_integer=0x7f090000;
		public static int feature_integer;
    }
    public static final class string {
        public static final int my_string1=0x7f050000;
        public static final int my_string2=0x7f050001;
		public static int feature_string;
    }
    public static final class xml {
        public static final int my_activity_meta=0x7f030000;
    }
}
