/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.mms;

public final class R {
    public static final class array {
        public static final int default_smiley_names=0x7f060001;
        /**  String to match as no subject and filter out as a subject. For example, if the
         subject string is "no subject", we won't display that. We'll pretend
         no subject string was delivered. 
         */
        public static final int empty_subject_strings=0x7f060000;
        /**  Options for slide duration in duration selection dialog box 
         */
        public static final int select_dialog_items=0x7f060002;
    }
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipAlternatesLayout=0x7f010004;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipBackground=0x7f010001;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipBackgroundPressed=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipDelete=0x7f010003;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipFontSize=0x7f010007;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipHeight=0x7f010006;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int chipPadding=0x7f010005;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int invalidChipBackground=0x7f010000;
    }
    public static final class color {
        public static final int banner_item_activated=0x7f07000b;
        public static final int banner_item_pressed=0x7f07000d;
        public static final int banner_item_selected=0x7f07000c;
        public static final int banner_item_transparent=0x7f07000a;
        public static final int message_count_color=0x7f070001;
        public static final int read_bgcolor=0x7f070004;
        public static final int solid_white=0x7f07000f;
        public static final int text_hairline=0x7f070000;
        public static final int text_shadow_color_light=0x7f07000e;
        /**  Chat "sent time" text background 
         */
        public static final int timestamp_color=0x7f070002;
        public static final int translucent_white=0x7f070009;
        /**  the background color used for unread conversation 
         */
        public static final int unread_bgcolor=0x7f070003;
        public static final int widget_sender_text_color_read=0x7f070005;
        public static final int widget_sender_text_color_unread=0x7f070006;
        public static final int widget_subject_text_color_read=0x7f070007;
        public static final int widget_subject_text_color_unread=0x7f070008;
    }
    public static final class dimen {
        public static final int avatar_width_height=0x7f080003;
        public static final int banner_m_space=0x7f08000c;
        /**  Bammer item spacing 
         */
        public static final int banner_s_space=0x7f08000b;
        public static final int chip_height=0x7f08000e;
        public static final int chip_padding=0x7f08000d;
        public static final int chip_text_size=0x7f08000f;
        public static final int input_text_height=0x7f080004;
        public static final int input_text_height_adjusted=0x7f080005;
        public static final int line_spacing_extra=0x7f080010;
        public static final int message_item_avatar_on_right_text_indent=0x7f080000;
        public static final int message_item_text_padding_left_right=0x7f080001;
        public static final int message_item_text_padding_top=0x7f080002;
        public static final int mms_inline_attachment_size=0x7f080006;
        public static final int widget_margin_bottom=0x7f08000a;
        public static final int widget_margin_left=0x7f080008;
        public static final int widget_margin_right=0x7f080009;
        public static final int widget_margin_top=0x7f080007;
    }
    public static final class drawable {
        public static final int attachment_editor_bg=0x7f020000;
        public static final int attachment_selector=0x7f020001;
        public static final int banner_button_selectable=0x7f020002;
        public static final int chip_background=0x7f020003;
        public static final int chip_background_invalid=0x7f020004;
        public static final int chip_background_selected=0x7f020005;
        public static final int chip_delete=0x7f020006;
        /**  Activity background color 
         */
        public static final int class_zero_background=0x7f02006b;
        public static final int conversation_item_background_read=0x7f020007;
        public static final int conversation_item_background_unread=0x7f020008;
        public static final int emo_im_angel=0x7f020009;
        public static final int emo_im_cool=0x7f02000a;
        public static final int emo_im_crying=0x7f02000b;
        public static final int emo_im_embarrassed=0x7f02000c;
        public static final int emo_im_foot_in_mouth=0x7f02000d;
        public static final int emo_im_happy=0x7f02000e;
        public static final int emo_im_heart=0x7f02000f;
        public static final int emo_im_kissing=0x7f020010;
        public static final int emo_im_laughing=0x7f020011;
        public static final int emo_im_lips_are_sealed=0x7f020012;
        public static final int emo_im_mad=0x7f020013;
        public static final int emo_im_money_mouth=0x7f020014;
        public static final int emo_im_pokerface=0x7f020015;
        public static final int emo_im_sad=0x7f020016;
        public static final int emo_im_smirk=0x7f020017;
        public static final int emo_im_surprised=0x7f020018;
        public static final int emo_im_tongue_sticking_out=0x7f020019;
        public static final int emo_im_undecided=0x7f02001a;
        public static final int emo_im_winking=0x7f02001b;
        public static final int emo_im_wtf=0x7f02001c;
        public static final int emo_im_yelling=0x7f02001d;
        public static final int gradient_bg_mms_widget_holo=0x7f02001e;
        public static final int gradient_bg_widget_holo=0x7f02001f;
        public static final int hairline=0x7f020020;
        public static final int hairline_left=0x7f020021;
        public static final int hairline_right=0x7f020022;
        public static final int header_bg_mms_widget_holo=0x7f020023;
        public static final int ic_attach_audio_holo_light=0x7f020024;
        public static final int ic_attach_capture_audio_holo_light=0x7f020025;
        public static final int ic_attach_capture_picture_holo_light=0x7f020026;
        public static final int ic_attach_capture_video_holo_light=0x7f020027;
        public static final int ic_attach_picture_holo_light=0x7f020028;
        public static final int ic_attach_slideshow_holo_light=0x7f020029;
        public static final int ic_attach_video_holo_light=0x7f02002a;
        public static final int ic_attachment_universal_small=0x7f02002b;
        public static final int ic_contact_picture=0x7f02002c;
        public static final int ic_dialog_attach=0x7f02002d;
        public static final int ic_gallery_video_overlay=0x7f02002e;
        public static final int ic_launcher_smsmms=0x7f02002f;
        public static final int ic_list_alert_sms_failed=0x7f020030;
        public static final int ic_lock_message_sms=0x7f020031;
        public static final int ic_maps_back=0x7f020032;
        public static final int ic_maps_next=0x7f020033;
        public static final int ic_menu_add_slide=0x7f020034;
        public static final int ic_menu_add_sound=0x7f020035;
        public static final int ic_menu_attachment=0x7f020036;
        public static final int ic_menu_call=0x7f020037;
        public static final int ic_menu_delete_played=0x7f020038;
        public static final int ic_menu_duration=0x7f020039;
        public static final int ic_menu_edit=0x7f02003a;
        public static final int ic_menu_move_down=0x7f02003b;
        public static final int ic_menu_move_up=0x7f02003c;
        public static final int ic_menu_movie=0x7f02003d;
        public static final int ic_menu_msg_compose_holo_dark=0x7f02003e;
        public static final int ic_menu_picture=0x7f02003f;
        public static final int ic_menu_remove_picture=0x7f020040;
        public static final int ic_menu_remove_sound=0x7f020041;
        public static final int ic_menu_remove_text=0x7f020042;
        public static final int ic_menu_remove_video=0x7f020043;
        public static final int ic_menu_search_holo_dark=0x7f020044;
        public static final int ic_menu_trash_holo_dark=0x7f020045;
        public static final int ic_missing_thumbnail_picture=0x7f020046;
        public static final int ic_missing_thumbnail_video=0x7f020047;
        public static final int ic_mms_drm_protected=0x7f020048;
        public static final int ic_mms_duration=0x7f020049;
        public static final int ic_mms_layout=0x7f02004a;
        public static final int ic_mms_music=0x7f02004b;
        public static final int ic_mms_text_bottom=0x7f02004c;
        public static final int ic_mms_text_top=0x7f02004d;
        public static final int ic_send_disabled_holo_light=0x7f02004e;
        public static final int ic_send_holo_light=0x7f02004f;
        public static final int ic_sms_mms_delivered=0x7f020050;
        public static final int ic_sms_mms_details=0x7f020051;
        public static final int ic_sms_mms_not_delivered=0x7f020052;
        public static final int ic_sms_mms_pending=0x7f020053;
        public static final int list_activated_holo=0x7f020054;
        public static final int list_div_top_btm_mms_widget_holo=0x7f020055;
        public static final int list_focused_holo=0x7f020056;
        public static final int list_item_font_primary=0x7f020057;
        public static final int list_item_font_secondary=0x7f020058;
        public static final int list_pressed_holo_light=0x7f020059;
        public static final int list_read_holo=0x7f02005a;
        public static final int list_selected_holo=0x7f02005b;
        public static final int list_selected_holo_light=0x7f02005c;
        public static final int list_selector_background_selected=0x7f02005d;
        public static final int list_unread_holo=0x7f02005e;
        public static final int listitem_background=0x7f02005f;
        public static final int mms_play_btn=0x7f020060;
        public static final int movie=0x7f020061;
        public static final int msg_bubble_left=0x7f020062;
        public static final int msg_bubble_right=0x7f020063;
        public static final int send_button_selector=0x7f020064;
        public static final int stat_notify_mms=0x7f020065;
        public static final int stat_notify_sms=0x7f020066;
        public static final int stat_notify_sms_failed=0x7f020067;
        public static final int stat_sys_no_sim=0x7f020068;
        public static final int text_color_black=0x7f02006d;
        /**  text color 
         */
        public static final int text_color_red=0x7f02006c;
        public static final int widget_conversation_read_selector=0x7f020069;
        public static final int widget_conversation_unread_selector=0x7f02006a;
    }
    public static final class id {
        public static final int action_cell_broadcasts=0x7f0e007f;
        public static final int action_compose_new=0x7f0e007b;
        public static final int action_debug_dump=0x7f0e0080;
        public static final int action_delete_all=0x7f0e007e;
        public static final int action_settings=0x7f0e007d;
        public static final int album_name=0x7f0e0002;
        public static final int artist_name=0x7f0e0003;
        public static final int attachment=0x7f0e0025;
        public static final int attachment_editor=0x7f0e0010;
        public static final int attachment_editor_scroll_view=0x7f0e000f;
        public static final int attachment_icon=0x7f0e0069;
        public static final int attachment_name=0x7f0e0068;
        public static final int audio=0x7f0e0031;
        public static final int audio_attachment_view=0x7f0e0000;
        public static final int audio_attachment_view_stub=0x7f0e0013;
        public static final int audio_error_msg=0x7f0e0004;
        public static final int audio_icon=0x7f0e0055;
        public static final int audio_name=0x7f0e0001;
        public static final int avatar=0x7f0e0021;
        public static final int banner_sms_default_app_icon=0x7f0e0009;
        public static final int banner_sms_promo=0x7f0e0008;
        public static final int banner_sms_promo_title=0x7f0e000a;
        public static final int bottom_panel=0x7f0e0015;
        public static final int btn_download_msg=0x7f0e004e;
        public static final int btn_no=0x7f0e001e;
        public static final int btn_yes=0x7f0e001d;
        public static final int buttonPanel=0x7f0e001c;
        public static final int button_with_counter=0x7f0e0018;
        public static final int controler=0x7f0e0032;
        public static final int conversation_list=0x7f0e0075;
        public static final int custom_title_root=0x7f0e001f;
        public static final int date=0x7f0e0023;
        public static final int date_view=0x7f0e0046;
        public static final int delete=0x7f0e0081;
        public static final int delete_locked=0x7f0e002a;
        public static final int delivered_indicator=0x7f0e0048;
        public static final int delivery_date=0x7f0e002e;
        public static final int details_indicator=0x7f0e0049;
        public static final int done=0x7f0e003c;
        public static final int done_button=0x7f0e0039;
        public static final int duration_text=0x7f0e006a;
        public static final int edit_slideshow_button=0x7f0e0062;
        public static final int embedded_text_editor=0x7f0e0016;
        public static final int empty=0x7f0e0028;
        public static final int empty_message=0x7f0e005d;
        public static final int error=0x7f0e0024;
        public static final int from=0x7f0e0022;
        public static final int history=0x7f0e000e;
        public static final int icon=0x7f0e002b;
        public static final int image=0x7f0e0030;
        public static final int image_attachment_view=0x7f0e003e;
        public static final int image_attachment_view_stub=0x7f0e0011;
        public static final int image_content=0x7f0e003f;
        public static final int image_preview=0x7f0e0065;
        public static final int image_view=0x7f0e0051;
        public static final int label=0x7f0e003a;
        public static final int label_downloading=0x7f0e004f;
        public static final int loading_text=0x7f0e007a;
        public static final int locked_indicator=0x7f0e0047;
        public static final int message=0x7f0e0029;
        public static final int message_block=0x7f0e0044;
        public static final int messages=0x7f0e005c;
        public static final int mms_download_controls=0x7f0e004d;
        public static final int mms_downloading_view_stub=0x7f0e004b;
        public static final int mms_layout_view_parent=0x7f0e0043;
        public static final int mms_layout_view_stub=0x7f0e004a;
        public static final int mms_view=0x7f0e0050;
        public static final int msg_list_item_recv=0x7f0e0042;
        public static final int msg_list_item_send=0x7f0e004c;
        public static final int name=0x7f0e0056;
        public static final int name_and_label=0x7f0e0057;
        public static final int next_slide_button=0x7f0e0034;
        public static final int number=0x7f0e0058;
        public static final int number_picker=0x7f0e0053;
        public static final int play_audio_button=0x7f0e0005;
        public static final int play_slideshow_button=0x7f0e0052;
        public static final int playing_audio=0x7f0e0054;
        public static final int pre_slide_button=0x7f0e0033;
        public static final int preview_button=0x7f0e0035;
        public static final int recipient=0x7f0e002c;
        public static final int recipients_editor=0x7f0e0059;
        public static final int recipients_editor_stub=0x7f0e000c;
        public static final int recipients_picker=0x7f0e005a;
        public static final int recipients_subject_linear=0x7f0e000b;
        public static final int remove_audio_button=0x7f0e0007;
        public static final int remove_image_button=0x7f0e0041;
        public static final int remove_slide_button=0x7f0e0037;
        public static final int remove_slideshow_button=0x7f0e0064;
        public static final int remove_video_button=0x7f0e006f;
        public static final int replace_audio_button=0x7f0e0006;
        public static final int replace_image_button=0x7f0e0036;
        public static final int replace_video_button=0x7f0e006e;
        public static final int search=0x7f0e007c;
        public static final int selected_conv_count=0x7f0e0027;
        public static final int send_button=0x7f0e0017;
        public static final int send_button_mms=0x7f0e001a;
        public static final int send_button_sms=0x7f0e001b;
        public static final int send_slideshow_button=0x7f0e0063;
        public static final int slide_editor_view=0x7f0e002f;
        public static final int slide_number_text=0x7f0e0066;
        public static final int slide_view=0x7f0e005e;
        public static final int slideshow_attachment_view=0x7f0e005f;
        public static final int slideshow_attachment_view_stub=0x7f0e0014;
        public static final int slideshow_image=0x7f0e0060;
        public static final int slideshow_text=0x7f0e0061;
        public static final int status=0x7f0e002d;
        public static final int subject=0x7f0e000d;
        public static final int subtitle=0x7f0e005b;
        public static final int text=0x7f0e003b;
        public static final int text1=0x7f0e003d;
        public static final int text_counter=0x7f0e0019;
        public static final int text_message=0x7f0e0038;
        public static final int text_preview=0x7f0e0067;
        public static final int text_view=0x7f0e0045;
        public static final int title=0x7f0e0026;
        public static final int unread_conv_count=0x7f0e0020;
        public static final int video_attachment_view=0x7f0e006b;
        public static final int video_attachment_view_stub=0x7f0e0012;
        public static final int video_thumbnail=0x7f0e006c;
        public static final int view_image_button=0x7f0e0040;
        public static final int view_video_button=0x7f0e006d;
        public static final int widget_compose=0x7f0e0074;
        public static final int widget_conversation=0x7f0e0076;
        public static final int widget_header=0x7f0e0070;
        public static final int widget_icon=0x7f0e0071;
        public static final int widget_label=0x7f0e0072;
        public static final int widget_loading=0x7f0e0079;
        public static final int widget_read_background=0x7f0e0078;
        public static final int widget_unread_background=0x7f0e0077;
        public static final int widget_unread_count=0x7f0e0073;
    }
    public static final class integer {
        public static final int chips_max_lines=0x7f0c0000;
    }
    public static final class layout {
        public static final int audio_attachment_view=0x7f040000;
        public static final int banner_sms_promo=0x7f040001;
        public static final int chips_alternate_item=0x7f040002;
        public static final int chips_recipient_dropdown_item=0x7f040003;
        public static final int compose_message_activity=0x7f040004;
        public static final int confirm_rate_limit_activity=0x7f040005;
        public static final int conversation_list_actionbar=0x7f040006;
        public static final int conversation_list_item=0x7f040007;
        public static final int conversation_list_multi_select_actionbar=0x7f040008;
        public static final int conversation_list_screen=0x7f040009;
        public static final int copy_chip_dialog_layout=0x7f04000a;
        public static final int delete_thread_dialog_view=0x7f04000b;
        public static final int delivery_report_activity=0x7f04000c;
        public static final int delivery_report_header=0x7f04000d;
        public static final int delivery_report_list_item=0x7f04000e;
        public static final int edit_slide_activity=0x7f04000f;
        public static final int edit_slide_duration=0x7f040010;
        public static final int icon_list_item=0x7f040011;
        public static final int image_attachment_view=0x7f040012;
        public static final int message_list_item_recv=0x7f040013;
        public static final int message_list_item_send=0x7f040014;
        public static final int mms_chips_recipient_dropdown_item=0x7f040015;
        public static final int mms_downloading_view=0x7f040016;
        public static final int mms_layout_view=0x7f040017;
        public static final int more_item=0x7f040018;
        public static final int number_picker_dialog=0x7f040019;
        public static final int playing_audio_info=0x7f04001a;
        public static final int recipient_filter_item=0x7f04001b;
        public static final int recipient_list_item=0x7f04001c;
        public static final int recipients_editor=0x7f04001d;
        public static final int search_activity=0x7f04001e;
        public static final int search_item=0x7f04001f;
        public static final int sim_list=0x7f040020;
        public static final int slideshow=0x7f040021;
        public static final int slideshow_attachment_view=0x7f040022;
        public static final int slideshow_edit_item=0x7f040023;
        public static final int video_attachment_view=0x7f040024;
        public static final int widget=0x7f040025;
        public static final int widget_conversation=0x7f040026;
        public static final int widget_loading=0x7f040027;
    }
    public static final class menu {
        public static final int conversation_list_menu=0x7f0d0000;
        public static final int conversation_multi_select_menu=0x7f0d0001;
        public static final int recipient_list_menu=0x7f0d0002;
    }
    public static final class mipmap {
        public static final int ic_launcher_contacts=0x7f030000;
        public static final int ic_launcher_smsmms=0x7f030001;
    }
    public static final class plurals {
        /**  This message is displayed in a confirmation dialog when the user selects one or more
         conversations and then taps the "Delete" button. 
         */
        public static final int confirm_delete_conversation=0x7f0a0000;
        /**  In digest notifications when we show N messages, but there are N+M outstanding messages,
         this text is displayed at the bottom of the notification. [CHAR LIMIT=50] 
         */
        public static final int message_count_notification_overflow=0x7f0a0003;
        /**  In the title of the compose message activity, when there are multiple recipients, we show
         the number of recipients in the subtitle of the action bar. There's never a case of one. [CHAR LIMIT=50] 
         */
        public static final int recipient_count=0x7f0a0004;
        /**   Search results title 
         */
        public static final int search_results_title=0x7f0a0002;
        /**  Duration of the slide, shown in the list in the slideshow editor 
         */
        public static final int slide_duration=0x7f0a0001;
    }
    public static final class string {
        /**  Menu item in conversation screen for attaching something to the message being composed 
         */
        public static final int add_attachment=0x7f090036;
        /**  Menu item in slide edit screen for adding music to the slide being edited 
         */
        public static final int add_music=0x7f090030;
        /**  Menu item in slide edit screen for adding a picture to the slide being edited 
         */
        public static final int add_picture=0x7f09002e;
        /**  Menu item in slideshow edit screen for adding a new slide to the slideshow 
         */
        public static final int add_slide=0x7f090029;
        /**  Text displayed below "Add slide" item in slideshow edit screen 
         */
        public static final int add_slide_hint=0x7f09002a;
        /**  Menu item in conversation screen for adding a subject to the message being composed 
         */
        public static final int add_subject=0x7f090037;
        /**  Menu item in slide edit screen for adding a video to the slide being edited 
         */
        public static final int add_video=0x7f090032;
        /**  Alert dialog when adding attachments is taking a while 
         */
        public static final int adding_attachments=0x7f09005f;
        /**  Alert dialog title when adding attachments is taking a while  [CHAR LIMIT=none] 
         */
        public static final int adding_attachments_title=0x7f09005e;
        /**  Message of progress dialog for picker 
         */
        public static final int adding_recipients=0x7f090119;
        /**  Menu item in conversation screen for returning to the conversation list 
         */
        public static final int all_threads=0x7f09003f;
        /**  The name of the SMS/MMS app as it appears to the user in the Home screen, task switcher, etc. 
         */
        public static final int app_label=0x7f090000;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_image=0x7f0900d0;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_record_sound=0x7f0900d5;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_record_video=0x7f0900d3;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_slideshow=0x7f0900d6;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_sound=0x7f0900d4;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_take_photo=0x7f0900d1;
        /**  Attachment Type Selector Adapter. This string is an option in the "Attach" dialog, "Add music" dialog 
         */
        public static final int attach_video=0x7f0900d2;
        /**  Attachment type shown in notification. [CHAR LIMIT=35] 
         */
        public static final int attachment_audio=0x7f090121;
        /**  Attachment type shown in notification. [CHAR LIMIT=35] 
         */
        public static final int attachment_picture=0x7f090124;
        /**  Attachment type shown in notification. [CHAR LIMIT=35] 
         */
        public static final int attachment_slideshow=0x7f090122;
        /**  Attachment type shown in notification. [CHAR LIMIT=35] 
         */
        public static final int attachment_video=0x7f090123;
        public static final int banner_sms_promo_message=0x7f09012e;
        public static final int banner_sms_promo_title_application=0x7f09012d;
        /**  Banner in conversation list for making Messaging the default SMS app 
         */
        public static final int banner_sms_promo_title_initial=0x7f09012c;
        /**  Label in "Message details" dialog 
         */
        public static final int bcc_label=0x7f0900b0;
        /**  Alert dialog title when creating a slideshow [CHAR LIMIT=none] 
         */
        public static final int building_slideshow_title=0x7f090060;
        /**  Brief message that appears when user tries to add picture to a slide which already has a video. 
         */
        public static final int cannot_add_picture_and_video=0x7f090059;
        /**  Brief message that appears when the maximum number of slides has been reached 
         */
        public static final int cannot_add_slide_anymore=0x7f090058;
        /**  Error message displayed when the user attempts to forward a message with DRM-locked contents 
         */
        public static final int cannot_forward_drm_obj=0x7f090056;
        /**  When the user tries to view message details and some error occurs while
         retrieving those details, this message will be shown. 
         */
        public static final int cannot_get_details=0x7f0900a8;
        /**  Error message indicating that an audio attachment cannot be played 
         */
        public static final int cannot_play_audio=0x7f090061;
        /**  Brief message that appears when the message cannot be saved 
         */
        public static final int cannot_save_message=0x7f09005a;
        /**  Dialog box title indicating the message cannot be sent because there are no valid recipients 
         */
        public static final int cannot_send_message=0x7f090054;
        /**  Dialog message text indicating the message cannot be sent because there are no valid recipients 
         */
        public static final int cannot_send_message_reason=0x7f090055;
        /**  Title of the slide duration editor activity. 
         */
        public static final int change_duration_activity=0x7f090101;
        /**  Title of the class-0 message activity. 
         */
        public static final int class_0_message_activity=0x7f090106;
        /**  Toast text when user tries to compose while we are not the default SMS app 
         */
        public static final int compose_disabled_toast=0x7f090043;
        /**  Toast message while an image is being resized 
         */
        public static final int compressing=0x7f090044;
        /**  Dialog title for the Read Report dialog. 
         */
        public static final int confirm=0x7f0900e7;
        /**  Text for the preferences button. 
         */
        public static final int confirm_clear_search_text=0x7f09010e;
        /**  Button title in Messaging preferences. 
         */
        public static final int confirm_clear_search_title=0x7f09010d;
        /**  Delete the selected message on the SIM dialog message 
         */
        public static final int confirm_delete_SIM_message=0x7f0900a2;
        /**  Delete all the messages on the SIM dialog message 
         */
        public static final int confirm_delete_all_SIM_messages=0x7f0900a1;
        /**  Delete all threads confirmation dialog message 
         */
        public static final int confirm_delete_all_conversations=0x7f09009e;
        /**  no translation found for confirm_delete_conversation:one (7509396981963472833) 
 no translation found for confirm_delete_conversation:other (4076915774012081811) 
         */
        public static final int confirm_delete_conversation=0x7f09009d;
        /**  Delete message confirmation dialog message for a locked message 
         */
        public static final int confirm_delete_locked_message=0x7f0900a0;
        /**  Delete message confirmation dialog message 
         */
        public static final int confirm_delete_message=0x7f09009f;
        /**  Delete confirmation dialog title for locked messages 
         */
        public static final int confirm_dialog_locked_title=0x7f09009c;
        /**  Confirm Delete 
 Delete confirmation dialog title 
         */
        public static final int confirm_dialog_title=0x7f09009b;
        /**  This is the confirm rate limit alert dialog text. 
         */
        public static final int confirm_rate_limit=0x7f0900ef;
        /**  Brief message that appears when converting a message from SMS to MMS. 
         */
        public static final int converting_to_picture_message=0x7f090057;
        /**  Text displayed when the user long presses on a chip to copy the recipients email address.
         [CHAR LIMIT=200] 
         */
        public static final int copy_email=0x7f090131;
        /**  Individual message context menu item 
         */
        public static final int copy_message_text=0x7f090022;
        /**  Text displayed when the user long presses on a chip to copy the recipient's phone number.
         [CHAR LIMIT=200] 
         */
        public static final int copy_number=0x7f090132;
        /**  Menu title to copy an attachment to the shared storage [CHAR LIMIT=25] 
         */
        public static final int copy_to_sdcard=0x7f0900f6;
        /**  Toast message on failed copy to shared storage [CHAR LIMIT=30] 
         */
        public static final int copy_to_sdcard_fail=0x7f0900f8;
        /**  Toast message on successful copy to shared storage [CHAR LIMIT=30] 
         */
        public static final int copy_to_sdcard_success=0x7f0900f7;
        /**  Delete button title 
         */
        public static final int delete=0x7f0900a4;
        /**  Context menu item on an individual message for deleting only that message 
         */
        public static final int delete_message=0x7f090015;
        /**  Menu item for deleting the entire conversation currently being viewed 
         */
        public static final int delete_thread=0x7f09001b;
        /**  Delete unlocked checkbox title 
         */
        public static final int delete_unlocked=0x7f0900a3;
        /**  Label in "Report" window [CHAR LIMIT=50]
         */
        public static final int delivered_label=0x7f0900cf;
        /**  Delivery Header View 
 Title of "Report" window 
         */
        public static final int delivery_header_title=0x7f0900c5;
        /**  Title of the delivery report activity. 
         */
        public static final int delivery_report_activity=0x7f0900ff;
        /**  Delivery Report Toast dialog content 
         */
        public static final int delivery_toast_body=0x7f0900d9;
        public static final int desc_mms_send_outbox_msg=0x7f09012b;
        /**  Message of the dialog used to disable messaging notifications [CHAR LIMIT=none] 
         */
        public static final int disable_notifications_dialog_message=0x7f09011f;
        /**  Menu item in conversation screen for discarding the message currently being composed 
         */
        public static final int discard=0x7f090038;
        /**  Dialog message text explaining that a draft message will not be saved due to invalid recipients 
         */
        public static final int discard_message_reason=0x7f09004d;
        /**  Menu item in slideshow edit screen for discarding the entire slideshow 
         */
        public static final int discard_slideshow=0x7f09002b;
        /**  When an error occurs downloading a new message, display this message.
         An example: Download of message Wanna get pizza from dorkman was unsuccessful. 
         */
        public static final int dl_failure_notification=0x7f0900ed;
        /**  Button text on edit slide screen indicating the user wants to finish editing that slide 
 Text displayed in the enter key slot when the recipientedittextview has focus.
         [CHAR LIMIT=12] 
         */
        public static final int done=0x7f090025;
        /**  Text of a button appearing for MMS messages that have not yet been downloaded, causing the message
         to be downloaded (imperative verb) 
         */
        public static final int download=0x7f09001d;
        /**  Dialog box message when there's a problem retrieving messages. 
         */
        public static final int download_later=0x7f0900f3;
        /**  Message displayed in place of the "download message" button once it has been pressed,
         indicating that the download is in progress 
         */
        public static final int downloading=0x7f09001e;
        /**  In conversation list items, this is the separator between a contact's name
         and the draft stamp [CHAR LIMIT=5] 
         */
        public static final int draft_separator=0x7f09011a;
        /**  Text to display when the actual text is inaccessible due to DRM protection 
         */
        public static final int drm_protected_text=0x7f090020;
        /**  Toast when the user enters a non-numeric value for the duration of a slide 
         */
        public static final int duration_not_a_number=0x7f09006b;
        /**  String for slide duration in seconds 
         */
        public static final int duration_sec=0x7f090065;
        /**  Dialog box title for duration selector 
         */
        public static final int duration_selector_title=0x7f090066;
        /**  Toast when the user enters a zero value for the duration of a slide 
         */
        public static final int duration_zero=0x7f09006c;
        /**  Button text used for editing a slideshow (imperative verb) 
         */
        public static final int edit=0x7f090075;
        /**  Title of the slide editor activity. 
         */
        public static final int edit_slide_activity=0x7f090104;
        /**  Title of the slideshow editor activity. 
         */
        public static final int edit_slideshow_activity=0x7f090102;
        /**  An enumeration comma for separating multiple names in notifications. [CHAR LIMIT=2] 
         */
        public static final int enumeration_comma=0x7f090126;
        /**  Label in "Message details" dialog 
         */
        public static final int error_code_label=0x7f0900bb;
        /**  For debugging: Dialog box title indicating there's a situation where data has unexpectedly
         changed 
         */
        public static final int error_state=0x7f09011d;
        /**  For debugging: Dialog box text indicating there's a situation where data has unexpectedly
         changed 
         */
        public static final int error_state_text=0x7f09011e;
        /**  Message indicating that the message size limit has been reached 
         */
        public static final int exceed_message_size_limitation=0x7f090047;
        /**  Time and date a message is due to expire 
         */
        public static final int expire_on=0x7f090016;
        /**  Error message indicating that the item trying to be attached could not be added 
         */
        public static final int failed_to_add_media=0x7f090049;
        /**  Error message indicating that the picture being attached and resized could not be resized 
         */
        public static final int failed_to_resize_image=0x7f09004a;
        /**  dialog error message when only is FDN is allowed. 
         */
        public static final int fdn_check_failure=0x7f0900ea;
        /**  String prepended to forwarded messages to indicate they were forwarded 
         */
        public static final int forward_prefix=0x7f09004c;
        /**  Label in "Message details" dialog showing who sent the message. 
         */
        public static final int from_label=0x7f0900ae;
        /**  Tag appearing on conversations in the conversation list that contain a draft message 
         */
        public static final int has_draft=0x7f09000f;
        /**  Dialog box title indicating which recipients are invalid when the user tries to send a message with invalid recipients 
         */
        public static final int has_invalid_recipient=0x7f09004e;
        /**  Sender to be used if the sender address has been hidden 
         */
        public static final int hidden_sender_address=0x7f090070;
        /**  Formatting for subject displayed inline, prepended to MMS message text 
         */
        public static final int inline_subject=0x7f09001f;
        /**  Error message to display when DRM rights are insufficient to access some data 
         */
        public static final int insufficient_drm_rights=0x7f090021;
        /**  While sending a message, if it has invalid recipient, display this message. 
         */
        public static final int invalid_destination=0x7f09004f;
        /**  Dialog message text when the user tries to send a message with invalid recipients 
         */
        public static final int invalid_recipient_message=0x7f090053;
        /**  Abbreviation for "kilobyte" 
         */
        public static final int kilobyte=0x7f090017;
        /**   Strings used forh MMS push of messages in outbox 
         */
        public static final int label_mms_send_outbox_msg=0x7f09012a;
        /**  Slide layout option for layout at the bottom 
         */
        public static final int layout_bottom=0x7f090069;
        /**  Dialog box title for slide layout selector 
         */
        public static final int layout_selector_title=0x7f090067;
        /**  Slide layout option for layout at the top 
         */
        public static final int layout_top=0x7f090068;
        /**  Show this in the middle of the main activity when loading conversations [CHAR LIMIT=none] 
         */
        public static final int loading_conversations=0x7f0900a7;
        /**  Menu shown in the context menu when long pressing on a message when the message contains
         one or more phone numbers and/or email addresses and the number or email is new to
         contacts. [CHAR LIMIT=50] 
         */
        public static final int menu_add_address_to_contacts=0x7f090006;
        /**  Context menu item on a message recipient for adding them to the user's
         contacts (used if the recipient is not already in the address book) 
         */
        public static final int menu_add_to_contacts=0x7f09006f;
        /**  Menu item to call the recipient of the conversation on the phone (imperative verb) 
         */
        public static final int menu_call=0x7f090007;
        /**  Context menu item on an individual message for dialing the sender's phone number 
         */
        public static final int menu_call_back=0x7f090002;
        /**  Menu item to show received cell broadcasts. [CHAR LIMIT=30] 
         */
        public static final int menu_cell_broadcasts=0x7f09000e;
        /**  Menu item for starting a new conversation 
         */
        public static final int menu_compose_new=0x7f090004;
        /**  Menu item for debugging - do not localize 
         */
        public static final int menu_debug_dump=0x7f09000c;
        /**  Context menu item on an individual conversation for deleting that conversation 
         */
        public static final int menu_delete=0x7f09000a;
        /**  Menu item for deleting all conversations 
         */
        public static final int menu_delete_all=0x7f090009;
        /**  Menu title for deleting undelivered messages or messages on
        the SIM card. 
         */
        public static final int menu_delete_messages=0x7f0900bd;
        /**  Menu title for editing a message 
         */
        public static final int menu_edit=0x7f0900bc;
        /**  Context menu item on an individual message for forwarding it to another recipient 
         */
        public static final int menu_forward=0x7f09001c;
        /**  Menu item 
 Menu item  [CHAR LIMIT=40] 
         */
        public static final int menu_group_participants=0x7f0900fc;
        public static final int menu_insert_smiley=0x7f09012f;
        /**  Menu title for locking a message 
         */
        public static final int menu_lock=0x7f0900be;
        /**  Menu item for accessing application settings 
         */
        public static final int menu_preferences=0x7f090005;
        /**  Menu item for search 
         */
        public static final int menu_search=0x7f090008;
        /**  Context menu item on an individual message for emailing the sender 
         */
        public static final int menu_send_email=0x7f090003;
        /**  Menu title for unlocking a message 
         */
        public static final int menu_unlock=0x7f0900bf;
        /**  Context menu item on an individual conversation for viewing that conversation 
         */
        public static final int menu_view=0x7f09000b;
        /**  Context menu item on a message recipient for viewing their contact info 
 no translation found for select_dialog_items:10 (7786079681602275449) 
         */
        public static final int menu_view_contact=0x7f09006e;
        /**  Label in "Message details" dialog 
         */
        public static final int message_class_label=0x7f0900ba;
        /**  In conversation list items, this comes after the receipient's name and contains
         the number of messages in the thread [CHAR LIMIT=5] 
         */
        public static final int message_count_format=0x7f09011b;
        /**  When showing a multi-message notification, this is the title [CHAR LIMIT=none] 
         */
        public static final int message_count_notification=0x7f09011c;
        /**  Title of "Message details" dialog 
         */
        public static final int message_details_title=0x7f0900a9;
        /**  Message Failed Notification 
 Dialog box title when receiving a message failed. 
         */
        public static final int message_download_failed_title=0x7f0900f0;
        /**  Dialog box message text when failure occurs sending a message. 
         */
        public static final int message_failed_body=0x7f0900f2;
        /**  Header for context menu on an individual message 
         */
        public static final int message_options=0x7f090023;
        /**  This is the text of a toast message briefly displayed when a problem occurs
         while sending. 
         */
        public static final int message_queued=0x7f0900e9;
        /**  Brief message that appears when a message has automatically been saved as a draft 
         */
        public static final int message_saved_as_draft=0x7f09005b;
        /**  Dialog box title when sending a message failed. 
         */
        public static final int message_send_failed_title=0x7f0900f1;
        /**  Dialog text for the Read Report dialog. 
         */
        public static final int message_send_read_report=0x7f0900e8;
        /**  Label in "Message details" dialog 
         */
        public static final int message_size_label=0x7f0900b5;
        /**  In message list items, this string builds the timestamp line when the message is in a group [CHAR LIMIT=NONE] 
         */
        public static final int message_timestamp_format=0x7f090127;
        /**  Message indicating that the message is too big and there is no space to attach a video 
         */
        public static final int message_too_big_for_video=0x7f090048;
        /**  Label in "Message details" dialog 
         */
        public static final int message_type_label=0x7f0900aa;
        /**  Name of the local user when displaying sender of an outgoing message (personal pronoun) 
         */
        public static final int messagelist_sender_self=0x7f090011;
        /**  Text to appear directly below the "Send" text on the SMS/MMS send button. The "MMS" text is on a second line in a smaller font. This is similar to saying "Send (mms)". 
         */
        public static final int mms=0x7f09003d;
        /**  Text displayed when the recipientedittextview is not focused. Displays the total number of recipients since the field is shrunk to just display a portion 
         */
        public static final int more_string=0x7f090130;
        /**  Menu item in slideshow edit screen for moving the selected slide down in the order 
         */
        public static final int move_down=0x7f090027;
        /**  Menu item in slideshow edit screen for moving the selected slide up in the order 
         */
        public static final int move_up=0x7f090026;
        /**  "Type" value in "Message details" dialog 
         */
        public static final int multimedia_message=0x7f0900ac;
        /**  "Type" value in "Message details" dialog 
         */
        public static final int multimedia_notification=0x7f0900ad;
        /**  Command name to open a Compose screen; displays in conversation list.
         Also used as accessibility text for widget's new message button 
         */
        public static final int new_message=0x7f090001;
        /**  Text to be used for negative response button in dialog boxes 
         */
        public static final int no=0x7f090072;
        /**  Dialog box message when there's no APN specified on the device. 
         */
        public static final int no_apn=0x7f0900f4;
        /**  Show this in the middle of the main activity when there are no conversations [CHAR LIMIT=none] 
         */
        public static final int no_conversations=0x7f0900a6;
        /**  Download Manager 
 When an error occurs downloading a new message and a subject isn't available, substitute
         this default subject. 
         */
        public static final int no_subject=0x7f0900eb;
        /**  Subject to display in the conversation list if there is no subject 
         */
        public static final int no_subject_view=0x7f090010;
        /**  Failed to send/download Notification dialog title. 
         */
        public static final int notification_failed_multiple=0x7f0900dc;
        /**  Failed to send/download Notification dialog title. 
         */
        public static final int notification_failed_multiple_title=0x7f0900dd;
        /**  Delivery Report Notification dialog title. 
         */
        public static final int notification_multiple=0x7f0900da;
        /**  Delivery Report Notification dialog title. 
         */
        public static final int notification_multiple_title=0x7f0900db;
        /**  Separator between parts of a notification in each line of an inboxStyle notification. [CHAR LIMIT=2] 
         */
        public static final int notification_separator=0x7f090125;
        /**  Hint text in message body field when keyboard is hidden 
         */
        public static final int open_keyboard_to_compose_message=0x7f090041;
        /**  Title of progress dialog for picker 
         */
        public static final int pick_too_many_recipients=0x7f090118;
        /**  Button text used for playing an attachment or slideshow (imperative verb) 
         */
        public static final int play=0x7f090074;
        /**  The value to use when migrating from old versions for a false vibrate setting 
         */
        public static final int prefDefault_vibrate_false=0x7f090096;
        /**  The value to use when migrating from old versions for a true vibrate setting 
         */
        public static final int prefDefault_vibrate_true=0x7f090095;
        /**  Settings item for setting the number of message to save for each conversation 
         */
        public static final int pref_messages_to_save=0x7f090093;
        /** - Button description in preferences to clear the search history. 
         */
        public static final int pref_mms_clear_search_history_summary=0x7f090110;
        /** - Button title in preferences to clear the search history. It's a verb action that takes place
          immediately when clicked. 
         */
        public static final int pref_mms_clear_search_history_title=0x7f09010f;
        /**  Settings screen, section heading for MMS-specific settings 
         */
        public static final int pref_mms_settings_title=0x7f09007a;
        /**  Settings screen, section heading for notifications 
         */
        public static final int pref_notification_settings_title=0x7f090079;
        /**  Settings screen, section heading for SMS-specific settings 
         */
        public static final int pref_sms_settings_title=0x7f09007b;
        /**  Settings screen, section heading for storage-specific settings 
         */
        public static final int pref_sms_storage_title=0x7f09007c;
        /**  Settings item description for boolean auto-delete messages setting 
         */
        public static final int pref_summary_auto_delete=0x7f090085;
        /**  Settings item description for integer auto-delete sms message limit 
         */
        public static final int pref_summary_delete_limit=0x7f090086;
        /**  Settings item description for entering SIM card message screen 
         */
        public static final int pref_summary_manage_sim_messages=0x7f090081;
        /**  Settings item description for boolean MMS auto-retrieve option 
         */
        public static final int pref_summary_mms_auto_retrieval=0x7f090098;
        /**  Settings item description for boolean MMS delivery report setting 
         */
        public static final int pref_summary_mms_delivery_reports=0x7f090082;
        /**  Settings item description for boolean MMS enable group MMS setting 
         */
        public static final int pref_summary_mms_group_mms=0x7f090087;
        /**  Settings item description for boolean MMS read report setting 
         */
        public static final int pref_summary_mms_read_reports=0x7f090083;
        /**  Settings item description for boolean MMS auto-retrieve while roaming option 
         */
        public static final int pref_summary_mms_retrieval_during_roaming=0x7f09009a;
        /**  Settings item description for boolean SMS delivery report setting 
         */
        public static final int pref_summary_sms_delivery_reports=0x7f090084;
        /**  Summary for SMS Disabled 
         */
        public static final int pref_summary_sms_disabled=0x7f09007e;
        /**  Summary for SMS Enabled 
         */
        public static final int pref_summary_sms_enabled=0x7f090080;
        /**  Settings item for boolean option to enable/disable auto-deletion of messages 
         */
        public static final int pref_title_auto_delete=0x7f09008d;
        /**  Settings item for entering SIM card message screen 
         */
        public static final int pref_title_manage_sim_messages=0x7f090088;
        /**  Settings item for boolean option to auto-retrieve incoming MMS messages 
         */
        public static final int pref_title_mms_auto_retrieval=0x7f090097;
        /**  Settings item for integer option to set MMS delete limit 
         */
        public static final int pref_title_mms_delete=0x7f09008f;
        /**  Settings item for boolean option to enable/disable MMS delivery reports 
         */
        public static final int pref_title_mms_delivery_reports=0x7f090089;
        /**  Settings item for boolean option to enable/disable MMS group messages 
         */
        public static final int pref_title_mms_group_mms=0x7f09008a;
        /**  Settings item for boolean option to enable/disable MMS read reports 
         */
        public static final int pref_title_mms_read_reports=0x7f09008b;
        /**  Settings item for boolean option to auto-retrieve incoming MMS messages while roaming 
         */
        public static final int pref_title_mms_retrieval_during_roaming=0x7f090099;
        /**  Settings item for boolean option to display message notifications 
         */
        public static final int pref_title_notification_enabled=0x7f090090;
        /**  Settings item for entering ringtone selection screen 
         */
        public static final int pref_title_notification_ringtone=0x7f090092;
        /**  Settings item for boolean option to vibrate during message notification 
         */
        public static final int pref_title_notification_vibrateWhen=0x7f090091;
        /**  Settings item for integer option to set SMS delete limit 
         */
        public static final int pref_title_sms_delete=0x7f09008e;
        /**  Settings item for boolean option to enable/disable SMS delivery reports 
         */
        public static final int pref_title_sms_delivery_reports=0x7f09008c;
        /**  Title for SMS Disabled 
         */
        public static final int pref_title_sms_disabled=0x7f09007d;
        /**  Title for SMS Enabled 
         */
        public static final int pref_title_sms_enabled=0x7f09007f;
        /**  Title of Settings screen 
         */
        public static final int preferences_title=0x7f090077;
        /**  Button in the slide editor screen used to preview the slide (imperative verb) 
         */
        public static final int preview=0x7f090062;
        /**  Menu item in the slide editor screen used to preview the entire slideshow (imperative verb) 
         */
        public static final int preview_slideshow=0x7f090063;
        /**  "Priority" value in "Message details" dialog 
         */
        public static final int priority_high=0x7f0900b7;
        /**  Label in "Message details" dialog 
         */
        public static final int priority_label=0x7f0900b6;
        /**  "Priority" value in "Message details" dialog 
         */
        public static final int priority_low=0x7f0900b9;
        /**  "Priority" value in "Message details" dialog 
         */
        public static final int priority_normal=0x7f0900b8;
        /**  This is the confirm rate limit alert dialog title. 
         */
        public static final int rate_limit_surpassed=0x7f0900ee;
        /**  Label in "Message details" dialog 
         */
        public static final int received_label=0x7f0900b2;
        /**  Label in "Report" window 
         */
        public static final int recipient_label=0x7f0900cd;
        /**  Title of the recipient list activity. [CHAR LIMIT=NONE] 
         */
        public static final int recipient_list_activity=0x7f090103;
        /**  Message that appears on screen while SIM card messages are retrieved 
         */
        public static final int refreshing=0x7f09000d;
        /**  Button next to an attachment during message composition to remove the attachment (imperative verb) 
         */
        public static final int remove=0x7f09003b;
        /**  Menu item in slide edit screen for removing the music from the slide being edited 
         */
        public static final int remove_music=0x7f090031;
        /**  Menu item in slide edit screen for removing the picture from the slide being edited 
         */
        public static final int remove_picture=0x7f09002f;
        /**  Menu item in slideshow edit screen for removing the selected slide from the slideshow 
         */
        public static final int remove_slide=0x7f090028;
        /**  Menu item in slide edit screen for removing the text from the slide being edited 
         */
        public static final int remove_text=0x7f09002d;
        /**  Menu item in slide edit screen for removing the video from the slide being edited 
         */
        public static final int remove_video=0x7f090033;
        /**  Button next to an attachment during message composition to replace the attachment (imperative verb) 
         */
        public static final int replace=0x7f09003a;
        /**  Button in the slide editor screen used to replace the attached picture 
         */
        public static final int replace_image=0x7f090064;
        /**  Error message indicating that an image being attached is still too large to send even after resize 
         */
        public static final int resize_image_error_information=0x7f09004b;
        /**  Settings screen menu item for restoring all settings to default 
         */
        public static final int restore_default=0x7f090078;
        /**  Dialog text for display mode save dialog. 
         */
        public static final int save=0x7f090111;
        /**  Menu title to save a sound as a ringtone 
         */
        public static final int save_ringtone=0x7f0900f9;
        /**  Label in "Message details" dialog 
         */
        public static final int saved_label=0x7f0900b3;
        /**  Toast message on successful copying ringtone to drm provider 
         */
        public static final int saved_ringtone=0x7f0900fa;
        /**  Toast message on failed copying ringtone to drm provider 
         */
        public static final int saved_ringtone_fail=0x7f0900fb;
        /**  Search activity name 
         */
        public static final int search=0x7f090109;
        /**   Search empty results 
         */
        public static final int search_empty=0x7f09010b;
        /**  Search hint 
         */
        public static final int search_hint=0x7f090108;
        /** - String saved in history searches. 
 String.format failed for translation 
 no translation found for search_results_title:one (4657073733087431350) 
         */
        public static final int search_history=0x7f09010c;
        /**  Application name shown when searching 
         */
        public static final int search_label=0x7f090107;
        /**  Search setting description 
         */
        public static final int search_setting_description=0x7f09010a;
        /**  In duration selection dialog box, short version of "seconds" 
         */
        public static final int secs=0x7f09006d;
        /**  Title for audio file picker 
         */
        public static final int select_audio=0x7f0900f5;
        /**  Layout Selector Adapter. Slideshow layout dialog option for aligning an icon. 
         */
        public static final int select_bottom_text=0x7f0900d7;
        /**  Action bar mode title when multi-selecting conversations 
         */
        public static final int select_conversations=0x7f0900a5;
        /**  Message prompting the user to select a different item; item string as type-appropriate (e.g. "picture") 
         */
        public static final int select_different_media=0x7f090046;
        /**  This is the dialog title for the "Select link" dialog, shown when the user clicks on a
    chat in the chat history view if there are links in the chat message. The dialog displays the
    links if there are any 
         */
        public static final int select_link_title=0x7f0900fd;
        /**  Layout Selector Adapter. Slideshow layout dialog option for aligning an icon. 
         */
        public static final int select_top_text=0x7f0900d8;
        /**  Button in conversation screen for sending the SMS message currently being composed (imperative verb) 
         */
        public static final int send=0x7f09003c;
        /**  Content description for the send button when sending an mms (imperative verb) 
         */
        public static final int send_mms=0x7f09003e;
        /**  Hint text when we are not the default SMS app 
         */
        public static final int sending_disabled_not_default_app=0x7f090042;
        /**  Brief small label shown to right of message when it is being sent. 
         */
        public static final int sending_message=0x7f090117;
        /**  Label in "Message details" dialog 
         */
        public static final int sent_label=0x7f0900b1;
        /**  If a message has expired and is no longer available on MMSC, show this toast. [CHAR LIMIT=NONE] 
         */
        public static final int service_message_not_found=0x7f090051;
        /**  If a message can't be sent because of a MMSC network problem, show this toast. [CHAR LIMIT=NONE] 
         */
        public static final int service_network_problem=0x7f090052;
        /**  While sending a message, this error is expected to be generated when user does not have
         MMS enabled on his account. [CHAR LIMIT=NONE] 
         */
        public static final int service_not_activated=0x7f090050;
        /**  Text to be used for affirmative response button in setting SMS limits dialog box 
         */
        public static final int set=0x7f090073;
        /**  Settings screen, what to display for Ringtone when the user chooses "silent" [CHAR LIMIT=100]
         */
        public static final int silent_ringtone=0x7f090094;
        /**  Menu title to copy a selected message from the SIM card to the phone. 
         */
        public static final int sim_copy_to_phone_memory=0x7f0900c0;
        /**  Menu title to delete a selected messaged from the SIM card. 
         */
        public static final int sim_delete=0x7f0900c1;
        /**  Message that appears on the "SMS messges on SIM card" screen when there are no messages on the SIM card 
         */
        public static final int sim_empty=0x7f0900c4;
        /**  Sim Full Notification dialog text. 
         */
        public static final int sim_full_body=0x7f0900df;
        /**  Sim Full Notification dialog title. 
         */
        public static final int sim_full_title=0x7f0900de;
        /**  Title of screen displaying messages on SIM card 
         */
        public static final int sim_manage_messages_title=0x7f0900c2;
        /**  Context menu item but currently commented out in 1.0. 
         */
        public static final int sim_view=0x7f0900c3;
        /**  Name of the Nth slide, shown in the list in the slideshow editor. 
         */
        public static final int slide_number=0x7f0900fe;
        /**  Header of slideshow showing which slide is being displayed 
         */
        public static final int slide_show_part=0x7f09002c;
        /**  Title of the slideshow activity. 
         */
        public static final int slideshow_activity=0x7f090105;
        /**  Header for context menu on an individual slideshow 
         */
        public static final int slideshow_options=0x7f090024;
        /**  Device Full Notification dialog text. 
         */
        public static final int sms_full_body=0x7f0900e1;
        /**  Device Full Notification dialog title. 
         */
        public static final int sms_full_title=0x7f0900e0;
        /**  Sms's Being Rejected Notification dialog text. 
         */
        public static final int sms_rejected_body=0x7f0900e3;
        /**  Sms's Being Rejected Notification dialog title. 
         */
        public static final int sms_rejected_title=0x7f0900e2;
        /**  Status in "Report" window 
         */
        public static final int status_failed=0x7f0900ca;
        /**  Label in "Report" window 
         */
        public static final int status_label=0x7f0900ce;
        /**  Delivery Report Activity 
 Status in "Report" window 
         */
        public static final int status_none=0x7f0900c6;
        /**  Status in "Report" window 
         */
        public static final int status_pending=0x7f0900c7;
        /**  Status in "Report" window 
         */
        public static final int status_read=0x7f0900c8;
        /**  Status in "Report" window 
         */
        public static final int status_received=0x7f0900c9;
        /**  Status in "Report" window 
         */
        public static final int status_rejected=0x7f0900cc;
        /**  Status in "Report" window 
         */
        public static final int status_unread=0x7f0900cb;
        /**  Title of the activity that tells the user about storage limits. 
         */
        public static final int storage_limits_activity=0x7f090100;
        /**  Dialog message for dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_message=0x7f090113;
        /**  Button title for dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_setting=0x7f090114;
        /**  Button title to dismiss dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_setting_dismiss=0x7f090115;
        /**  Dialog title for dialog that informs user about new storage settings. 
         */
        public static final int storage_limits_title=0x7f090112;
        public static final int storage_warning_content=0x7f090129;
        public static final int storage_warning_title=0x7f090128;
        /**  Hint displayed in subject edit text box when adding a subject 
         */
        public static final int subject_hint=0x7f090035;
        /**  Label in "Message details" dialog 
         */
        public static final int subject_label=0x7f0900b4;
        /**  "Type" value in "Message details" dialog 
         */
        public static final int text_message=0x7f0900ab;
        /**  Label in "Message details" dialog 
         */
        public static final int to_address_label=0x7f0900af;
        /**  Hint displayed in message recipient text box when starting a new conversation 
         */
        public static final int to_hint=0x7f090034;
        /**  Brief message that appears when too many videos/pictures are imported 
         */
        public static final int too_many_attachments=0x7f09005d;
        /**  Brief message that appears when too many recipients have been added 
         */
        public static final int too_many_recipients=0x7f09005c;
        /**  Toast message when a user tries to send a Mms message when there are already too many
         outstanding unsent message. 
         */
        public static final int too_many_unsent_mms=0x7f090116;
        /**  Button used for trying to send a message that has some valid recipients and some
         invalid recipients, in spite of the warning presented to the user 
         */
        public static final int try_to_send=0x7f090076;
        /**  Multimedia type used in building other messages.
         For instance: Sorry, you cannot add this audio to your message. 
         */
        public static final int type_audio=0x7f0900e4;
        /**  Multimedia type used in building other messages.
         For instance: Sorry, you cannot add this picture to your message. 
         */
        public static final int type_picture=0x7f0900e5;
        /**  Hint text in message body field when keyboard is exposed 
         */
        public static final int type_to_compose_text_enter_to_send=0x7f090040;
        /**  Hint in slide text field before text is typed 
         */
        public static final int type_to_compose_text_or_leave_blank=0x7f09006a;
        /**  Multimedia type used in building other messages.
         For instance: Sorry, you cannot add this video to your message. 
         */
        public static final int type_video=0x7f0900e6;
        /**  Dialog box message indicating that a message could not be delivered, including the time of last attempt 
         */
        public static final int undelivered_msg_dialog_body=0x7f090019;
        /**  Dialog box title brought up when warning the user that a message could not be delivered 
         */
        public static final int undelivered_msg_dialog_title=0x7f090018;
        /**  Dialog box message indicating that a message could not be delivered 
         */
        public static final int undelivered_sms_dialog_body=0x7f09001a;
        /**  When an error occurs downloading a new message and the sender is unknown, substitute
         this default text. 
         */
        public static final int unknown_sender=0x7f0900ec;
        /**  Error message indicating the format for the specified media type (e.g. "picture") is unsupported 
         */
        public static final int unsupported_media_format=0x7f090045;
        /**  Button next to an attachment during message composition to view the attachment (imperative verb) 
         */
        public static final int view=0x7f090039;
        /**  Context menu item on an individual message for viewing a delivery report 
         */
        public static final int view_delivery_report=0x7f090014;
        /**  Context menu item on an individual message for viewing message details such as time and date 
         */
        public static final int view_message_details=0x7f090013;
        /**  Displayed at the end of the conversation list in the widget. Tapping on this will open the default conversation list. [CHAR LIMIT=35] 
         */
        public static final int view_more_conversations=0x7f090120;
        /**  Context menu item on an individual message for viewing an attached slideshow 
         */
        public static final int view_slideshow=0x7f090012;
        /**  Text to be used for affirmative response button in dialog boxes 
         */
        public static final int yes=0x7f090071;
    }
    public static final class style {
        public static final int BannerContentText=0x7f0b000b;
        public static final int BannerTitleText=0x7f0b000a;
        public static final int MmsHoloTheme=0x7f0b0004;
        public static final int NotificationPrimaryText=0x7f0b0006;
        public static final int NotificationSecondaryText=0x7f0b0007;
        public static final int NotificationSubjectText=0x7f0b0008;
        public static final int RecipientEditTextView=0x7f0b000c;
        public static final int TextAppearance=0x7f0b0000;
        public static final int TextAppearance_SearchResult=0x7f0b0001;
        public static final int TextAppearance_SearchResult_Subtitle=0x7f0b0003;
        public static final int TextAppearance_SearchResult_Title=0x7f0b0002;
        public static final int TextShadowLight=0x7f0b0009;
        public static final int WidgetTitle=0x7f0b0005;
    }
    public static final class xml {
        public static final int mms_config=0x7f050000;
        public static final int preferences=0x7f050001;
        public static final int searchable=0x7f050002;
        public static final int widget_info=0x7f050003;
    }
    public static final class styleable {
        /** Attributes that can be used with a RecipientEditTextView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipAlternatesLayout com.android.mms:chipAlternatesLayout}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipBackground com.android.mms:chipBackground}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipBackgroundPressed com.android.mms:chipBackgroundPressed}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipDelete com.android.mms:chipDelete}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipFontSize com.android.mms:chipFontSize}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipHeight com.android.mms:chipHeight}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_chipPadding com.android.mms:chipPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #RecipientEditTextView_invalidChipBackground com.android.mms:invalidChipBackground}</code></td><td></td></tr>
           </table>
           @see #RecipientEditTextView_chipAlternatesLayout
           @see #RecipientEditTextView_chipBackground
           @see #RecipientEditTextView_chipBackgroundPressed
           @see #RecipientEditTextView_chipDelete
           @see #RecipientEditTextView_chipFontSize
           @see #RecipientEditTextView_chipHeight
           @see #RecipientEditTextView_chipPadding
           @see #RecipientEditTextView_invalidChipBackground
         */
        public static final int[] RecipientEditTextView = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipAlternatesLayout}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipAlternatesLayout
        */
        public static final int RecipientEditTextView_chipAlternatesLayout = 4;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipBackground}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipBackground
        */
        public static final int RecipientEditTextView_chipBackground = 1;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipBackgroundPressed}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipBackgroundPressed
        */
        public static final int RecipientEditTextView_chipBackgroundPressed = 2;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipDelete}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipDelete
        */
        public static final int RecipientEditTextView_chipDelete = 3;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipFontSize}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipFontSize
        */
        public static final int RecipientEditTextView_chipFontSize = 7;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipHeight}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipHeight
        */
        public static final int RecipientEditTextView_chipHeight = 6;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#chipPadding}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:chipPadding
        */
        public static final int RecipientEditTextView_chipPadding = 5;
        /**
          <p>This symbol is the offset where the {@link com.android.mms.R.attr#invalidChipBackground}
          attribute's value can be found in the {@link #RecipientEditTextView} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.mms:invalidChipBackground
        */
        public static final int RecipientEditTextView_invalidChipBackground = 0;
    };
}
