// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.protobuf.nano;

@SuppressWarnings("hiding")
public interface UnittestRecursiveNano {
  
  public static final class RecursiveMessageNano extends
      com.google.protobuf.nano.MessageNano {
    
    public static final class NestedMessage extends
        com.google.protobuf.nano.MessageNano {
      
      private static volatile NestedMessage[] _emptyArray;
      public static NestedMessage[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new NestedMessage[0];
            }
          }
        }
        return _emptyArray;
      }
      
      // optional .protobuf_unittest_import.RecursiveMessageNano a = 1;
      public com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano a;
      
      public NestedMessage() {
        clear();
      }
      
      public NestedMessage clear() {
        a = null;
        cachedSize = -1;
        return this;
      }
      
      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.a != null) {
          output.writeMessage(1, this.a);
        }
        super.writeTo(output);
      }
      
      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.a != null) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeMessageSize(1, this.a);
        }
        return size;
      }
      
      @Override
      public NestedMessage mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              if (this.a == null) {
                this.a = new com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano();
              }
              input.readMessage(this.a);
              break;
            }
          }
        }
      }
      
      public static NestedMessage parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new NestedMessage(), data);
      }
      
      public static NestedMessage parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new NestedMessage().mergeFrom(input);
      }
    }
    
    private static volatile RecursiveMessageNano[] _emptyArray;
    public static RecursiveMessageNano[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new RecursiveMessageNano[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // required int32 id = 1;
    public int id;
    
    // optional .protobuf_unittest_import.RecursiveMessageNano.NestedMessage nested_message = 2;
    public com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano.NestedMessage nestedMessage;
    
    // optional .protobuf_unittest_import.RecursiveMessageNano optional_recursive_message_nano = 3;
    public com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano optionalRecursiveMessageNano;
    
    // repeated .protobuf_unittest_import.RecursiveMessageNano repeated_recursive_message_nano = 4;
    public com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano[] repeatedRecursiveMessageNano;
    
    public RecursiveMessageNano() {
      clear();
    }
    
    public RecursiveMessageNano clear() {
      id = 0;
      nestedMessage = null;
      optionalRecursiveMessageNano = null;
      repeatedRecursiveMessageNano = com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano.emptyArray();
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeInt32(1, this.id);
      if (this.nestedMessage != null) {
        output.writeMessage(2, this.nestedMessage);
      }
      if (this.optionalRecursiveMessageNano != null) {
        output.writeMessage(3, this.optionalRecursiveMessageNano);
      }
      if (this.repeatedRecursiveMessageNano != null && this.repeatedRecursiveMessageNano.length > 0) {
        for (int i = 0; i < this.repeatedRecursiveMessageNano.length; i++) {
          com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano element = this.repeatedRecursiveMessageNano[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(1, this.id);
      if (this.nestedMessage != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.nestedMessage);
      }
      if (this.optionalRecursiveMessageNano != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.optionalRecursiveMessageNano);
      }
      if (this.repeatedRecursiveMessageNano != null && this.repeatedRecursiveMessageNano.length > 0) {
        for (int i = 0; i < this.repeatedRecursiveMessageNano.length; i++) {
          com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano element = this.repeatedRecursiveMessageNano[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }
    
    @Override
    public RecursiveMessageNano mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt32();
            break;
          }
          case 18: {
            if (this.nestedMessage == null) {
              this.nestedMessage = new com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano.NestedMessage();
            }
            input.readMessage(this.nestedMessage);
            break;
          }
          case 26: {
            if (this.optionalRecursiveMessageNano == null) {
              this.optionalRecursiveMessageNano = new com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano();
            }
            input.readMessage(this.optionalRecursiveMessageNano);
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.repeatedRecursiveMessageNano == null ? 0 : this.repeatedRecursiveMessageNano.length;
            com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano[] newArray =
                new com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.repeatedRecursiveMessageNano, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.google.protobuf.nano.UnittestRecursiveNano.RecursiveMessageNano();
            input.readMessage(newArray[i]);
            this.repeatedRecursiveMessageNano = newArray;
            break;
          }
        }
      }
    }
    
    public static RecursiveMessageNano parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new RecursiveMessageNano(), data);
    }
    
    public static RecursiveMessageNano parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new RecursiveMessageNano().mergeFrom(input);
    }
  }
}
