// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.protobuf.nano;

@SuppressWarnings("hiding")
public interface UnittestSimpleNano {
  
  public static final class SimpleMessageNano extends
      com.google.protobuf.nano.android.ParcelableMessageNano {
    
    // enum NestedEnum
    public static final int FOO = 1;
    public static final int BAR = 2;
    public static final int BAZ = 3;
    
    public static final class NestedMessage extends
        com.google.protobuf.nano.android.ParcelableMessageNano {
      
      private static volatile NestedMessage[] _emptyArray;
      public static NestedMessage[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new NestedMessage[0];
            }
          }
        }
        return _emptyArray;
      }
      
      // optional int32 bb = 1;
      public int bb;
      
      public NestedMessage() {
        clear();
      }
      
      public NestedMessage clear() {
        bb = 0;
        cachedSize = -1;
        return this;
      }
      
      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (this.bb != 0) {
          output.writeInt32(1, this.bb);
        }
        super.writeTo(output);
      }
      
      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (this.bb != 0) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, this.bb);
        }
        return size;
      }
      
      @Override
      public NestedMessage mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              this.bb = input.readInt32();
              break;
            }
          }
        }
      }
      
      public static NestedMessage parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new NestedMessage(), data);
      }
      
      public static NestedMessage parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new NestedMessage().mergeFrom(input);
      }
    }
    
    private static volatile SimpleMessageNano[] _emptyArray;
    public static SimpleMessageNano[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new SimpleMessageNano[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional int32 d = 1 [default = 123];
    public int d;
    
    // optional .protobuf_unittest_import.SimpleMessageNano.NestedMessage nested_msg = 2;
    public com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.NestedMessage nestedMsg;
    
    // optional .protobuf_unittest_import.SimpleMessageNano.NestedEnum default_nested_enum = 3 [default = BAZ];
    public int defaultNestedEnum;
    
    public SimpleMessageNano() {
      clear();
    }
    
    public SimpleMessageNano clear() {
      d = 123;
      nestedMsg = null;
      defaultNestedEnum = com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.BAZ;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.d != 123) {
        output.writeInt32(1, this.d);
      }
      if (this.nestedMsg != null) {
        output.writeMessage(2, this.nestedMsg);
      }
      if (this.defaultNestedEnum != com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.BAZ) {
        output.writeInt32(3, this.defaultNestedEnum);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.d != 123) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.d);
      }
      if (this.nestedMsg != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.nestedMsg);
      }
      if (this.defaultNestedEnum != com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.BAZ) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeInt32Size(3, this.defaultNestedEnum);
      }
      return size;
    }
    
    @Override
    public SimpleMessageNano mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.d = input.readInt32();
            break;
          }
          case 18: {
            if (this.nestedMsg == null) {
              this.nestedMsg = new com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.NestedMessage();
            }
            input.readMessage(this.nestedMsg);
            break;
          }
          case 24: {
            int value = input.readInt32();
            switch (value) {
              case com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.FOO:
              case com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.BAR:
              case com.google.protobuf.nano.UnittestSimpleNano.SimpleMessageNano.BAZ:
                this.defaultNestedEnum = value;
                break;
            }
            break;
          }
        }
      }
    }
    
    public static SimpleMessageNano parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new SimpleMessageNano(), data);
    }
    
    public static SimpleMessageNano parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new SimpleMessageNano().mergeFrom(input);
    }
  }
}
