// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.google.protobuf.nano;

@SuppressWarnings("hiding")
public interface UnittestImportNano {
  
  // enum ImportEnumNano
  public static final int IMPORT_NANO_FOO = 7;
  public static final int IMPORT_NANO_BAR = 8;
  public static final int IMPORT_NANO_BAZ = 9;
  
  public static final class ImportMessageNano extends
      com.google.protobuf.nano.MessageNano {
    
    private static volatile ImportMessageNano[] _emptyArray;
    public static ImportMessageNano[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new ImportMessageNano[0];
          }
        }
      }
      return _emptyArray;
    }
    
    // optional int32 d = 1;
    public int d;
    
    public ImportMessageNano() {
      clear();
    }
    
    public ImportMessageNano clear() {
      d = 0;
      cachedSize = -1;
      return this;
    }
    
    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.d != 0) {
        output.writeInt32(1, this.d);
      }
      super.writeTo(output);
    }
    
    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.d != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.d);
      }
      return size;
    }
    
    @Override
    public ImportMessageNano mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.d = input.readInt32();
            break;
          }
        }
      }
    }
    
    public static ImportMessageNano parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new ImportMessageNano(), data);
    }
    
    public static ImportMessageNano parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new ImportMessageNano().mergeFrom(input);
    }
  }
}
