/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.webviewtests;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int web_page=0x7f030000;
    }
    public static final class layout {
        public static final int webview_layout=0x7f020000;
    }
}
