/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.effectstest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int stop=0x7f020001;
    }
    public static final class id {
        public static final int SessionFrame=0x7f060006;
        public static final int attachButton=0x7f060020;
        public static final int auxFrame=0x7f06001c;
        public static final int bassboostOnOff=0x7f060005;
        public static final int bassboost_actvity=0x7f060013;
        public static final int bbControlLayout=0x7f060003;
        public static final int bbControlText=0x7f060004;
        public static final int bbReleaseButton=0x7f060002;
        public static final int bbReleaseLayout=0x7f060000;
        public static final int bbReleaseText=0x7f060001;
        public static final int bbStrengthDesc=0x7f06000a;
        public static final int bbStrengthMax=0x7f06000c;
        public static final int bbStrengthMin=0x7f06000b;
        public static final int bbStrengthName=0x7f060009;
        public static final int bbStrengthSeekBar=0x7f06000d;
        public static final int bbStrengthValue=0x7f06000e;
        public static final int effect_list=0x7f060015;
        public static final int env_reverb_actvity=0x7f06000f;
        public static final int eqControlLayout=0x7f060045;
        public static final int eqControlText=0x7f060046;
        public static final int eqParam1Center=0x7f06004b;
        public static final int eqParam1Desc=0x7f060049;
        public static final int eqParam1Max=0x7f06004c;
        public static final int eqParam1Min=0x7f06004a;
        public static final int eqParam1Name=0x7f060048;
        public static final int eqParam1SeekBar=0x7f06004d;
        public static final int eqParam1Value=0x7f06004e;
        public static final int eqParam2Center=0x7f060052;
        public static final int eqParam2Desc=0x7f060050;
        public static final int eqParam2Max=0x7f060053;
        public static final int eqParam2Min=0x7f060051;
        public static final int eqParam2Name=0x7f06004f;
        public static final int eqParam2SeekBar=0x7f060054;
        public static final int eqParam2Value=0x7f060055;
        public static final int eqParam3Center=0x7f060059;
        public static final int eqParam3Desc=0x7f060057;
        public static final int eqParam3Max=0x7f06005a;
        public static final int eqParam3Min=0x7f060058;
        public static final int eqParam3Name=0x7f060056;
        public static final int eqParam3SeekBar=0x7f06005b;
        public static final int eqParam3Value=0x7f06005c;
        public static final int eqParam4Center=0x7f060060;
        public static final int eqParam4Desc=0x7f06005e;
        public static final int eqParam4Max=0x7f060061;
        public static final int eqParam4Min=0x7f06005f;
        public static final int eqParam4Name=0x7f06005d;
        public static final int eqParam4SeekBar=0x7f060062;
        public static final int eqParam4Value=0x7f060063;
        public static final int eqParam5Center=0x7f060067;
        public static final int eqParam5Desc=0x7f060065;
        public static final int eqParam5Max=0x7f060068;
        public static final int eqParam5Min=0x7f060066;
        public static final int eqParam5Name=0x7f060064;
        public static final int eqParam5SeekBar=0x7f060069;
        public static final int eqParam5Value=0x7f06006a;
        public static final int eqParam6Name=0x7f06006b;
        public static final int eqParam6SeekBar=0x7f06006c;
        public static final int eqParam6Value=0x7f06006d;
        public static final int eqReleaseButton=0x7f060044;
        public static final int eqReleaseLayout=0x7f060042;
        public static final int eqReleaseText=0x7f060043;
        public static final int equalizerOnOff=0x7f060047;
        public static final int equalizer_actvity=0x7f060011;
        public static final int fftCenter=0x7f060092;
        public static final int fftMax=0x7f060093;
        public static final int fftMin=0x7f060091;
        public static final int fftName=0x7f060090;
        public static final int playPause1=0x7f06001f;
        public static final int playPauseFrame=0x7f06001d;
        public static final int preset_reverb_actvity=0x7f060010;
        public static final int presetrvbControlLayout=0x7f060071;
        public static final int presetrvbControlText=0x7f060072;
        public static final int presetrvbOnOff=0x7f060073;
        public static final int presetrvbParam1Name=0x7f060074;
        public static final int presetrvbParam1SeekBar=0x7f060075;
        public static final int presetrvbParam1Value=0x7f060076;
        public static final int presetrvbReleaseButton=0x7f060070;
        public static final int presetrvbReleaseLayout=0x7f06006e;
        public static final int presetrvbReleaseText=0x7f06006f;
        public static final int rvbControlLayout=0x7f060019;
        public static final int rvbControlText=0x7f06001a;
        public static final int rvbOnOff=0x7f06001b;
        public static final int rvbParam10Name=0x7f06003f;
        public static final int rvbParam10SeekBar=0x7f060040;
        public static final int rvbParam10Value=0x7f060041;
        public static final int rvbParam1Name=0x7f060024;
        public static final int rvbParam1SeekBar=0x7f060025;
        public static final int rvbParam1Value=0x7f060026;
        public static final int rvbParam2Name=0x7f060027;
        public static final int rvbParam2SeekBar=0x7f060028;
        public static final int rvbParam2Value=0x7f060029;
        public static final int rvbParam3Name=0x7f06002a;
        public static final int rvbParam3SeekBar=0x7f06002b;
        public static final int rvbParam3Value=0x7f06002c;
        public static final int rvbParam4Name=0x7f06002d;
        public static final int rvbParam4SeekBar=0x7f06002e;
        public static final int rvbParam4Value=0x7f06002f;
        public static final int rvbParam5Name=0x7f060030;
        public static final int rvbParam5SeekBar=0x7f060031;
        public static final int rvbParam5Value=0x7f060032;
        public static final int rvbParam6Name=0x7f060033;
        public static final int rvbParam6SeekBar=0x7f060034;
        public static final int rvbParam6Value=0x7f060035;
        public static final int rvbParam7Name=0x7f060036;
        public static final int rvbParam7SeekBar=0x7f060037;
        public static final int rvbParam7Value=0x7f060038;
        public static final int rvbParam8Name=0x7f060039;
        public static final int rvbParam8SeekBar=0x7f06003a;
        public static final int rvbParam8Value=0x7f06003b;
        public static final int rvbParam9Name=0x7f06003c;
        public static final int rvbParam9SeekBar=0x7f06003d;
        public static final int rvbParam9Value=0x7f06003e;
        public static final int rvbReleaseButton=0x7f060018;
        public static final int rvbReleaseLayout=0x7f060016;
        public static final int rvbReleaseText=0x7f060017;
        public static final int sendLevelSeekBar=0x7f060022;
        public static final int sendLevelText=0x7f060021;
        public static final int sendLevelValue=0x7f060023;
        public static final int sessionEdit=0x7f060008;
        public static final int sessionText=0x7f060007;
        public static final int stop1=0x7f06001e;
        public static final int virtControlLayout=0x7f06007a;
        public static final int virtControlText=0x7f06007b;
        public static final int virtReleaseButton=0x7f060079;
        public static final int virtReleaseLayout=0x7f060077;
        public static final int virtReleaseText=0x7f060078;
        public static final int virtStrengthDesc=0x7f06007e;
        public static final int virtStrengthMax=0x7f060080;
        public static final int virtStrengthMin=0x7f06007f;
        public static final int virtStrengthName=0x7f06007d;
        public static final int virtStrengthSeekBar=0x7f060081;
        public static final int virtStrengthValue=0x7f060082;
        public static final int virtualizerOnOff=0x7f06007c;
        public static final int virtualizer_actvity=0x7f060012;
        public static final int visuCallbackLayout=0x7f060089;
        public static final int visuCallbackOnOff=0x7f06008b;
        public static final int visuCallbackText=0x7f06008a;
        public static final int visuControlLayout=0x7f060086;
        public static final int visuControlText=0x7f060087;
        public static final int visuReleaseButton=0x7f060085;
        public static final int visuReleaseLayout=0x7f060083;
        public static final int visuReleaseText=0x7f060084;
        public static final int visualizerOnOff=0x7f060088;
        public static final int visualizer_actvity=0x7f060014;
        public static final int waveformCenter=0x7f06008e;
        public static final int waveformMax=0x7f06008f;
        public static final int waveformMin=0x7f06008d;
        public static final int waveformName=0x7f06008c;
    }
    public static final class layout {
        public static final int bassboosttest=0x7f030000;
        public static final int effectstest=0x7f030001;
        public static final int envreverbtest=0x7f030002;
        public static final int equalizertest=0x7f030003;
        public static final int presetreverbtest=0x7f030004;
        public static final int virtualizertest=0x7f030005;
        public static final int visualizertest=0x7f030006;
    }
    public static final class raw {
        public static final int mp3_sample=0x7f040000;
        public static final int sine440_mo_16b_16k=0x7f040001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int bassboost_test_name=0x7f05001b;
        public static final int effect_attach_off=0x7f050020;
        public static final int effect_attach_on=0x7f050021;
        public static final int effect_bypass=0x7f050003;
        public static final int effect_control=0x7f050001;
        public static final int effect_release=0x7f050002;
        public static final int envreverb_test_name=0x7f050004;
        public static final int eq_param_1_name=0x7f050013;
        public static final int eq_param_2_name=0x7f050014;
        public static final int eq_param_3_name=0x7f050015;
        public static final int eq_param_4_name=0x7f050016;
        public static final int eq_param_5_name=0x7f050017;
        public static final int eq_param_6_name=0x7f050018;
        public static final int equalizer_test_name=0x7f050011;
        public static final int fft_name=0x7f05001f;
        public static final int presetrvb_param_1_name=0x7f050010;
        public static final int presetrvb_test_name=0x7f05000f;
        public static final int rvb_param_10_name=0x7f05000e;
        public static final int rvb_param_1_name=0x7f050005;
        public static final int rvb_param_2_name=0x7f050006;
        public static final int rvb_param_3_name=0x7f050007;
        public static final int rvb_param_4_name=0x7f050008;
        public static final int rvb_param_5_name=0x7f050009;
        public static final int rvb_param_6_name=0x7f05000a;
        public static final int rvb_param_7_name=0x7f05000b;
        public static final int rvb_param_8_name=0x7f05000c;
        public static final int rvb_param_9_name=0x7f05000d;
        public static final int send_level_name=0x7f050022;
        public static final int session=0x7f050012;
        public static final int stength_name=0x7f05001a;
        public static final int virtualizer_test_name=0x7f050019;
        public static final int visu_callback=0x7f05001d;
        public static final int visualizer_test_name=0x7f05001c;
        public static final int waveform_name=0x7f05001e;
    }
}
