/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.cts.keysets_permdef;

public final class R {
    public static final class attr {
    }
    public static final class string {
        public static final int keysets_perm_desc=0x7f020000;
        public static final int keysets_perm_label=0x7f020001;
    }
}
