/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.test.shared_library;

public final class R {
    public static final class array {
        public static int animals=0x00050000;
    }
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int city=0x00010003;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int country=0x00010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int name=0x00010000;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int state=0x00010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int streetName=0x00010002;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int streetNumber=0x00010001;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static int zip=0x00010005;
    }
    public static final class color {
        public static int orange=0x00070000;
    }
    public static final class drawable {
        public static int size_48x48=0x00030000;
    }
    public static final class id {
        public static int cityStateZip=0x00080002;
        public static int country=0x00080003;
        public static int name=0x00080000;
        public static int street=0x00080001;
    }
    public static final class layout {
        public static int address=0x00060000;
    }
    public static final class string {
        public static int racoon=0x00020004;
        public static int shared_string=0x00020003;
        public static int upgrade_body=0x00020001;
        public static int upgrade_button=0x00020002;
        public static int upgrade_title=0x00020000;
    }
    public static final class style {
        public static int ActionBar=0x00040002;
        public static int CodeFont=0x00040000;
        public static int Theme=0x00040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a AddressView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AddressView_city com.google.android.test.shared_library:city}</code></td><td></td></tr>
           <tr><td><code>{@link #AddressView_country com.google.android.test.shared_library:country}</code></td><td></td></tr>
           <tr><td><code>{@link #AddressView_name com.google.android.test.shared_library:name}</code></td><td></td></tr>
           <tr><td><code>{@link #AddressView_state com.google.android.test.shared_library:state}</code></td><td></td></tr>
           <tr><td><code>{@link #AddressView_streetName com.google.android.test.shared_library:streetName}</code></td><td></td></tr>
           <tr><td><code>{@link #AddressView_streetNumber com.google.android.test.shared_library:streetNumber}</code></td><td></td></tr>
           <tr><td><code>{@link #AddressView_zip com.google.android.test.shared_library:zip}</code></td><td></td></tr>
           </table>
           @see #AddressView_city
           @see #AddressView_country
           @see #AddressView_name
           @see #AddressView_state
           @see #AddressView_streetName
           @see #AddressView_streetNumber
           @see #AddressView_zip
         */
        public static final int[] AddressView = {
            0x02010000, 0x02010001, 0x02010002, 0x02010003,
            0x02010004, 0x02010005, 0x02010006
        };
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#city}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:city
        */
        public static int AddressView_city = 3;
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#country}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:country
        */
        public static int AddressView_country = 6;
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#name}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:name
        */
        public static int AddressView_name = 0;
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#state}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:state
        */
        public static int AddressView_state = 4;
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#streetName}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:streetName
        */
        public static int AddressView_streetName = 2;
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#streetNumber}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:streetNumber
        */
        public static int AddressView_streetNumber = 1;
        /**
          <p>This symbol is the offset where the {@link com.google.android.test.shared_library.R.attr#zip}
          attribute's value can be found in the {@link #AddressView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.google.android.test.shared_library:zip
        */
        public static int AddressView_zip = 5;
    };
    public static void onResourcesLoaded(int packageId) {
        array.animals = (array.animals & 0x00ffffff) | (packageId << 24);
        attr.city = (attr.city & 0x00ffffff) | (packageId << 24);
        attr.country = (attr.country & 0x00ffffff) | (packageId << 24);
        attr.name = (attr.name & 0x00ffffff) | (packageId << 24);
        attr.state = (attr.state & 0x00ffffff) | (packageId << 24);
        attr.streetName = (attr.streetName & 0x00ffffff) | (packageId << 24);
        attr.streetNumber = (attr.streetNumber & 0x00ffffff) | (packageId << 24);
        attr.zip = (attr.zip & 0x00ffffff) | (packageId << 24);
        color.orange = (color.orange & 0x00ffffff) | (packageId << 24);
        drawable.size_48x48 = (drawable.size_48x48 & 0x00ffffff) | (packageId << 24);
        id.cityStateZip = (id.cityStateZip & 0x00ffffff) | (packageId << 24);
        id.country = (id.country & 0x00ffffff) | (packageId << 24);
        id.name = (id.name & 0x00ffffff) | (packageId << 24);
        id.street = (id.street & 0x00ffffff) | (packageId << 24);
        layout.address = (layout.address & 0x00ffffff) | (packageId << 24);
        string.racoon = (string.racoon & 0x00ffffff) | (packageId << 24);
        string.shared_string = (string.shared_string & 0x00ffffff) | (packageId << 24);
        string.upgrade_body = (string.upgrade_body & 0x00ffffff) | (packageId << 24);
        string.upgrade_button = (string.upgrade_button & 0x00ffffff) | (packageId << 24);
        string.upgrade_title = (string.upgrade_title & 0x00ffffff) | (packageId << 24);
        style.ActionBar = (style.ActionBar & 0x00ffffff) | (packageId << 24);
        style.CodeFont = (style.CodeFont & 0x00ffffff) | (packageId << 24);
        style.Theme = (style.Theme & 0x00ffffff) | (packageId << 24);
        for(int i = 0; i < styleable.AddressView.length; ++i) {
            styleable.AddressView[i] = (styleable.AddressView[i] & 0x00ffffff) | (packageId << 24);
        }
    }
}
