/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.printspooler;

public final class R {
    public static final class array {
        /**  Arrays 
 Color mode labels. 
         */
        public static final int color_mode_labels=0x7f040003;
        /**  Everything else is ISO 
         */
        public static final int mediasize_to_standard_map=0x7f040000;
        /**  Orientation labels. 
         */
        public static final int orientation_labels=0x7f040004;
        public static final int page_options_values=0x7f040002;
        public static final int pdf_printer_media_sizes=0x7f040001;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int columnCount=0x7f010000;
    }
    public static final class color {
        public static final int item_text_color=0x7f050005;
        public static final int material_grey_500=0x7f050004;
        public static final int print_button_tint_color=0x7f050000;
        public static final int print_preview_background_color=0x7f050002;
        public static final int print_preview_scrim_color=0x7f050001;
        public static final int promoted_action_background_color=0x7f050003;
    }
    public static final class dimen {
        public static final int preview_controls_elevation=0x7f070005;
        public static final int preview_destination_spinner_width=0x7f070008;
        public static final int preview_list_padding=0x7f070004;
        public static final int preview_page_footer_height=0x7f070006;
        public static final int preview_page_margin=0x7f070003;
        public static final int preview_page_min_width=0x7f070007;
        public static final int print_dialog_frame_max_width_dip=0x7f070000;
        public static final int selected_page_elevation=0x7f070001;
        public static final int unselected_page_elevation=0x7f070002;
    }
    public static final class drawable {
        public static final int ic_check_circle=0x7f020000;
        public static final int ic_expand_less=0x7f020001;
        public static final int ic_expand_less_24dp=0x7f020002;
        public static final int ic_expand_more=0x7f020003;
        public static final int ic_expand_more_24dp=0x7f020004;
        public static final int ic_grayedout_printer=0x7f020005;
        public static final int ic_menu_savetopdf=0x7f020006;
        public static final int ic_print=0x7f020007;
        public static final int ic_remove_circle=0x7f020008;
        public static final int ic_restart=0x7f020009;
        public static final int ic_search=0x7f02000a;
        public static final int page_selector_background=0x7f02000b;
        public static final int print_button=0x7f02000c;
        public static final int print_button_background=0x7f02000d;
        public static final int stat_notify_cancelling=0x7f02000e;
    }
    public static final class fraction {
        public static final int page_selected_alpha=0x7f080000;
        public static final int page_unselected_alpha=0x7f080001;
    }
    public static final class id {
        public static final int action_add_printer=0x7f0d0024;
        public static final int action_button=0x7f0d001d;
        public static final int action_search=0x7f0d0023;
        public static final int color_spinner=0x7f0d0014;
        public static final int copies_count_summary=0x7f0d0009;
        public static final int copies_edittext=0x7f0d0012;
        public static final int destination_spinner=0x7f0d0007;
        public static final int draggable_content=0x7f0d0010;
        public static final int dynamic_content=0x7f0d000f;
        public static final int embedded_content_container=0x7f0d000c;
        public static final int embedded_content_scrim=0x7f0d000e;
        public static final int empty_print_state=0x7f0d0021;
        public static final int expand_collapse_handle=0x7f0d001a;
        public static final int expand_collapse_icon=0x7f0d001b;
        public static final int icon=0x7f0d001e;
        public static final int message=0x7f0d001c;
        public static final int more_options_button=0x7f0d0019;
        public static final int options_container=0x7f0d0011;
        public static final int options_content=0x7f0d0005;
        public static final int orientation_spinner=0x7f0d0015;
        public static final int page_content=0x7f0d0001;
        public static final int page_footer=0x7f0d0002;
        public static final int page_number=0x7f0d0003;
        public static final int page_range_edittext=0x7f0d0018;
        public static final int page_range_title=0x7f0d0017;
        public static final int page_selector=0x7f0d0004;
        public static final int paper_size_spinner=0x7f0d0013;
        public static final int paper_size_summary=0x7f0d000a;
        public static final int preview_content=0x7f0d000d;
        public static final int preview_page=0x7f0d0000;
        public static final int print_button=0x7f0d000b;
        public static final int progress_bar=0x7f0d0022;
        public static final int range_options_spinner=0x7f0d0016;
        public static final int static_content=0x7f0d0006;
        public static final int subtitle=0x7f0d0020;
        public static final int summary_content=0x7f0d0008;
        public static final int title=0x7f0d001f;
    }
    public static final class integer {
        public static final int page_option_value_all=0x7f060000;
        public static final int page_option_value_page_range=0x7f060001;
        public static final int preview_page_per_row_count=0x7f060002;
        public static final int print_option_column_count=0x7f060003;
    }
    public static final class layout {
        public static final int preview_page=0x7f030000;
        public static final int preview_page_loading=0x7f030001;
        public static final int print_activity=0x7f030002;
        public static final int print_activity_controls=0x7f030003;
        public static final int print_error_fragment=0x7f030004;
        public static final int print_progress_fragment=0x7f030005;
        public static final int printer_dropdown_item=0x7f030006;
        public static final int printer_list_item=0x7f030007;
        public static final int select_printer_activity=0x7f030008;
    }
    public static final class menu {
        public static final int select_printer_activity=0x7f0c0000;
    }
    public static final class plurals {
        /**  Template for the notification label for a composite (multiple items) print jobs notification. [CHAR LIMIT=25] 
         */
        public static final int composite_notification_title_template=0x7f0a0001;
        /**  Utterance to announce a change in the number of matches during a search. This is spoken to a blind user. [CHAR LIMIT=none] 
         */
        public static final int print_search_result_count_utterance=0x7f0a0000;
    }
    public static final class string {
        /**  Title of the button to install a print service. [CHAR LIMIT=25] 
         */
        public static final int add_print_service_label=0x7f090025;
        /**  Title for the open all printers UI option in the printer list. [CHAR LIMIT=30] 
         */
        public static final int all_printers=0x7f090018;
        /**  Title for the select printer activity. [CHAR LIMIT=30] 
         */
        public static final int all_printers_label=0x7f090024;
        /**  Title of the PrintSpooler application. [CHAR LIMIT=50] 
         */
        public static final int app_label=0x7f090006;
        /**  Template for the notification label for a blocked print job. [CHAR LIMIT=25] 
         */
        public static final int blocked_notification_title_template=0x7f090031;
        /**  Label for the notification button for cancelling a print job. [CHAR LIMIT=25] 
         */
        public static final int cancel=0x7f090032;
        /**  Template for the notification label for a cancelling print job. [CHAR LIMIT=25] 
         */
        public static final int cancelling_notification_title_template=0x7f09002f;
        /**  Add printer dialog  
 Title for the alert dialog for selecting a print service. [CHAR LIMIT=50] 
         */
        public static final int choose_print_service=0x7f09002b;
        /**  Description for the handle to collapse all print options - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int collapse_handle=0x7f09001e;
        /**  Template for the message that shows the current page out of the total number of pages [CHAR LIMIT=none] 
         */
        public static final int current_page_template=0x7f09001a;
        /**  Description for the handle to expand all print options - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int expand_handle=0x7f09001d;
        /**  Template for the notification label for a failed print job. [CHAR LIMIT=25] 
         */
        public static final int failed_notification_title_template=0x7f090030;
        /**  Title for the temporary dialog show while an app is generating a print job. [CHAR LIMIT=30] 
         */
        public static final int generating_print_job=0x7f090016;
        /**  Title for the pring preview button if there is no PDF viewer isntalled. [CHAR LIMIT=50] 
         */
        public static final int install_for_print_preview=0x7f090014;
        /**  Label of the color mode widget. [CHAR LIMIT=20] 
         */
        public static final int label_color=0x7f09000d;
        /**  Label of the copies count widget. [CHAR LIMIT=20] 
         */
        public static final int label_copies=0x7f090009;
        /**  Label of the copies count for the print options summary. [CHAR LIMIT=20] 
         */
        public static final int label_copies_summary=0x7f09000a;
        /**  Label of the destination widget. [CHAR LIMIT=20] 
         */
        public static final int label_destination=0x7f090008;
        /**  Label of the orientation widget. [CHAR LIMIT=20] 
         */
        public static final int label_orientation=0x7f09000e;
        /**  Label of the page selection widget. [CHAR LIMIT=20] 
         */
        public static final int label_pages=0x7f09000f;
        /**  Label of the paper size widget. [CHAR LIMIT=20] 
         */
        public static final int label_paper_size=0x7f09000b;
        /**  Label of the paper size for the print options summary. [CHAR LIMIT=20] 
         */
        public static final int label_paper_size_summary=0x7f09000c;
        /**  Locale specific values 
         */
        public static final int mediasize_default=0x7f090004;
        public static final int mediasize_standard=0x7f090005;
        public static final int mediasize_standard_china=0x7f090003;
        /**  Media size standards 
         */
        public static final int mediasize_standard_iso=0x7f090000;
        public static final int mediasize_standard_japan=0x7f090002;
        public static final int mediasize_standard_north_america=0x7f090001;
        /**  Label of the print dialog's button for more print options. [CHAR LIMIT=25] 
         */
        public static final int more_options_button=0x7f090007;
        /**  Message that there is no connection to a printer. [CHAR LIMIT=40] 
         */
        public static final int no_connection_to_printer=0x7f090034;
        /**  Description of the current page - spoken to the user [CHAR LIMIT=none] 
         */
        public static final int page_description_template=0x7f09001b;
        /**  Page range exmple used as a hint of how to specify such. [CHAR LIMIT=20] 
         */
        public static final int pages_range_example=0x7f090012;
        /**  Description of an application permission, listed so the user can choose whether
         they want to allow the application to do this. 
         */
        public static final int permdesc_accessAllPrintJobs=0x7f090038;
        /**  Description of an application permission, listed so the user can choose whether they
         want to allow the application to do this. 
         */
        public static final int permdesc_startPrintServiceConfigActivity=0x7f09003a;
        /**  Permissions 
 Title of an application permission, listed so the user can choose whether they want
         to allow the application to do this. 
         */
        public static final int permlab_accessAllPrintJobs=0x7f090037;
        /**  Title of an application permission, listed so the user can choose whether they want
         to allow the application to do this. 
         */
        public static final int permlab_startPrintServiceConfigActivity=0x7f090039;
        /**  Title of the action bar button to got to add a printer. [CHAR LIMIT=25] 
         */
        public static final int print_add_printer=0x7f090028;
        /**  Description for the print button - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int print_button=0x7f09001f;
        /**  Title for the print dialog announced to the user for accessibility. Not shown in the UI. [CHAR LIMIT=none] 
         */
        public static final int print_dialog=0x7f090019;
        /**  Default message for an error while generating a print job. [CHAR LIMIT=50] 
         */
        public static final int print_error_default_message=0x7f09003c;
        /**  Message for the currently selected printer being unavailable. [CHAR LIMIT=100] 
         */
        public static final int print_error_printer_unavailable=0x7f09003e;
        /**  Label for the retry button in the error message. [CHAR LIMIT=50] 
         */
        public static final int print_error_retry=0x7f09003d;
        /**  Title of the menu item to forget a printer. [CHAR LIMIT=25] 
         */
        public static final int print_forget_printer=0x7f09002a;
        /**  Title for the prompt shown as a placeholder if there are no printers while searching. [CHAR LIMIT=50] 
         */
        public static final int print_no_printers=0x7f09002d;
        /**  Message to announce print options are collapsed - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int print_options_collapsed=0x7f090022;
        /**  Message to announce print options are expanded - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int print_options_expanded=0x7f090021;
        /**  Long running operations 
 Message long running operation when preparing print preview. [CHAR LIMIT=50] 
         */
        public static final int print_preparing_preview=0x7f09003f;
        /**  Title for the pring preview button .[CHAR LIMIT=30] 
         */
        public static final int print_preview=0x7f090013;
        /**  Utterance to announce that the search box is hidden. This is spoken to a blind user. [CHAR LIMIT=none] 
         */
        public static final int print_search_box_hidden_utterance=0x7f090027;
        /**  Utterance to announce that the search box is shown. This is spoken to a blind user. [CHAR LIMIT=none] 
         */
        public static final int print_search_box_shown_utterance=0x7f090026;
        /**  Title for the prompt shown as a placeholder if no printers are found while not searching. [CHAR LIMIT=50] 
         */
        public static final int print_searching_for_printers=0x7f09002c;
        /**  Title of the menu item to select a printer. [CHAR LIMIT=25] 
         */
        public static final int print_select_printer=0x7f090029;
        /**  Error messages 
 Message for an error when trying to print to a PDF file. [CHAR LIMIT=50] 
         */
        public static final int print_write_error_message=0x7f09003b;
        /**  Label for a printer that is not available. [CHAR LIMIT=25] 
         */
        public static final int printer_unavailable=0x7f090036;
        /**  Title of the message that the printing application crashed. [CHAR LIMIT=50] 
         */
        public static final int printing_app_crashed=0x7f090015;
        /**  Notifications 
 Template for the notification label for a printing print job. [CHAR LIMIT=25] 
         */
        public static final int printing_notification_title_template=0x7f09002e;
        /**  Label for an unknown reason for failed or blocked print job. [CHAR LIMIT=25] 
         */
        public static final int reason_unknown=0x7f090035;
        /**  Label for the notification button for restarting a filed print job. [CHAR LIMIT=25] 
         */
        public static final int restart=0x7f090033;
        /**  Title for the save as PDF option in the printer list. [CHAR LIMIT=30] 
         */
        public static final int save_as_pdf=0x7f090017;
        /**  Description for the save to PDF button - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int savetopdf_button=0x7f090020;
        /**  Select printer activity 
 Title for the share action bar menu item. [CHAR LIMIT=20] 
         */
        public static final int search=0x7f090023;
        /**  Template for the message to announce the print options summary - spoken to the user. [CHAR LIMIT=none] 
         */
        public static final int summary_template=0x7f09001c;
        /**  Template for the all pages option in the page selection widget. [CHAR LIMIT=20] 
         */
        public static final int template_all_pages=0x7f090010;
        /**  Template for the page range option in the page selection widget. [CHAR LIMIT=20] 
         */
        public static final int template_page_range=0x7f090011;
    }
    public static final class style {
        public static final int PrintActivity=0x7f0b0000;
    }
    public static final class styleable {
        /** Attributes that can be used with a PrintOptionsLayout.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #PrintOptionsLayout_columnCount com.android.printspooler:columnCount}</code></td><td></td></tr>
           </table>
           @see #PrintOptionsLayout_columnCount
         */
        public static final int[] PrintOptionsLayout = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link com.android.printspooler.R.attr#columnCount}
          attribute's value can be found in the {@link #PrintOptionsLayout} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.printspooler:columnCount
        */
        public static final int PrintOptionsLayout_columnCount = 0;
    };
}
