/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.accessorydisplay.sink;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_app=0x7f020000;
    }
    public static final class id {
        public static final int fpsTextView=0x7f060000;
        public static final int logTextView=0x7f060001;
        public static final int surfaceView=0x7f060002;
    }
    public static final class layout {
        public static final int sink_activity=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
    public static final class xml {
        public static final int usb_device_filter=0x7f040000;
    }
}
