/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.test.lib_client;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int label=0x7f060000;
    }
    public static final class layout {
        public static final int dependent_appwidget=0x7f020000;
        public static final int main=0x7f020001;
    }
    public static final class string {
        public static final int app_title=0x7f040000;
        public static final int changes=0x7f040001;
    }
    public static final class style {
        public static final int Theme=0x7f050000;
    }
    public static final class xml {
        public static final int dependent_appwidget_info=0x7f030000;
    }
}
