/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.bidi;

public final class R {
    public static final class attr {
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int color=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int size=0x7f010000;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int text=0x7f010002;
    }
    public static final class drawable {
        public static final int alphabet_a=0x7f020000;
        public static final int alphabet_b=0x7f020001;
        public static final int alphabet_c=0x7f020002;
        public static final int alphabet_d=0x7f020003;
        public static final int alphabet_e=0x7f020004;
        public static final int alphabet_f=0x7f020005;
        public static final int alphabet_g=0x7f020006;
        public static final int alphabet_h=0x7f020007;
        public static final int alphabet_i=0x7f020008;
        public static final int alphabet_j=0x7f020009;
        public static final int end=0x7f02000a;
        public static final int start=0x7f02000b;
    }
    public static final class id {
        public static final int basic=0x7f060000;
        public static final int button_alert_dialog=0x7f060009;
        public static final int canvas2=0x7f06000c;
        public static final int edittext_default=0x7f060004;
        public static final int edittext_ltr=0x7f060006;
        public static final int edittext_password_default=0x7f060002;
        public static final int edittext_rtl=0x7f060008;
        public static final int edittext_url=0x7f06000a;
        public static final int entry_1=0x7f06001f;
        public static final int entry_2=0x7f060022;
        public static final int entry_3=0x7f060025;
        public static final int entry_4=0x7f060028;
        public static final int frame_layout_locale=0x7f06000d;
        public static final int frame_layout_ltr=0x7f06000e;
        public static final int frame_layout_rtl=0x7f06000f;
        public static final int gallery_ltr=0x7f060010;
        public static final int gallery_rtl=0x7f060012;
        public static final int galleryview=0x7f060011;
        public static final int grid_layout_code=0x7f060013;
        public static final int grid_layout_locale=0x7f060014;
        public static final int grid_layout_ltr=0x7f060015;
        public static final int grid_layout_rtl=0x7f060016;
        public static final int label_1=0x7f06001e;
        public static final int label_2=0x7f060021;
        public static final int label_3=0x7f060024;
        public static final int label_4=0x7f060027;
        public static final int linear_layout_locale=0x7f060017;
        public static final int linear_layout_ltr=0x7f060019;
        public static final int linear_layout_rtl=0x7f06001a;
        public static final int main_menu=0x7f06003c;
        public static final int menu_add=0x7f06003d;
        public static final int menu_delete=0x7f06003e;
        public static final int ok_1=0x7f060020;
        public static final int ok_2=0x7f060023;
        public static final int ok_3=0x7f060026;
        public static final int ok_4=0x7f060029;
        public static final int relative_layout_2_locale=0x7f06001d;
        public static final int relative_layout_2_ltr=0x7f06002a;
        public static final int relative_layout_2_rtl=0x7f06002b;
        public static final int relative_layout_ltr=0x7f06002c;
        public static final int relative_layout_rtl=0x7f06002d;
        public static final int spinner_line_1=0x7f06000b;
        public static final int table_layout_locale=0x7f06002e;
        public static final int table_layout_ltr=0x7f06002f;
        public static final int table_layout_rtl=0x7f060030;
        public static final int testframe=0x7f06001c;
        public static final int testlist=0x7f06001b;
        public static final int textview=0x7f060018;
        public static final int textview_alignment_ltr=0x7f060031;
        public static final int textview_alignment_rtl=0x7f060032;
        public static final int textview_default=0x7f060003;
        public static final int textview_direction_ltr=0x7f060033;
        public static final int textview_direction_rtl=0x7f060034;
        public static final int textview_drawables_ltr=0x7f060035;
        public static final int textview_drawables_rtl=0x7f060037;
        public static final int textview_error=0x7f060036;
        public static final int textview_locale=0x7f060038;
        public static final int textview_ltr=0x7f060005;
        public static final int textview_password_default=0x7f060001;
        public static final int textview_rtl=0x7f060007;
        public static final int view_group_margin_mixed=0x7f060039;
        public static final int view_padding=0x7f06003a;
        public static final int view_padding_mixed=0x7f06003b;
    }
    public static final class layout {
        public static final int basic=0x7f030000;
        public static final int canvas2=0x7f030001;
        public static final int custom_list_item=0x7f030002;
        public static final int frame_layout_locale=0x7f030003;
        public static final int frame_layout_ltr=0x7f030004;
        public static final int frame_layout_rtl=0x7f030005;
        public static final int gallery_ltr=0x7f030006;
        public static final int gallery_rtl=0x7f030007;
        public static final int grid_layout_code=0x7f030008;
        public static final int grid_layout_locale=0x7f030009;
        public static final int grid_layout_ltr=0x7f03000a;
        public static final int grid_layout_rtl=0x7f03000b;
        public static final int linear_layout_locale=0x7f03000c;
        public static final int linear_layout_ltr=0x7f03000d;
        public static final int linear_layout_rtl=0x7f03000e;
        public static final int main=0x7f03000f;
        public static final int relative_layout_2_locale=0x7f030010;
        public static final int relative_layout_2_ltr=0x7f030011;
        public static final int relative_layout_2_rtl=0x7f030012;
        public static final int relative_layout_ltr=0x7f030013;
        public static final int relative_layout_rtl=0x7f030014;
        public static final int table_layout_locale=0x7f030015;
        public static final int table_layout_ltr=0x7f030016;
        public static final int table_layout_rtl=0x7f030017;
        public static final int textview_alignment_ltr=0x7f030018;
        public static final int textview_alignment_rtl=0x7f030019;
        public static final int textview_direction_ltr=0x7f03001a;
        public static final int textview_direction_rtl=0x7f03001b;
        public static final int textview_drawables_ltr=0x7f03001c;
        public static final int textview_drawables_rtl=0x7f03001d;
        public static final int textview_locale=0x7f03001e;
        public static final int textview_ltr=0x7f03001f;
        public static final int textview_rtl=0x7f030020;
        public static final int view_group_margin_mixed=0x7f030021;
        public static final int view_padding=0x7f030022;
        public static final int view_padding_mixed=0x7f030023;
    }
    public static final class menu {
        public static final int main_menu=0x7f050000;
    }
    public static final class string {
        public static final int arabic_text=0x7f040015;
        public static final int bold_italic_text=0x7f040019;
        public static final int bold_text=0x7f040018;
        public static final int button1_text=0x7f040001;
        public static final int button2_text=0x7f040002;
        public static final int button3_text=0x7f040003;
        public static final int button4_text=0x7f040004;
        public static final int button_after_text=0x7f040006;
        public static final int button_alert_dialog_text=0x7f04000a;
        public static final int button_before_text=0x7f040008;
        public static final int button_left_text=0x7f040007;
        public static final int button_requestlayout_text=0x7f040009;
        public static final int button_right_text=0x7f040005;
        public static final int button_text=0x7f040000;
        public static final int chinese_text=0x7f040016;
        public static final int composing=0x7f040023;
        public static final int edittext_text=0x7f040010;
        public static final int hebrew_text=0x7f04001b;
        public static final int italic_text=0x7f040017;
        public static final int ltr=0x7f040021;
        public static final int menu_add=0x7f04001c;
        public static final int menu_delete=0x7f04001d;
        public static final int mixed_text_1=0x7f04001a;
        public static final int normal_long_text=0x7f040012;
        public static final int normal_long_text_2=0x7f040013;
        public static final int normal_long_text_3=0x7f040014;
        public static final int normal_text=0x7f040011;
        public static final int pointer_location=0x7f040025;
        public static final int rtl=0x7f040022;
        public static final int textview_default_text=0x7f04000e;
        public static final int textview_hebrew_text=0x7f04001e;
        public static final int textview_latin_text=0x7f04001f;
        public static final int textview_ltr_text=0x7f04000c;
        public static final int textview_multiline_text=0x7f040020;
        public static final int textview_password_default_text=0x7f04000f;
        public static final int textview_rtl_text=0x7f04000d;
        public static final int textview_text=0x7f04000b;
        public static final int url=0x7f040024;
    }
    public static final class styleable {
        /** Attributes that can be used with a DrawTextTestView.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #DrawTextTestView_color com.android.bidi:color}</code></td><td></td></tr>
           <tr><td><code>{@link #DrawTextTestView_size com.android.bidi:size}</code></td><td></td></tr>
           <tr><td><code>{@link #DrawTextTestView_text com.android.bidi:text}</code></td><td></td></tr>
           </table>
           @see #DrawTextTestView_color
           @see #DrawTextTestView_size
           @see #DrawTextTestView_text
         */
        public static final int[] DrawTextTestView = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>This symbol is the offset where the {@link com.android.bidi.R.attr#color}
          attribute's value can be found in the {@link #DrawTextTestView} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.bidi:color
        */
        public static final int DrawTextTestView_color = 1;
        /**
          <p>This symbol is the offset where the {@link com.android.bidi.R.attr#size}
          attribute's value can be found in the {@link #DrawTextTestView} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.bidi:size
        */
        public static final int DrawTextTestView_size = 0;
        /**
          <p>This symbol is the offset where the {@link com.android.bidi.R.attr#text}
          attribute's value can be found in the {@link #DrawTextTestView} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.bidi:text
        */
        public static final int DrawTextTestView_text = 2;
    };
}
