/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.shell;

public final class R {
    public static final class attr {
    }
    public static final class layout {
        public static final int confirm_repeat=0x7f020000;
    }
    public static final class string {
        public static final int app_label=0x7f040000;
        /**  Body of dialog informing user about contents of a bugreport. [CHAR LIMIT=NONE] 
         */
        public static final int bugreport_confirm=0x7f040003;
        /**  Checkbox that indicates this dialog should be shown again when the next bugreport is taken. [CHAR LIMIT=50] 
         */
        public static final int bugreport_confirm_repeat=0x7f040004;
        /**  Text of notification indicating that touching will share the captured bugreport. [CHAR LIMIT=100] 
         */
        public static final int bugreport_finished_text=0x7f040002;
        /**  Title of notification indicating a bugreport has been successfully captured. [CHAR LIMIT=50] 
         */
        public static final int bugreport_finished_title=0x7f040001;
    }
    public static final class xml {
        public static final int file_provider_paths=0x7f030000;
    }
}
