/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.rs.image;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int img1600x1067=0x7f020000;
        public static final int img1600x1067b=0x7f020001;
    }
    public static final class id {
        public static final int benchmarkText=0x7f050003;
        public static final int display=0x7f050002;
        public static final int filterselection=0x7f050004;
        public static final int slider1=0x7f050007;
        public static final int slider1Text=0x7f050006;
        public static final int slider2=0x7f050009;
        public static final int slider2Text=0x7f050008;
        public static final int slider3=0x7f05000b;
        public static final int slider3Text=0x7f05000a;
        public static final int slider4=0x7f05000d;
        public static final int slider4Text=0x7f05000c;
        public static final int slider5=0x7f05000f;
        public static final int slider5Text=0x7f05000e;
        public static final int spinner1=0x7f050005;
        public static final int surface=0x7f050001;
        public static final int toplevel=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int spinner_layout=0x7f030001;
    }
    public static final class string {
        public static final int benchmark=0x7f040007;
        public static final int benchmark_all=0x7f040008;
        /** slider label 
         */
        public static final int blur_description=0x7f040000;
        public static final int gamma=0x7f040005;
        public static final int in_black=0x7f040003;
        public static final int in_white=0x7f040001;
        public static final int out_black=0x7f040004;
        public static final int out_white=0x7f040002;
        public static final int saturation=0x7f040006;
    }
}
