/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.providers.settings;

public final class R {
    public static final class attr {
    }
    public static final class bool {
        public static final int assisted_gps_enabled=0x7f04000b;
        public static final int def_accelerometer_rotation=0x7f040004;
        /**  Default value for Settings.Secure.ACCESSIBILITY_DISPLAY_MAGNIFICATION_AUTO_UPDATE 
         */
        public static final int def_accessibility_display_magnification_auto_update=0x7f04001e;
        /**  Default value for Settings.Secure.ACCESSIBILITY_DISPLAY_MAGNIFICATION_ENABLED 
         */
        public static final int def_accessibility_display_magnification_enabled=0x7f04001d;
        /**  Default for Settings.Secure.ACCESSIBILITY_SCRIPT_INJECTION 
         */
        public static final int def_accessibility_script_injection=0x7f04001a;
        /**  Default for Settings.Secure.ACCESSIBILITY_SPEAK_PASSWORD 
         */
        public static final int def_accessibility_speak_password=0x7f04001b;
        public static final int def_airplane_mode_on=0x7f040001;
        public static final int def_auto_time=0x7f040002;
        public static final int def_auto_time_zone=0x7f040003;
        public static final int def_backup_enabled=0x7f040010;
        public static final int def_bluetooth_on=0x7f040007;
        public static final int def_device_provisioned=0x7f040017;
        public static final int def_dim_screen=0x7f040000;
        /**  Default for DTMF tones enabled 
         */
        public static final int def_dtmf_tones_enabled=0x7f04001f;
        public static final int def_haptic_feedback=0x7f040006;
        public static final int def_install_non_market_apps=0x7f040009;
        public static final int def_lockscreen_disabled=0x7f040016;
        public static final int def_mount_play_notification_snd=0x7f040012;
        public static final int def_mount_ums_autostart=0x7f040013;
        public static final int def_mount_ums_notify_enabled=0x7f040015;
        public static final int def_mount_ums_prompt=0x7f040014;
        public static final int def_netstats_enabled=0x7f04000c;
        public static final int def_networks_available_notification_on=0x7f04000f;
        /**  Default value for whether or not to pulse the notification LED when there is a
         pending notification 
         */
        public static final int def_notification_pulse=0x7f040011;
        /**  Notifications use ringer volume 
         */
        public static final int def_notifications_use_ring_volume=0x7f040018;
        public static final int def_package_verifier_enable=0x7f04000a;
        /**  Set the automatic brightness mode on by default 
         */
        public static final int def_screen_brightness_automatic_mode=0x7f040005;
        /**  Default for UI touch sounds enabled 
         */
        public static final int def_sound_effects_enabled=0x7f040020;
        /**  Development settings 
         */
        public static final int def_stay_on_while_plugged_in=0x7f040021;
        /**  Default for Settings.Secure.TOUCH_EXPLORATION_ENABLED 
         */
        public static final int def_touch_exploration_enabled=0x7f04001c;
        public static final int def_usb_mass_storage_enabled=0x7f04000d;
        /**  Default for Settings.Secure.USER_SETUP_COMPLETE 
         */
        public static final int def_user_setup_complete=0x7f040022;
        /**  Default for Settings.System.VIBRATE_IN_SILENT 
         */
        public static final int def_vibrate_in_silent=0x7f040019;
        public static final int def_wifi_display_on=0x7f040008;
        public static final int def_wifi_on=0x7f04000e;
    }
    public static final class fraction {
        /**  Default value for Settings.Secure.ACCESSIBILITY_DISPLAY_MAGNIFICATION_SCALE 
         */
        public static final int def_accessibility_display_magnification_scale=0x7f070002;
        public static final int def_window_animation_scale=0x7f070000;
        public static final int def_window_transition_scale=0x7f070001;
    }
    public static final class integer {
        public static final int def_dock_audio_media_enabled=0x7f050006;
        public static final int def_dock_sounds_enabled=0x7f050004;
        /**  Default for Settings.Secure.DOWNLOAD_MAX_BYTES_OVER_MOBILE. <=0 if no limit 
         */
        public static final int def_download_manager_max_bytes_over_mobile=0x7f050008;
        /**  Default for Settings.Secure.DOWNLOAD_RECOMMENDED_MAX_BYTES_OVER_MOBILE. <=0 if no limit 
         */
        public static final int def_download_manager_recommended_max_bytes_over_mobile=0x7f050009;
        public static final int def_lockscreen_sounds_enabled=0x7f050005;
        /**  Default for Settings.Secure.LONG_PRESS_TIMEOUT_MILLIS 
         */
        public static final int def_long_press_timeout_millis=0x7f05000a;
        /**  Default for Settings.Global.LOW_BATTERY_SOUND_TIMEOUT.
         0 means no timeout; battery sounds will always play
         >0 is milliseconds of screen-off time after which battery sounds will not play 
         */
        public static final int def_low_battery_sound_timeout=0x7f05000d;
        /**  Number of retries for connecting to DHCP.
         Value here is the same as WifiStateMachine.DEFAULT_MAX_DHCP_RETRIES 
         */
        public static final int def_max_dhcp_retries=0x7f05000c;
        /**  Default for Settings.System.POINTER_SPEED 
         */
        public static final int def_pointer_speed=0x7f05000b;
        /**  user interface sound effects 
         */
        public static final int def_power_sounds_enabled=0x7f050003;
        /**  Default screen brightness, from 0 to 255.  102 is 40%. 
 Default screen brightness, from 0 to 255. 87 is 34%. 
         */
        public static final int def_screen_brightness=0x7f050001;
        /**  30 seconds for default screen timeout 
         */
        public static final int def_screen_off_timeout=0x7f050000;
        /**  Default for Settings.System.USER_ROTATION 
         */
        public static final int def_user_rotation=0x7f050007;
        /**  0 == never, 1 == only when plugged in, 2 == always 
         */
        public static final int def_wifi_sleep_policy=0x7f050002;
    }
    public static final class mipmap {
        public static final int ic_launcher_settings=0x7f020000;
    }
    public static final class string {
        public static final int airplane_mode_toggleable_radios=0x7f060001;
        /**  Name of the activity for Settings storage. 
         */
        public static final int app_label=0x7f06000e;
        /**  Default for Settings.Secure.ACCESSIBILITY_SCRIPT_INJECTION_URL 
         */
        public static final int def_accessibility_screen_reader_url=0x7f06000d;
        /**  Default for Settings.Secure.ACCESSIBILITY_WEB_CONTENT_KEY_BINDINGS 
 DPAD/Trackball UP - traverse previous on current axis and send an event. 
 DPAD/Trackball DOWN - traverse next on current axis and send an event. 
 DPAD/Trackball LEFT - traverse previous on the character navigation axis and send event. 
 DPAD/Trackball RIGHT - traverse next on the character navigation axis end send event. 
 Alt+DPAD/Trackball UP - go to the top of the document. 
 Alt+DPAD/Trackball DOWN - go to the bottom of the document. 
 Alt+DPAD/Trackball LEFT - transition from an axis to another and sends an event.
 Axis transitions: 2 -> 1; 
 Alt+DPAD/Trackball RIGHT - transition from an axis to another and sends an event. 
 Axis transitions:  1 -> 2; 
 Alt+g - go to the previous heading and send an event. 
 Alt+h - go to the next heading and send an event. 
 Alt+COMMA - transition to sentence navigation axis and send an event. 
 Axis transitions:  7 -> 2; 
 Alt+PERIOD - transition to default web view behavior axis and send an event. 
 Axis transitions:  0 -> 7; 1 - > 7; 2 -> 7; 
         */
        public static final int def_accessibility_web_content_key_bindings=0x7f06000c;
        /**  Comma-separated list of bluetooth, wifi, and cell. 
         */
        public static final int def_airplane_mode_radios=0x7f060000;
        public static final int def_backup_transport=0x7f060003;
        public static final int def_car_dock_sound=0x7f060007;
        public static final int def_car_undock_sound=0x7f060008;
        public static final int def_desk_dock_sound=0x7f060005;
        public static final int def_desk_undock_sound=0x7f060006;
        /**  Comma-separated list of location providers.
         Network location is off by default because it requires
         user opt-in via Setup Wizard or Settings.
    
         */
        public static final int def_location_providers_allowed=0x7f060002;
        public static final int def_lock_sound=0x7f060009;
        public static final int def_low_battery_sound=0x7f060004;
        public static final int def_unlock_sound=0x7f06000a;
        public static final int def_wireless_charging_started_sound=0x7f06000b;
    }
    public static final class xml {
        public static final int bookmarks=0x7f030000;
    }
}
