/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.test.dynamic;

public final class R {
    public static final class anim {
        public static final int animation_favorite=0x7f030000;
        public static final int animation_favorite02=0x7f030001;
        public static final int animation_grouping_1_01=0x7f030002;
        public static final int animation_grouping_1_02=0x7f030003;
        public static final int animation_linear_progress_bar_rect1_scale=0x7f030004;
        public static final int animation_linear_progress_bar_rect1_translate=0x7f030005;
        public static final int animation_linear_progress_bar_rect2_scale=0x7f030006;
        public static final int animation_linear_progress_bar_rect2_translate=0x7f030007;
        public static final int trim_path_animation01=0x7f030008;
        public static final int trim_path_animation02=0x7f030009;
        public static final int trim_path_animation03=0x7f03000a;
        public static final int trim_path_animation04=0x7f03000b;
        public static final int trim_path_animation05=0x7f03000c;
        public static final int trim_path_animation06=0x7f03000d;
        public static final int trim_path_animation_progress_bar=0x7f03000e;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int animation_drawable_vector=0x7f020000;
        public static final int animation_vector_drawable01=0x7f020001;
        public static final int animation_vector_drawable_favorite=0x7f020002;
        public static final int animation_vector_drawable_grouping_1=0x7f020003;
        public static final int animation_vector_linear_progress_bar=0x7f020004;
        public static final int animation_vector_progress_bar=0x7f020005;
        public static final int bitmap_drawable01=0x7f020006;
        public static final int icon=0x7f020007;
        public static final int state_animation_vector_drawable01=0x7f020008;
        public static final int state_animation_vector_drawable02=0x7f020009;
        public static final int state_animation_vector_drawable03=0x7f02000a;
        public static final int vector_drawable01=0x7f02000b;
        public static final int vector_drawable02=0x7f02000c;
        public static final int vector_drawable03=0x7f02000d;
        public static final int vector_drawable04=0x7f02000e;
        public static final int vector_drawable05=0x7f02000f;
        public static final int vector_drawable06=0x7f020010;
        public static final int vector_drawable07=0x7f020011;
        public static final int vector_drawable08=0x7f020012;
        public static final int vector_drawable09=0x7f020013;
        public static final int vector_drawable10=0x7f020014;
        public static final int vector_drawable11=0x7f020015;
        public static final int vector_drawable12=0x7f020016;
        public static final int vector_drawable13=0x7f020017;
        public static final int vector_drawable14=0x7f020018;
        public static final int vector_drawable15=0x7f020019;
        public static final int vector_drawable16=0x7f02001a;
        public static final int vector_drawable17=0x7f02001b;
        public static final int vector_drawable18=0x7f02001c;
        public static final int vector_drawable19=0x7f02001d;
        public static final int vector_drawable20=0x7f02001e;
        public static final int vector_drawable21=0x7f02001f;
        public static final int vector_drawable22=0x7f020020;
        public static final int vector_drawable23=0x7f020021;
        public static final int vector_drawable24=0x7f020022;
        public static final int vector_drawable25=0x7f020023;
        public static final int vector_drawable26=0x7f020024;
        public static final int vector_drawable27=0x7f020025;
        public static final int vector_drawable28=0x7f020026;
        public static final int vector_drawable_favorite=0x7f020027;
        public static final int vector_drawable_grouping_1=0x7f020028;
        public static final int vector_drawable_linear_progress_bar=0x7f020029;
        public static final int vector_drawable_progress_bar=0x7f02002a;
        public static final int vector_icon_create=0x7f02002b;
        public static final int vector_icon_delete=0x7f02002c;
        public static final int vector_icon_heart=0x7f02002d;
        public static final int vector_icon_schedule=0x7f02002e;
        public static final int vector_icon_settings=0x7f02002f;
        public static final int vector_test01=0x7f020030;
        public static final int vector_test02=0x7f020031;
    }
    public static final class id {
        public static final int animation_drawable_vector=0x7f060000;
        public static final int off=0x7f060002;
        public static final int on=0x7f060001;
    }
    public static final class interpolator {
        public static final int custom_path_interpolator=0x7f040000;
        public static final int custom_path_interpolator_favorite=0x7f040001;
        public static final int custom_path_interpolator_grouping_1_01=0x7f040002;
        public static final int trim_end_interpolator=0x7f040003;
        public static final int trim_start_interpolator=0x7f040004;
    }
    public static final class string {
        public static final int equal2=0x7f050004;
        public static final int heart=0x7f050006;
        public static final int rectangle=0x7f050002;
        public static final int rectangle2=0x7f050003;
        public static final int rectangle200=0x7f050007;
        public static final int round_box=0x7f050005;
        public static final int triangle=0x7f050001;
        public static final int twoLinePathData=0x7f050000;
    }
}
