/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.printspooler;

public final class R {
    public static final class array {
        /**  Arrays 
 Color mode labels. 
         */
        public static final int color_mode_labels=0x7f040003;
        /**  Everything else is ISO 
         */
        public static final int mediasize_to_standard_map=0x7f040000;
        /**  Orientation labels. 
         */
        public static final int orientation_labels=0x7f040004;
        /**  Page options labels. 
         */
        public static final int page_options_labels=0x7f040005;
        public static final int page_options_values=0x7f040002;
        public static final int pdf_printer_media_sizes=0x7f040001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int action_button_background=0x7f050004;
        public static final int container_background=0x7f050000;
        public static final int important_text=0x7f050001;
        public static final int item_text_color=0x7f050005;
        public static final int print_option_title=0x7f050002;
        public static final int separator=0x7f050003;
    }
    public static final class dimen {
        public static final int print_dialog_frame_max_width_dip=0x7f070000;
        public static final int printer_list_view_padding_end=0x7f070002;
        public static final int printer_list_view_padding_start=0x7f070001;
    }
    public static final class drawable {
        public static final int ic_menu_print=0x7f020000;
        public static final int ic_restart=0x7f020001;
        public static final int stat_notify_cancelling=0x7f020002;
    }
    public static final class id {
        public static final int action_add_printer=0x7f0c0018;
        public static final int action_search=0x7f0c0017;
        public static final int advanced_settings_button=0x7f0c000b;
        public static final int advanced_settings_container=0x7f0c000a;
        public static final int cancel_button=0x7f0c0010;
        public static final int color_spinner=0x7f0c0003;
        public static final int content_container=0x7f0c0000;
        public static final int content_generating=0x7f0c000d;
        public static final int copies_edittext=0x7f0c0002;
        public static final int destination_spinner=0x7f0c0001;
        public static final int empty_print_state=0x7f0c0015;
        public static final int icon=0x7f0c0011;
        public static final int message=0x7f0c000e;
        public static final int ok_button=0x7f0c000f;
        public static final int orientation_spinner=0x7f0c0007;
        public static final int page_range_edittext=0x7f0c0009;
        public static final int page_range_title=0x7f0c0008;
        public static final int paper_size_spinner=0x7f0c0006;
        public static final int print_button=0x7f0c000c;
        public static final int progress_bar=0x7f0c0016;
        public static final int range_options_spinner=0x7f0c0005;
        public static final int range_options_title=0x7f0c0004;
        public static final int select_printer_fragment=0x7f0c0014;
        public static final int subtitle=0x7f0c0013;
        public static final int title=0x7f0c0012;
    }
    public static final class integer {
        public static final int page_option_value_all=0x7f060000;
        public static final int page_option_value_page_range=0x7f060001;
    }
    public static final class layout {
        public static final int print_job_config_activity_container=0x7f030000;
        public static final int print_job_config_activity_content_editing=0x7f030001;
        public static final int print_job_config_activity_content_error=0x7f030002;
        public static final int print_job_config_activity_content_generating=0x7f030003;
        public static final int printer_dropdown_item=0x7f030004;
        public static final int printer_list_item=0x7f030005;
        public static final int select_printer_activity=0x7f030006;
        public static final int select_printer_fragment=0x7f030007;
        public static final int spinner_dropdown_item=0x7f030008;
    }
    public static final class menu {
        public static final int select_printer_activity=0x7f0b0000;
    }
    public static final class plurals {
        /**  Template for the notificaiton label for a composite (multiple items) print jobs notification. [CHAR LIMIT=25] 
         */
        public static final int composite_notification_title_template=0x7f090001;
        /**  Utterance to announce a change in the number of matches during a search. This is spoken to a blind user. [CHAR LIMIT=none] 
         */
        public static final int print_search_result_count_utterance=0x7f090000;
    }
    public static final class string {
        /**  Title of the button to install a print service. [CHAR LIMIT=25] 
         */
        public static final int add_print_service_label=0x7f08001b;
        /**  Label of the print dialog's button for advanced printer settings. [CHAR LIMIT=25] 
         */
        public static final int advanced_settings_button=0x7f080007;
        /**  Title for the open all printers UI option in the printer list. [CHAR LIMIT=30] 
         */
        public static final int all_printers=0x7f080017;
        /**  Title for the select printer activity. [CHAR LIMIT=30] 
         */
        public static final int all_printers_label=0x7f08001a;
        /**  Title of the PrintSpooler application. [CHAR LIMIT=50] 
         */
        public static final int app_label=0x7f080006;
        /**  Template for the notificaiton label for a blocked print job. [CHAR LIMIT=25] 
         */
        public static final int blocked_notification_title_template=0x7f080027;
        /**  Label for the notification button for cancelling a print job. [CHAR LIMIT=25] 
         */
        public static final int cancel=0x7f080028;
        /**  Template for the notificaiton label for a cancelling print job. [CHAR LIMIT=25] 
         */
        public static final int cancelling_notification_title_template=0x7f080025;
        /**  Add printer dialog  
 Title for the alert dialog for selecting a print service. [CHAR LIMIT=50] 
         */
        public static final int choose_print_service=0x7f080021;
        /**  Template for the notificaiton label for a failed print job. [CHAR LIMIT=25] 
         */
        public static final int failed_notification_title_template=0x7f080026;
        /**  Title for the temporary dialog show while an app is generating a print job. [CHAR LIMIT=30] 
         */
        public static final int generating_print_job=0x7f080015;
        /**  Title for the pring preview button if there is no PDF viewer isntalled. [CHAR LIMIT=50] 
         */
        public static final int install_for_print_preview=0x7f080012;
        /**  Label of the color mode widget. [CHAR LIMIT=20] 
         */
        public static final int label_color=0x7f08000d;
        /**  Label of the copies count widget. [CHAR LIMIT=20] 
         */
        public static final int label_copies=0x7f08000b;
        /**  Label of the destination widget. [CHAR LIMIT=20] 
         */
        public static final int label_destination=0x7f08000a;
        /**  Label of the orientation widget. [CHAR LIMIT=20] 
         */
        public static final int label_orientation=0x7f08000e;
        /**  Label of the page selection widget. [CHAR LIMIT=20] 
         */
        public static final int label_pages=0x7f08000f;
        /**  Label of the paper size widget. [CHAR LIMIT=20] 
         */
        public static final int label_paper_size=0x7f08000c;
        /**  Locale specific values 
         */
        public static final int mediasize_default=0x7f080004;
        public static final int mediasize_standard=0x7f080005;
        public static final int mediasize_standard_china=0x7f080003;
        /**  Media size standards 
         */
        public static final int mediasize_standard_iso=0x7f080000;
        public static final int mediasize_standard_japan=0x7f080002;
        public static final int mediasize_standard_north_america=0x7f080001;
        /**  Message that there is no connection to a printer. [CHAR LIMIT=40] 
         */
        public static final int no_connection_to_printer=0x7f08002a;
        /**  Title if the number of pages in a printed document is unknown. [CHAR LIMIT=20] 
         */
        public static final int page_count_unknown=0x7f080014;
        /**  Page range exmple used as a hint of how to specify such. [CHAR LIMIT=20] 
         */
        public static final int pages_range_example=0x7f080010;
        /**  Description of an application permission, listed so the user can choose whether
         they want to allow the application to do this. 
         */
        public static final int permdesc_accessAllPrintJobs=0x7f08002f;
        /**  Description of an application permission, listed so the user can choose whether they
         want to allow the application to do this. 
         */
        public static final int permdesc_startPrintServiceConfigActivity=0x7f080031;
        /**  Permissions 
 Title of an application permission, listed so the user can choose whether they want
         to allow the application to do this. 
         */
        public static final int permlab_accessAllPrintJobs=0x7f08002e;
        /**  Title of an application permission, listed so the user can choose whether they want
         to allow the application to do this. 
         */
        public static final int permlab_startPrintServiceConfigActivity=0x7f080030;
        /**  Title of the action bar button to got to add a printer. [CHAR LIMIT=25] 
         */
        public static final int print_add_printer=0x7f08001e;
        /**  Label of the print dialog's print button. [CHAR LIMIT=16] 
         */
        public static final int print_button=0x7f080008;
        /**  Title for the print dialog announced to the user for accessibility. Not shown in the UI. [CHAR LIMIT=none] 
         */
        public static final int print_dialog=0x7f080018;
        /**  Default message of an alert dialog for app error while generating a print job. [CHAR LIMIT=50] 
         */
        public static final int print_error_default_message=0x7f08002d;
        /**  Title of the menu item to forget a printer. [CHAR LIMIT=25] 
         */
        public static final int print_forget_printer=0x7f080020;
        /**  Title for the prompt shown as a placeholder if there are no printers while searching. [CHAR LIMIT=50] 
         */
        public static final int print_no_printers=0x7f080023;
        /**  Title for the pring preview button .[CHAR LIMIT=30] 
         */
        public static final int print_preview=0x7f080011;
        /**  Utterance to announce that the search box is hidden. This is spoken to a blind user. [CHAR LIMIT=none] 
         */
        public static final int print_search_box_hidden_utterance=0x7f08001d;
        /**  Utterance to announce that the search box is shown. This is spoken to a blind user. [CHAR LIMIT=none] 
         */
        public static final int print_search_box_shown_utterance=0x7f08001c;
        /**  Title for the prompt shown as a placeholder if no printers are found while not searching. [CHAR LIMIT=50] 
         */
        public static final int print_searching_for_printers=0x7f080022;
        /**  Title of the menu item to select a printer. [CHAR LIMIT=25] 
         */
        public static final int print_select_printer=0x7f08001f;
        /**  Label for a printer that is not available. [CHAR LIMIT=25] 
         */
        public static final int printer_unavailable=0x7f08002c;
        /**  Title of the message that the printing application crashed. [CHAR LIMIT=50] 
         */
        public static final int printing_app_crashed=0x7f080013;
        /**  Notifications 
 Template for the notificaiton label for a printing print job. [CHAR LIMIT=25] 
         */
        public static final int printing_notification_title_template=0x7f080024;
        /**  Label for an unknown reason for failed or blocked print job. [CHAR LIMIT=25] 
         */
        public static final int reason_unknown=0x7f08002b;
        /**  Label for the notification button for restrating a filed print job. [CHAR LIMIT=25] 
         */
        public static final int restart=0x7f080029;
        /**  Title for the save as PDF option in the printer list. [CHAR LIMIT=30] 
         */
        public static final int save_as_pdf=0x7f080016;
        /**  Label of the print dialog's save button. [CHAR LIMIT=16] 
         */
        public static final int save_button=0x7f080009;
        /**  Select printer activity 
 Title for the share action bar menu item. [CHAR LIMIT=20] 
         */
        public static final int search=0x7f080019;
    }
    public static final class style {
        public static final int PrintJobConfigActivityTheme=0x7f0a0003;
        public static final int PrintOptionEditTextStyle=0x7f0a0002;
        public static final int PrintOptionSpinnerStyle=0x7f0a0001;
        public static final int PrintOptionTitleTextAppearance=0x7f0a0000;
        public static final int SelectPrinterActivityActionBarStyle=0x7f0a0005;
        public static final int SelectPrinterActivityTheme=0x7f0a0004;
    }
}
