/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.wallpaper;

public final class R {
    public static final class array {
        public static final int polar_clock_palette_ids=0x7f040001;
        public static final int polar_clock_palette_names=0x7f040000;
    }
    public static final class attr {
    }
    public static final class bool {
        public static final int config_enable_fall_wallpaper=0x7f050002;
        public static final int config_enable_galaxy_wallpaper=0x7f050001;
        public static final int config_enable_grass_wallpaper=0x7f050000;
        public static final int config_enable_nexus_wallpaper=0x7f050003;
        public static final int config_enable_polar_clock_wallpaper=0x7f050004;
    }
    public static final class drawable {
        public static final int flares=0x7f020000;
        public static final int galaxy_thumb=0x7f020001;
        public static final int glow=0x7f020002;
        public static final int grass_thumb=0x7f020003;
        public static final int ic_launcher_wallpaper=0x7f020004;
        public static final int leaves=0x7f020005;
        public static final int led_blue=0x7f020006;
        public static final int led_green=0x7f020007;
        public static final int led_red=0x7f020008;
        public static final int led_yellow=0x7f020009;
        public static final int light1=0x7f02000a;
        public static final int nexus_thumb=0x7f02000b;
        public static final int night=0x7f02000c;
        public static final int polarclock_thumb=0x7f02000d;
        public static final int pond=0x7f02000e;
        public static final int pulse=0x7f02000f;
        public static final int pyramid_background=0x7f020010;
        public static final int seethru_thumb=0x7f020011;
        public static final int sky=0x7f020012;
        public static final int space=0x7f020013;
        public static final int sunrise=0x7f020014;
        public static final int sunset=0x7f020015;
        public static final int water_thumb=0x7f020016;
    }
    public static final class integer {
        public static final int nexus_mode=0x7f060000;
    }
    public static final class string {
        /**  Polar clock: title of settings activity 
         */
        public static final int clock_settings=0x7f070007;
        /**  Polar clock: label for "palette" pref 
         */
        public static final int palette=0x7f07000a;
        /**  Polar clock: palette name 
         */
        public static final int palette_black_c=0x7f07000f;
        /**  Polar clock: palette name 
         */
        public static final int palette_gray=0x7f07000b;
        /**  Polar clock: palette name 
         */
        public static final int palette_halloween=0x7f070010;
        /**  Polar clock: palette name 
         */
        public static final int palette_matrix=0x7f07000d;
        /**  Polar clock: palette name 
         */
        public static final int palette_oceanic=0x7f070012;
        /**  Polar clock: palette name 
         */
        public static final int palette_violet=0x7f07000c;
        /**  Polar clock: palette name 
         */
        public static final int palette_white_c=0x7f07000e;
        /**  Polar clock: palette name 
         */
        public static final int palette_zenburn=0x7f070011;
        /**  Polar clock: label for "show seconds" pref 
         */
        public static final int show_seconds=0x7f070008;
        /**  Polar clock: label for "variable widths" pref 
         */
        public static final int variable_line_width=0x7f070009;
        /**  Wallpaper showing a clock 
         */
        public static final int wallpaper_clock=0x7f070004;
        public static final int wallpaper_clock_author=0x7f070005;
        public static final int wallpaper_clock_desc=0x7f070006;
        /**  Wallpaper showing the camera preview 
         */
        public static final int wallpaper_walkaround=0x7f070001;
        public static final int wallpaper_walkaround_author=0x7f070002;
        public static final int wallpaper_walkaround_desc=0x7f070003;
        /**  Application name 
         */
        public static final int wallpapers=0x7f070000;
    }
    public static final class xml {
        public static final int polar_clock=0x7f030000;
        public static final int polar_clock_palettes=0x7f030001;
        public static final int polar_clock_prefs=0x7f030002;
        public static final int walkaround=0x7f030003;
    }
}
