/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.contacts.common.unittest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int android=0x7f020000;
        public static final int default_icon=0x7f020001;
        public static final int ic_contact_picture=0x7f020002;
        public static final int phone_icon=0x7f020003;
    }
    public static final class string {
        public static final int authenticator_basic_label=0x7f040001;
        public static final int test_string=0x7f040000;
    }
    public static final class xml {
        public static final int contacts_fallback=0x7f030000;
        public static final int contacts_readonly=0x7f030001;
        public static final int iconset=0x7f030002;
        public static final int missing_contacts_base=0x7f030003;
        public static final int missing_contacts_name=0x7f030004;
        public static final int missing_contacts_name_attr1=0x7f030005;
        public static final int missing_contacts_name_attr2=0x7f030006;
        public static final int missing_contacts_name_attr3=0x7f030007;
        public static final int missing_contacts_name_attr4=0x7f030008;
        public static final int missing_contacts_name_attr5=0x7f030009;
        public static final int missing_contacts_name_attr6=0x7f03000a;
        public static final int missing_contacts_name_attr7=0x7f03000b;
        public static final int missing_contacts_photo=0x7f03000c;
        public static final int test_basic_contacts=0x7f03000d;
        public static final int test_basic_syncadapter=0x7f03000e;
    }
}
