/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.cts.view;

public final class R {
    public static final class anim {
        public static final int accelerate_alpha=0x7f040000;
        public static final int accelerate_decelerate_alpha=0x7f040001;
        public static final int alpha=0x7f040002;
        public static final int anim_alpha=0x7f040003;
        public static final int anim_gridlayout=0x7f040004;
        public static final int anim_rotate=0x7f040005;
        public static final int anim_scale=0x7f040006;
        public static final int anim_set=0x7f040007;
        public static final int anim_translate=0x7f040008;
        public static final int cycle_alpha=0x7f040009;
        public static final int cycle_interpolator=0x7f04000a;
        public static final int decelerate_alpha=0x7f04000b;
        public static final int layout_anim_controller_animation=0x7f04000c;
    }
    public static final class array {
        public static final int difficultyLevel=0x7f070002;
        public static final int integers=0x7f070001;
        public static final int string=0x7f070003;
        public static final int strings=0x7f070000;
        public static final int table_row_layout=0x7f070004;
    }
    public static final class attr {
        /** <p>May be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>type</code></td><td>28</td><td></td></tr>
<tr><td><code>data</code></td><td>0xff00ff00</td><td></td></tr>
<tr><td><code>asset_cookie</code></td><td>0</td><td></td></tr>
<tr><td><code>resource_id</code></td><td>0</td><td></td></tr>
<tr><td><code>changing_config</code></td><td>0</td><td></td></tr>
</table>
         */
        public static final int Type1=0x7f010000;
        /** <p>May be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>type</code></td><td>28</td><td></td></tr>
<tr><td><code>data</code></td><td>0xff0000ff</td><td></td></tr>
<tr><td><code>asset_cookie</code></td><td>0</td><td></td></tr>
<tr><td><code>resource_id</code></td><td>0</td><td></td></tr>
<tr><td><code>changing_config</code></td><td>0</td><td></td></tr>
</table>
         */
        public static final int Type2=0x7f010001;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>val1</code></td><td>1</td><td></td></tr>
<tr><td><code>val2</code></td><td>2</td><td></td></tr>
<tr><td><code>val10</code></td><td>10</td><td></td></tr>
</table>
         */
        public static final int testEnum=0x7f010012;
        /** <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bit1</code></td><td>0x1</td><td></td></tr>
<tr><td><code>bit2</code></td><td>0x2</td><td></td></tr>
<tr><td><code>bit31</code></td><td>0x40000000</td><td></td></tr>
</table>
         */
        public static final int testFlags=0x7f010013;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int testString=0x7f010014;
        /**  Color of text (usually same as colorForeground). 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int textColor=0x7f010018;
        /**  Color of highlighted text. 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int textColorHighlight=0x7f010019;
        /**  Color of hint text (displayed when the field is empty). 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int textColorHint=0x7f01001a;
        /**  Color of link text (URLs). 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int textColorLink=0x7f01001b;
        /**  Size of text. Recommended dimension type for text is "sp" for scaled-pixels (example: 15sp).
         Supported values include the following:<p/>
    <ul>
        <li><b>px</b> Pixels</li>
        <li><b>sp</b> Scaled pixels (scaled to relative pixel size on screen). See {@link android.util.DisplayMetrics} for more information.</li>
        <li><b>pt</b> Points</li>
        <li><b>dip</b> Device independent pixels. See {@link android.util.DisplayMetrics} for more information.</li>
    </ul>
    
         <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSize=0x7f010015;
        /**  Default text typeface style. 
         <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>bold</code></td><td>1</td><td></td></tr>
<tr><td><code>italic</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int textStyle=0x7f010017;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeAngle=0x7f010028;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeBitmap=0x7f010024;
        /**  Drawable theming attributes 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeBoolean=0x7f01001e;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeColor=0x7f01001f;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeDimension=0x7f010022;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeDrawable=0x7f010023;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeFloat=0x7f010020;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeGravity=0x7f010026;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeInteger=0x7f010021;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeNinePatch=0x7f010025;
        /**  Theme reference used to override parent theme. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int themeOverrideAttr=0x7f01001d;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>May be an integer value, such as "<code>100</code>".
<p>May be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>May be a floating point value, such as "<code>1.2</code>".
<p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>May be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
         */
        public static final int themeTileMode=0x7f010027;
        /**  Integer used to uniquely identify theme overrides. 
         <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int themeType=0x7f01001c;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type1=0x7f010002;
        /** <p>Must be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type10=0x7f01000b;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type11=0x7f01000c;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type12=0x7f01000d;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
         */
        public static final int type13=0x7f01000e;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type14=0x7f01000f;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int type15=0x7f010010;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type16=0x7f010011;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type2=0x7f010003;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type3=0x7f010004;
        /** <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int type4=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type5=0x7f010006;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type6=0x7f010007;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type7=0x7f010008;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int type8=0x7f010009;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int type9=0x7f01000a;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>sans</code></td><td>1</td><td></td></tr>
<tr><td><code>serif</code></td><td>2</td><td></td></tr>
<tr><td><code>monospace</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int typeface=0x7f010016;
    }
    public static final class color {
        public static final int failColor=0x7f080002;
        public static final int testcolor1=0x7f080000;
        public static final int testcolor2=0x7f080001;
    }
    public static final class drawable {
        public static final int black=0x7f020011;
        public static final int blue=0x7f020010;
        public static final int faces=0x7f020000;
        public static final int failed=0x7f020001;
        public static final int icon_black=0x7f020002;
        public static final int icon_blue=0x7f020003;
        public static final int icon_green=0x7f020004;
        public static final int icon_red=0x7f020005;
        public static final int icon_yellow=0x7f020006;
        public static final int ninepatch_0=0x7f020007;
        public static final int ninepatch_1=0x7f020008;
        public static final int no_padding=0x7f020009;
        public static final int padding_0=0x7f02000a;
        public static final int pass=0x7f02000b;
        public static final int red=0x7f02000f;
        public static final int scenery=0x7f02000c;
        public static final int size_48x48=0x7f02000d;
        public static final int start=0x7f02000e;
        public static final int yellow=0x7f020012;
    }
    public static final class id {
        public static final int MAIN_MENU=0x7f0c0067;
        public static final int abslistview_root=0x7f0c0011;
        public static final int anim_window=0x7f0c0013;
        public static final int anim_window_parent=0x7f0c0012;
        public static final int asset_cookie=0x7f0c0000;
        public static final int autotext_default=0x7f0c0026;
        public static final int background_tint=0x7f0c0056;
        public static final int bit1=0x7f0c0008;
        public static final int bit2=0x7f0c0009;
        public static final int bit31=0x7f0c000a;
        public static final int bold=0x7f0c000f;
        public static final int bottom_left_button=0x7f0c0017;
        public static final int bottom_right_button=0x7f0c0018;
        public static final int button1=0x7f0c0061;
        public static final int cancel=0x7f0c0049;
        public static final int changing_config=0x7f0c0001;
        public static final int checkable_group=0x7f0c0075;
        public static final int checkable_item_1=0x7f0c0076;
        public static final int checkable_item_2=0x7f0c0077;
        public static final int checkable_item_3=0x7f0c0078;
        public static final int country=0x7f0c0048;
        public static final int data=0x7f0c0002;
        public static final int entry=0x7f0c002e;
        public static final int exclusive_checkable_group=0x7f0c0079;
        public static final int exclusive_checkable_item_1=0x7f0c007a;
        public static final int exclusive_checkable_item_2=0x7f0c007b;
        public static final int exclusive_checkable_item_3=0x7f0c007c;
        public static final int failed=0x7f0c0084;
        public static final int first_child=0x7f0c0030;
        public static final int first_least_item=0x7f0c0070;
        public static final int first_most_item=0x7f0c006c;
        public static final int fit_windows=0x7f0c004f;
        public static final int goto_menu_id=0x7f0c0068;
        public static final int gridlayout_anim_gridview=0x7f0c001d;
        public static final int hidden_by_group=0x7f0c0088;
        public static final int hidden_group=0x7f0c0087;
        public static final int hidden_item=0x7f0c0086;
        public static final int inflated_id=0x7f0c005f;
        public static final int italic=0x7f0c0010;
        public static final int last_child=0x7f0c0031;
        public static final int last_least_item=0x7f0c006e;
        public static final int last_most_item=0x7f0c006a;
        public static final int layout=0x7f0c0014;
        public static final int layout_textviewtest=0x7f0c0033;
        public static final int least_used_items=0x7f0c006d;
        public static final int linearlayout=0x7f0c0060;
        public static final int listview_addwindow=0x7f0c0062;
        public static final int listview_window=0x7f0c0063;
        public static final int menu_search=0x7f0c0081;
        public static final int middle_least_item=0x7f0c006f;
        public static final int middle_most_item=0x7f0c006b;
        public static final int mock_textview_center=0x7f0c003b;
        public static final int mock_textview_left=0x7f0c0039;
        public static final int mock_textview_right=0x7f0c003a;
        public static final int mock_view=0x7f0c0029;
        public static final int mock_view_padding_bottom=0x7f0c0054;
        public static final int mock_view_padding_full=0x7f0c0050;
        public static final int mock_view_padding_left=0x7f0c0051;
        public static final int mock_view_padding_right=0x7f0c0052;
        public static final int mock_view_padding_runtime_updated=0x7f0c0055;
        public static final int mock_view_padding_top=0x7f0c0053;
        public static final int mocklinearlayout=0x7f0c005c;
        public static final int monospace=0x7f0c000b;
        public static final int most_used_items=0x7f0c0069;
        public static final int noncheckable_group=0x7f0c0071;
        public static final int noncheckable_item_1=0x7f0c0072;
        public static final int noncheckable_item_2=0x7f0c0073;
        public static final int noncheckable_item_3=0x7f0c0074;
        public static final int nongroup_checkable_item_1=0x7f0c007e;
        public static final int nongroup_checkable_item_2=0x7f0c007f;
        public static final int nongroup_checkable_item_3=0x7f0c0080;
        public static final int normal=0x7f0c000c;
        public static final int numeric_decimal=0x7f0c0021;
        public static final int numeric_default=0x7f0c001e;
        public static final int numeric_integer=0x7f0c001f;
        public static final int numeric_integer_decimal=0x7f0c0023;
        public static final int numeric_signed=0x7f0c0020;
        public static final int numeric_signed_decimal=0x7f0c0024;
        public static final int numeric_signed_decimal_integer=0x7f0c0025;
        public static final int numeric_signed_integer=0x7f0c0022;
        public static final int ok=0x7f0c004a;
        public static final int pass=0x7f0c0083;
        public static final int presentation_button1=0x7f0c0064;
        public static final int presentation_button2=0x7f0c0065;
        public static final int presentation_button3=0x7f0c0066;
        public static final int resource_id=0x7f0c0003;
        public static final int sans=0x7f0c000d;
        public static final int scroll_view=0x7f0c002f;
        public static final int scroll_view_2=0x7f0c004e;
        public static final int searchView1=0x7f0c0032;
        public static final int serif=0x7f0c000e;
        public static final int start=0x7f0c0082;
        public static final int submenu=0x7f0c007d;
        public static final int symbol=0x7f0c004b;
        public static final int symbolball=0x7f0c004c;
        public static final int tag_mock_view=0x7f0c002a;
        public static final int tag_viewlayout_root=0x7f0c0028;
        public static final int testparent=0x7f0c0057;
        public static final int testview=0x7f0c0058;
        public static final int textview1=0x7f0c0059;
        public static final int textview2=0x7f0c005a;
        public static final int textview3=0x7f0c005b;
        public static final int textview_drawable_1_1=0x7f0c003e;
        public static final int textview_drawable_1_2=0x7f0c003f;
        public static final int textview_drawable_2_1=0x7f0c0040;
        public static final int textview_drawable_2_2=0x7f0c0041;
        public static final int textview_drawable_3_1=0x7f0c0042;
        public static final int textview_drawable_3_2=0x7f0c0043;
        public static final int textview_drawable_4_1=0x7f0c0044;
        public static final int textview_drawable_4_2=0x7f0c0046;
        public static final int textview_drawable_5_1=0x7f0c0045;
        public static final int textview_drawable_5_2=0x7f0c0047;
        public static final int textview_ltr=0x7f0c003c;
        public static final int textview_password=0x7f0c0035;
        public static final int textview_rtl=0x7f0c003d;
        public static final int textview_singleLine=0x7f0c0036;
        public static final int textview_text=0x7f0c0037;
        public static final int textview_textAttr=0x7f0c0034;
        public static final int textview_text_two_lines=0x7f0c0038;
        public static final int top_left_button=0x7f0c0015;
        public static final int top_right_button=0x7f0c0016;
        public static final int type=0x7f0c0004;
        public static final int val1=0x7f0c0005;
        public static final int val10=0x7f0c0006;
        public static final int val2=0x7f0c0007;
        public static final int view1=0x7f0c0019;
        public static final int view2=0x7f0c001a;
        public static final int view3=0x7f0c001b;
        public static final int view4=0x7f0c001c;
        public static final int view_attr=0x7f0c002d;
        public static final int view_inner=0x7f0c002c;
        public static final int view_outer=0x7f0c002b;
        public static final int viewgrouptest_stub=0x7f0c005d;
        public static final int viewlayout_root=0x7f0c0027;
        public static final int viewstub=0x7f0c005e;
        public static final int visible_item=0x7f0c0085;
        public static final int warning=0x7f0c004d;
    }
    public static final class integer {
        public static final int reference=0x7f060000;
    }
    public static final class layout {
        public static final int abslistview_layout=0x7f030000;
        public static final int anim_layout=0x7f030001;
        public static final int focus_finder_layout=0x7f030002;
        public static final int focus_handling_layout=0x7f030003;
        public static final int gridlayout_anim_controller_layout=0x7f030004;
        public static final int inflater_layout=0x7f030005;
        public static final int inflater_layout_tags=0x7f030006;
        public static final int inflater_override_theme_layout=0x7f030007;
        public static final int inputmethod_edittext=0x7f030008;
        public static final int scrollview_layout=0x7f030009;
        public static final int searchview=0x7f03000a;
        public static final int textview_layout=0x7f03000b;
        public static final int using_views_layout=0x7f03000c;
        public static final int view_layout=0x7f03000d;
        public static final int view_layout_position=0x7f03000e;
        public static final int view_visibility_layout=0x7f03000f;
        public static final int viewgroup_margin_layout=0x7f030010;
        public static final int viewgrouptest_stub=0x7f030011;
        public static final int viewstub_layout=0x7f030012;
        public static final int viewtreeobserver_layout=0x7f030013;
        public static final int windowstub_addlayout=0x7f030014;
        public static final int windowstub_layout=0x7f030015;
        public static final int windowstub_presentation=0x7f030016;
    }
    public static final class menu {
        public static final int browser=0x7f0b0000;
        public static final int category_order=0x7f0b0001;
        public static final int checkable=0x7f0b0002;
        public static final int menu_searchview=0x7f0b0003;
        public static final int title_icon=0x7f0b0004;
        public static final int visible_shortcut=0x7f0b0005;
    }
    public static final class string {
        public static final int activity_forwarding=0x7f09000b;
        public static final int alert_dialog_negative=0x7f090019;
        public static final int alert_dialog_neutral=0x7f09001a;
        public static final int alert_dialog_password=0x7f090017;
        public static final int alert_dialog_positive=0x7f090018;
        public static final int alert_dialog_username=0x7f090016;
        public static final int am=0x7f090022;
        public static final int android_intent_action_preference=0x7f09006a;
        public static final int animationutils_test_alpha=0x7f09002b;
        public static final int animationutils_test_gridlayout=0x7f090031;
        public static final int animationutils_test_instructions=0x7f09002a;
        public static final int animationutils_test_layout=0x7f090030;
        public static final int animationutils_test_rotate=0x7f09002d;
        public static final int animationutils_test_scale=0x7f09002c;
        public static final int animationutils_test_set=0x7f09002f;
        public static final int animationutils_test_translate=0x7f09002e;
        public static final int authenticator_label=0x7f090081;
        public static final int back=0x7f09000e;
        public static final int button=0x7f090085;
        public static final int checkboxpref_depend=0x7f09004a;
        public static final int checkboxpref_depend_summary=0x7f09004c;
        public static final int checkboxpref_depend_title=0x7f09004b;
        public static final int checkboxpref_key=0x7f090045;
        public static final int checkboxpref_summary=0x7f090047;
        public static final int checkboxpref_summary_off=0x7f090049;
        public static final int checkboxpref_summary_on=0x7f090048;
        public static final int checkboxpref_title=0x7f090046;
        public static final int chronometer_text=0x7f090021;
        public static final int coerceBooleanToString=0x7f09003d;
        public static final int coerceColorToString=0x7f09003e;
        public static final int coerceDimensionToString=0x7f090040;
        public static final int coerceFloatToString=0x7f09003f;
        public static final int coerceFractionToString=0x7f090041;
        public static final int coerceIntegerToString=0x7f09003c;
        public static final int context_test_string1=0x7f090028;
        public static final int context_test_string2=0x7f090029;
        public static final int country=0x7f09007b;
        public static final int country_warning=0x7f09007d;
        public static final int def_pref_key=0x7f09006b;
        public static final int def_pref_summary=0x7f09006d;
        public static final int def_pref_title=0x7f09006c;
        public static final int dialogpref_cancel=0x7f090063;
        public static final int dialogpref_default_value=0x7f09005f;
        public static final int dialogpref_dialog_title=0x7f09005d;
        public static final int dialogpref_key=0x7f09005e;
        public static final int dialogpref_message=0x7f090061;
        public static final int dialogpref_summary=0x7f090060;
        public static final int dialogpref_sure=0x7f090062;
        public static final int dialogpref_title=0x7f09005c;
        public static final int easy=0x7f090057;
        public static final int edit_text=0x7f090010;
        public static final int edittextpref_default_value=0x7f09004e;
        public static final int edittextpref_dialog_title=0x7f090051;
        public static final int edittextpref_key=0x7f09004d;
        public static final int edittextpref_summary=0x7f090050;
        public static final int edittextpref_text=0x7f090052;
        public static final int edittextpref_title=0x7f09004f;
        public static final int explain=0x7f090006;
        public static final int footer_view=0x7f09005a;
        public static final int formattedStringNone=0x7f090042;
        public static final int formattedStringOne=0x7f090043;
        public static final int formattedStringTwo=0x7f090044;
        public static final int forward_target=0x7f09000f;
        public static final int forwarding=0x7f09000c;
        public static final int generated_image=0x7f09008b;
        public static final int go=0x7f09000d;
        public static final int hard=0x7f090059;
        public static final int header_view=0x7f09005b;
        public static final int hello_android=0x7f090015;
        public static final int hello_world=0x7f090014;
        public static final int holo_generator=0x7f090087;
        public static final int holo_light_generator=0x7f090089;
        public static final int holo_light_test=0x7f090088;
        public static final int holo_test=0x7f090086;
        public static final int horizontal_text_1=0x7f090035;
        public static final int horizontal_text_2=0x7f090036;
        public static final int horizontal_text_3=0x7f090037;
        public static final int id_cancel=0x7f090027;
        public static final int id_ok=0x7f090026;
        public static final int listpref_dialogtitle=0x7f090056;
        public static final int listpref_key=0x7f090053;
        public static final int listpref_summary=0x7f090055;
        public static final int listpref_title=0x7f090054;
        public static final int long_text=0x7f09008e;
        public static final int medium=0x7f090058;
        public static final int metadata_text=0x7f090034;
        public static final int notify=0x7f09001b;
        public static final int permdesc_testDenied=0x7f090005;
        public static final int permdesc_testDynamic=0x7f090003;
        public static final int permdesc_testGranted=0x7f090001;
        public static final int permlab_testDenied=0x7f090004;
        public static final int permlab_testDynamic=0x7f090002;
        public static final int permlab_testGranted=0x7f090000;
        public static final int pm=0x7f090023;
        public static final int pref_depend_key=0x7f090067;
        public static final int pref_depend_summary=0x7f090069;
        public static final int pref_depend_title=0x7f090068;
        public static final int pref_key=0x7f090064;
        public static final int pref_summary=0x7f090066;
        public static final int pref_title=0x7f090065;
        public static final int rectangle200=0x7f09008f;
        public static final int reference=0x7f09003b;
        public static final int reference_image=0x7f09008a;
        public static final int relative_view1=0x7f09006e;
        public static final int relative_view10=0x7f090077;
        public static final int relative_view11=0x7f090078;
        public static final int relative_view12=0x7f090079;
        public static final int relative_view13=0x7f09007a;
        public static final int relative_view2=0x7f09006f;
        public static final int relative_view3=0x7f090070;
        public static final int relative_view4=0x7f090071;
        public static final int relative_view5=0x7f090072;
        public static final int relative_view6=0x7f090073;
        public static final int relative_view7=0x7f090074;
        public static final int relative_view8=0x7f090075;
        public static final int relative_view9=0x7f090076;
        public static final int sample_text=0x7f09008d;
        public static final int search_label=0x7f090082;
        public static final int symbol=0x7f09007c;
        public static final int table_layout_first=0x7f09001d;
        public static final int table_layout_long=0x7f090020;
        public static final int table_layout_second=0x7f09001e;
        public static final int table_layout_third=0x7f09001f;
        public static final int tabs_1=0x7f09001c;
        public static final int tag1=0x7f090083;
        public static final int tag2=0x7f090084;
        public static final int text=0x7f090011;
        public static final int text_country=0x7f090012;
        public static final int text_name=0x7f090013;
        public static final int text_view_hello=0x7f090007;
        public static final int text_view_hello_two_lines=0x7f090008;
        public static final int text_view_hint=0x7f09000a;
        public static final int text_view_simple_hint=0x7f090009;
        public static final int themes_prompt=0x7f09008c;
        public static final int twolinelistitem_test_text1=0x7f090032;
        public static final int twolinelistitem_test_text2=0x7f090033;
        public static final int version_cur=0x7f09007e;
        public static final int version_old=0x7f09007f;
        public static final int version_v3=0x7f090080;
        public static final int vertical_text_1=0x7f090038;
        public static final int vertical_text_2=0x7f090039;
        public static final int vertical_text_3=0x7f09003a;
        public static final int viewanimator_test=0x7f090025;
        public static final int viewgroup_test=0x7f090024;
    }
    public static final class style {
        public static final int TestEnum1=0x7f0a000b;
        public static final int TestEnum1_EmptyInherit=0x7f0a0013;
        public static final int TestEnum10=0x7f0a000d;
        public static final int TestEnum2=0x7f0a000c;
        public static final int TestFlag1=0x7f0a000e;
        public static final int TestFlag1And2=0x7f0a0011;
        public static final int TestFlag1And2And31=0x7f0a0012;
        public static final int TestFlag2=0x7f0a000f;
        public static final int TestFlag31=0x7f0a0010;
        public static final int TestProgressBar=0x7f0a0015;
        public static final int Test_Theme=0x7f0a0016;
        public static final int TextAppearance=0x7f0a0005;
        public static final int TextAppearance_All=0x7f0a0007;
        public static final int TextAppearance_Colors=0x7f0a0008;
        public static final int TextAppearance_NotColors=0x7f0a0009;
        public static final int TextAppearance_Style=0x7f0a000a;
        public static final int TextAppearance_WithColor=0x7f0a0006;
        public static final int TextViewWithColorAndAppearance=0x7f0a0003;
        public static final int TextViewWithColorButWithOutAppearance=0x7f0a0002;
        public static final int TextViewWithoutColorAndAppearance=0x7f0a0001;
        public static final int TextViewWithoutColorButWithAppearance=0x7f0a0004;
        public static final int Theme_AlertDialog=0x7f0a0014;
        public static final int Theme_NoSwipeDismiss=0x7f0a001b;
        public static final int Theme_OverrideAttr=0x7f0a0019;
        public static final int Theme_OverrideInner=0x7f0a0018;
        public static final int Theme_OverrideOuter=0x7f0a0017;
        public static final int Theme_ThemedDrawableTest=0x7f0a001a;
        public static final int Whatever=0x7f0a0000;
    }
    public static final class xml {
        public static final int merge=0x7f050000;
        public static final int method=0x7f050001;
    }
    public static final class styleable {
        /** Attributes that can be used with a EnumStyle.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #EnumStyle_testEnum com.android.cts.view:testEnum}</code></td><td></td></tr>
           </table>
           @see #EnumStyle_testEnum
         */
        public static final int[] EnumStyle = {
            0x7f010012
        };
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#testEnum}
          attribute's value can be found in the {@link #EnumStyle} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>val1</code></td><td>1</td><td></td></tr>
<tr><td><code>val2</code></td><td>2</td><td></td></tr>
<tr><td><code>val10</code></td><td>10</td><td></td></tr>
</table>
          @attr name com.android.cts.view:testEnum
        */
        public static final int EnumStyle_testEnum = 0;
        /** Attributes that can be used with a FlagStyle.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #FlagStyle_testFlags com.android.cts.view:testFlags}</code></td><td></td></tr>
           </table>
           @see #FlagStyle_testFlags
         */
        public static final int[] FlagStyle = {
            0x7f010013
        };
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#testFlags}
          attribute's value can be found in the {@link #FlagStyle} array.


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>bit1</code></td><td>0x1</td><td></td></tr>
<tr><td><code>bit2</code></td><td>0x2</td><td></td></tr>
<tr><td><code>bit31</code></td><td>0x40000000</td><td></td></tr>
</table>
          @attr name com.android.cts.view:testFlags
        */
        public static final int FlagStyle_testFlags = 0;
        /** Attributes that can be used with a Style1.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #Style1_Type1 com.android.cts.view:Type1}</code></td><td></td></tr>
           <tr><td><code>{@link #Style1_Type2 com.android.cts.view:Type2}</code></td><td></td></tr>
           </table>
           @see #Style1_Type1
           @see #Style1_Type2
         */
        public static final int[] Style1 = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#Type1}
          attribute's value can be found in the {@link #Style1} array.


          <p>May be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>type</code></td><td>28</td><td></td></tr>
<tr><td><code>data</code></td><td>0xff00ff00</td><td></td></tr>
<tr><td><code>asset_cookie</code></td><td>0</td><td></td></tr>
<tr><td><code>resource_id</code></td><td>0</td><td></td></tr>
<tr><td><code>changing_config</code></td><td>0</td><td></td></tr>
</table>
          @attr name com.android.cts.view:Type1
        */
        public static final int Style1_Type1 = 0;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#Type2}
          attribute's value can be found in the {@link #Style1} array.


          <p>May be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>type</code></td><td>28</td><td></td></tr>
<tr><td><code>data</code></td><td>0xff0000ff</td><td></td></tr>
<tr><td><code>asset_cookie</code></td><td>0</td><td></td></tr>
<tr><td><code>resource_id</code></td><td>0</td><td></td></tr>
<tr><td><code>changing_config</code></td><td>0</td><td></td></tr>
</table>
          @attr name com.android.cts.view:Type2
        */
        public static final int Style1_Type2 = 1;
        /** Attributes that can be used with a TestConfig.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TestConfig_testString com.android.cts.view:testString}</code></td><td></td></tr>
           </table>
           @see #TestConfig_testString
         */
        public static final int[] TestConfig = {
            0x7f010014
        };
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#testString}
          attribute's value can be found in the {@link #TestConfig} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:testString
        */
        public static final int TestConfig_testString = 0;
        /** Attributes that can be used with a TextAppearance.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TextAppearance_textColor com.android.cts.view:textColor}</code></td><td> Color of text (usually same as colorForeground).</td></tr>
           <tr><td><code>{@link #TextAppearance_textColorHighlight com.android.cts.view:textColorHighlight}</code></td><td> Color of highlighted text.</td></tr>
           <tr><td><code>{@link #TextAppearance_textColorHint com.android.cts.view:textColorHint}</code></td><td> Color of hint text (displayed when the field is empty).</td></tr>
           <tr><td><code>{@link #TextAppearance_textColorLink com.android.cts.view:textColorLink}</code></td><td> Color of link text (URLs).</td></tr>
           <tr><td><code>{@link #TextAppearance_textSize com.android.cts.view:textSize}</code></td><td> Size of text.</td></tr>
           <tr><td><code>{@link #TextAppearance_textStyle com.android.cts.view:textStyle}</code></td><td> Default text typeface style.</td></tr>
           <tr><td><code>{@link #TextAppearance_typeface com.android.cts.view:typeface}</code></td><td></td></tr>
           </table>
           @see #TextAppearance_textColor
           @see #TextAppearance_textColorHighlight
           @see #TextAppearance_textColorHint
           @see #TextAppearance_textColorLink
           @see #TextAppearance_textSize
           @see #TextAppearance_textStyle
           @see #TextAppearance_typeface
         */
        public static final int[] TextAppearance = {
            0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018,
            0x7f010019, 0x7f01001a, 0x7f01001b
        };
        /**
          <p>
          @attr description
           Color of text (usually same as colorForeground). 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.android.cts.view:textColor
        */
        public static final int TextAppearance_textColor = 3;
        /**
          <p>
          @attr description
           Color of highlighted text. 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.android.cts.view:textColorHighlight
        */
        public static final int TextAppearance_textColorHighlight = 4;
        /**
          <p>
          @attr description
           Color of hint text (displayed when the field is empty). 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.android.cts.view:textColorHint
        */
        public static final int TextAppearance_textColorHint = 5;
        /**
          <p>
          @attr description
           Color of link text (URLs). 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.android.cts.view:textColorLink
        */
        public static final int TextAppearance_textColorLink = 6;
        /**
          <p>
          @attr description
           Size of text. Recommended dimension type for text is "sp" for scaled-pixels (example: 15sp).
         Supported values include the following:<p/>
    <ul>
        <li><b>px</b> Pixels</li>
        <li><b>sp</b> Scaled pixels (scaled to relative pixel size on screen). See {@link android.util.DisplayMetrics} for more information.</li>
        <li><b>pt</b> Points</li>
        <li><b>dip</b> Device independent pixels. See {@link android.util.DisplayMetrics} for more information.</li>
    </ul>
    


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.android.cts.view:textSize
        */
        public static final int TextAppearance_textSize = 0;
        /**
          <p>
          @attr description
           Default text typeface style. 


          <p>Must be one or more (separated by '|') of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>bold</code></td><td>1</td><td></td></tr>
<tr><td><code>italic</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.android.cts.view:textStyle
        */
        public static final int TextAppearance_textStyle = 2;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#typeface}
          attribute's value can be found in the {@link #TextAppearance} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>normal</code></td><td>0</td><td></td></tr>
<tr><td><code>sans</code></td><td>1</td><td></td></tr>
<tr><td><code>serif</code></td><td>2</td><td></td></tr>
<tr><td><code>monospace</code></td><td>3</td><td></td></tr>
</table>
          @attr name com.android.cts.view:typeface
        */
        public static final int TextAppearance_typeface = 1;
        /** Attributes that can be used with a style1.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #style1_type1 com.android.cts.view:type1}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type10 com.android.cts.view:type10}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type11 com.android.cts.view:type11}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type12 com.android.cts.view:type12}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type13 com.android.cts.view:type13}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type14 com.android.cts.view:type14}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type15 com.android.cts.view:type15}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type16 com.android.cts.view:type16}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type2 com.android.cts.view:type2}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type3 com.android.cts.view:type3}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type4 com.android.cts.view:type4}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type5 com.android.cts.view:type5}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type6 com.android.cts.view:type6}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type7 com.android.cts.view:type7}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type8 com.android.cts.view:type8}</code></td><td></td></tr>
           <tr><td><code>{@link #style1_type9 com.android.cts.view:type9}</code></td><td></td></tr>
           </table>
           @see #style1_type1
           @see #style1_type10
           @see #style1_type11
           @see #style1_type12
           @see #style1_type13
           @see #style1_type14
           @see #style1_type15
           @see #style1_type16
           @see #style1_type2
           @see #style1_type3
           @see #style1_type4
           @see #style1_type5
           @see #style1_type6
           @see #style1_type7
           @see #style1_type8
           @see #style1_type9
         */
        public static final int[] style1 = {
            0x7f010002, 0x7f010003, 0x7f010004, 0x7f010005,
            0x7f010006, 0x7f010007, 0x7f010008, 0x7f010009,
            0x7f01000a, 0x7f01000b, 0x7f01000c, 0x7f01000d,
            0x7f01000e, 0x7f01000f, 0x7f010010, 0x7f010011
        };
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type1}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type1
        */
        public static final int style1_type1 = 0;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type10}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a fractional value, which is a floating point number appended with either % or %p, such as "<code>14.5%</code>".
The % suffix always means a percentage of the base size; the optional %p suffix provides a size relative to
some parent container.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type10
        */
        public static final int style1_type10 = 9;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type11}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type11
        */
        public static final int style1_type11 = 10;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type12}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type12
        */
        public static final int style1_type12 = 11;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type13}
          attribute's value can be found in the {@link #style1} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
          @attr name com.android.cts.view:type13
        */
        public static final int style1_type13 = 12;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type14}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type14
        */
        public static final int style1_type14 = 13;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type15}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.cts.view:type15
        */
        public static final int style1_type15 = 14;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type16}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type16
        */
        public static final int style1_type16 = 15;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type2}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type2
        */
        public static final int style1_type2 = 1;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type3}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type3
        */
        public static final int style1_type3 = 2;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type4}
          attribute's value can be found in the {@link #style1} array.


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          @attr name com.android.cts.view:type4
        */
        public static final int style1_type4 = 3;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type5}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type5
        */
        public static final int style1_type5 = 4;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type6}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type6
        */
        public static final int style1_type6 = 5;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type7}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type7
        */
        public static final int style1_type7 = 6;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type8}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.android.cts.view:type8
        */
        public static final int style1_type8 = 7;
        /**
          <p>This symbol is the offset where the {@link com.android.cts.view.R.attr#type9}
          attribute's value can be found in the {@link #style1} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.android.cts.view:type9
        */
        public static final int style1_type9 = 8;
    };
}
