/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.test.assistant;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_action_assist=0x7f020000;
        public static final int ic_action_assist_activated=0x7f020001;
        public static final int ic_action_assist_normal=0x7f020002;
    }
    public static final class id {
        public static final int label=0x7f050000;
        public static final int search_input=0x7f050001;
    }
    public static final class layout {
        public static final int assist_intent_activity=0x7f030000;
    }
    public static final class string {
        public static final int activity_title=0x7f040000;
        public static final int search_label=0x7f040001;
    }
}
