/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.nfc;

public final class R {
    public static final class array {
        /**  The accepted mime-types when NFC is enabled in setup wizard.
         Mime-types must be lower case, wildcards are *not* accepted. 
         */
        public static final int provisioning_mime_types=0x7f060000;
    }
    public static final class attr {
    }
    public static final class bool {
        /**  Whether the device can receive NFC data in setup wizard 
         */
        public static final int enable_nfc_provisioning=0x7f050000;
    }
    public static final class drawable {
        public static final int back=0x7f020000;
        public static final int ic_menu_cancel_holo_dark=0x7f020001;
        public static final int icon=0x7f020002;
        public static final int nfc=0x7f020003;
        public static final int tap_again=0x7f020004;
    }
    public static final class id {
        public static final int appicon=0x7f080000;
        public static final int applabel=0x7f080001;
        public static final int banner=0x7f080002;
        public static final int blacklayer=0x7f080007;
        public static final int calltoaction=0x7f080005;
        public static final int fireflies=0x7f080004;
        public static final int resolver_list=0x7f080003;
        public static final int retrytext=0x7f080008;
        public static final int screenshot=0x7f080006;
        public static final int textview=0x7f080009;
    }
    public static final class layout {
        public static final int cardemu_item=0x7f030000;
        public static final int cardemu_payment_item=0x7f030001;
        public static final int cardemu_resolver=0x7f030002;
        public static final int screenshot=0x7f030003;
        public static final int tapagain=0x7f030004;
    }
    public static final class raw {
        public static final int end=0x7f040000;
        public static final int error=0x7f040001;
        public static final int start=0x7f040002;
    }
    public static final class string {
        /**  Content description of the NFC enabled notification icon for accessibility (not shown on the screen). [CHAR LIMIT=NONE] 
         */
        public static final int accessibility_nfc_enabled=0x7f070006;
        public static final int app_name=0x7f070000;
        public static final int beam_canceled=0x7f07000c;
        public static final int beam_complete=0x7f07000a;
        public static final int beam_failed=0x7f07000b;
        public static final int beam_handover_not_supported=0x7f07000f;
        public static final int beam_outgoing=0x7f070009;
        public static final int beam_progress=0x7f070008;
        public static final int beam_touch_to_view=0x7f07000e;
        public static final int beam_try_again=0x7f070010;
        public static final int cancel=0x7f07000d;
        /**  Label for a dialog showing a list of applications that can be used to complete the NFC action 
         */
        public static final int complete_with=0x7f070021;
        public static final int confirm_pairing=0x7f070019;
        public static final int connect_headset_failed=0x7f070013;
        public static final int connected_headset=0x7f070012;
        public static final int connecting_headset=0x7f070011;
        /**  String that is telling the user that his NFC transaction couldn't be completed with the
         indicated app 
         */
        public static final int could_not_use_app=0x7f07001f;
        /**  String that is telling the user that his default app for tap and pay has been removed,
         and asks him to pick another app as default.
         */
        public static final int default_pay_app_removed=0x7f070022;
        public static final int disconnected_headset=0x7f070015;
        public static final int disconnecting_headset=0x7f070014;
        public static final int failed_to_enable_bt=0x7f070018;
        /**  A notification action string prompting the user to add contact details to the People application [CHAR-LIMIT=64] 
         */
        public static final int inbound_me_profile_text=0x7f070003;
        /**  A notification description string informing the user that contact details were received over NFC [CHAR-LIMIT=64] 
         */
        public static final int inbound_me_profile_title=0x7f070002;
        public static final int nfcUserLabel=0x7f070001;
        /**  A notification action string prompting the user to share their contact details over NFC [CHAR-LIMIT=64] 
         */
        public static final int outbound_me_profile_text=0x7f070005;
        /**  A notification description string asking the user to share their contact details over NFC [CHAR-LIMIT=64] 
         */
        public static final int outbound_me_profile_title=0x7f070004;
        public static final int pair_no=0x7f07001b;
        public static final int pair_yes=0x7f07001a;
        public static final int pairing_headset=0x7f070016;
        public static final int pairing_headset_failed=0x7f070017;
        /**  Label for a dialog showing a list of applications can be paid with 
         */
        public static final int pay_with=0x7f070020;
        /**  String that is prompting the user to tap his NFC phone against a generic NFC reader again, to
         pay with the specified app 
         */
        public static final int tap_again_to_complete=0x7f07001d;
        /**  String that is prompting the user to tap his NFC phone against a payment reader again, to
         pay with the specified app 
         */
        public static final int tap_again_to_pay=0x7f07001c;
        public static final int touch=0x7f070007;
        /**  String that is telling the user that his NFC transaction couldn't be completed with the
         indicated app 
         */
        public static final int transaction_failure=0x7f07001e;
    }
}
