/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.test.hwuicompare;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /**  NOTE: the below MUST be multiples of 64 
         */
        public static final int layer_height=0x7f050000;
        public static final int layer_height_double=0x7f050002;
        public static final int layer_width=0x7f050001;
        public static final int layer_width_double=0x7f050003;
    }
    public static final class drawable {
        public static final int sunset1=0x7f020000;
    }
    public static final class id {
        public static final int compare_image_view=0x7f060005;
        public static final int current_error=0x7f060008;
        public static final int hardware_image_view=0x7f060002;
        public static final int hardware_view=0x7f060000;
        public static final int next=0x7f060007;
        public static final int previous=0x7f060006;
        public static final int show_error_heatmap=0x7f06000b;
        public static final int show_hardware_version=0x7f060009;
        public static final int show_software_version=0x7f06000a;
        public static final int software_image_view=0x7f060001;
        public static final int software_view=0x7f060004;
        public static final int spinner_layout=0x7f060003;
    }
    public static final class layout {
        public static final int automatic_layout=0x7f030000;
        public static final int manual_layout=0x7f030001;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        /**   select and display the next combination of painting options
         */
        public static final int next_combination=0x7f040005;
        /**   select and display the previous combination of painting options
         */
        public static final int previous_combination=0x7f040006;
        /**  show layer error heatmap 
         */
        public static final int show_error_heatmap=0x7f040004;
        /**  show layer error 
         */
        public static final int show_error_values=0x7f040003;
        /**  show hardware rendered version of the layer 
         */
        public static final int show_hardware_version=0x7f040001;
        /**  show software rendered version of the layer 
         */
        public static final int show_software_version=0x7f040002;
    }
}
