/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.frameworks.servicestests;

public final class R {
    public static final class attr {
    }
    public static final class raw {
        public static final int netstats_uid_v4=0x7f030000;
        public static final int netstats_v1=0x7f030001;
        public static final int test1=0x7f030002;
        public static final int test1_nosig=0x7f030003;
        public static final int test1_wrongpackage=0x7f030004;
    }
    public static final class xml {
        public static final int device_admin_sample=0x7f020000;
    }
}
