/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.android.webview.chromium;

public final class R {
    public static final class attr {
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int select_dialog_multichoice=0x00010000;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static int select_dialog_singlechoice=0x00010001;
    }
    public static final class color {
        public static int color_picker_background_color=0x00050001;
        public static int color_picker_border_color=0x00050000;
        public static int dropdown_dark_divider_color=0x00050003;
        public static int dropdown_divider_color=0x00050002;
    }
    public static final class dimen {
        public static int color_button_height=0x00060001;
        /** 
         14.5 = Seekbar thumb width - border width, but it depends on the width
	     of the seek bar icon.
    
         */
        public static int color_picker_gradient_margin=0x00060000;
        /** 
         Fallback values if the corresponding com.android.internal.R dimensions
         cannot be retrieved by name.
         Note: Constants taken directly from Android's core/res/values/config.xml.
    
         */
        public static int config_min_scaling_span=0x00060004;
        public static int config_min_scaling_touch_major=0x00060005;
        public static int dropdown_item_divider_height=0x00060003;
        public static int dropdown_item_height=0x00060002;
        /**  Link Preview dimensions 
         */
        public static int link_preview_overlay_radius=0x00060006;
    }
    public static final class drawable {
        public static int bubble=0x00020000;
        public static int bubble_arrow_up=0x00020001;
        public static int color_button_background=0x00020002;
        public static int color_picker_advanced_select_handle=0x00020003;
        public static int color_picker_border=0x00020004;
        public static int dropdown_popup_background=0x00020005;
        public static int dropdown_popup_background_down=0x00020006;
        public static int dropdown_popup_background_up=0x00020007;
        public static int ic_media_video_poster=0x00020008;
        public static int ic_menu_search_holo_light=0x00020009;
        public static int ic_menu_share_holo_light=0x0002000a;
        public static int icon_webview=0x0002000b;
        public static int ondemand_overlay=0x0002000c;
        public static int pageinfo_warning_major=0x0002000d;
    }
    public static final class id {
        public static int ampm=0x0008001a;
        public static int arrow_image=0x00080021;
        public static int color_button_swatch=0x00080024;
        public static int color_picker_advanced=0x00080005;
        public static int color_picker_simple=0x00080006;
        public static int date_picker=0x0008000c;
        public static int date_time_suggestion=0x0008000e;
        public static int date_time_suggestion_label=0x00080010;
        public static int date_time_suggestion_value=0x0008000f;
        public static int dropdown_label=0x00080012;
        public static int dropdown_menu_text=0x00080011;
        public static int dropdown_popup_window=0x00080000;
        public static int dropdown_sublabel=0x00080013;
        public static int gradient=0x00080003;
        public static int gradient_border=0x00080002;
        public static int hour=0x00080014;
        public static int icon_view=0x00080020;
        public static int main_text=0x00080022;
        public static int milli=0x00080019;
        public static int minute=0x00080015;
        public static int more_colors_button=0x00080008;
        public static int more_colors_button_border=0x00080007;
        public static int pickers=0x0008001b;
        public static int position_in_year=0x0008001c;
        public static int second=0x00080017;
        public static int second_colon=0x00080016;
        public static int second_dot=0x00080018;
        public static int seek_bar=0x00080004;
        public static int select_action_menu_copy=0x00080027;
        public static int select_action_menu_cut=0x00080026;
        public static int select_action_menu_paste=0x00080028;
        public static int select_action_menu_select_all=0x00080025;
        public static int select_action_menu_share=0x00080029;
        public static int select_action_menu_web_search=0x0008002a;
        public static int selected_color_view=0x0008000b;
        public static int selected_color_view_border=0x0008000a;
        public static int sub_text=0x00080023;
        public static int text=0x00080001;
        public static int text_wrapper=0x0008001f;
        public static int time_picker=0x0008000d;
        public static int title=0x00080009;
        public static int top_view=0x0008001e;
        public static int year=0x0008001d;
    }
    public static final class layout {
        public static int color_picker_advanced_component=0x00030000;
        public static int color_picker_dialog_content=0x00030001;
        public static int color_picker_dialog_title=0x00030002;
        public static int date_time_picker_dialog=0x00030003;
        public static int date_time_suggestion=0x00030004;
        public static int dropdown_item=0x00030005;
        public static int multi_field_time_picker_dialog=0x00030006;
        public static int two_field_date_picker=0x00030007;
        public static int validation_message_bubble=0x00030008;
    }
    public static final class menu {
        public static int select_action_menu=0x00090000;
    }
    public static final class string {
        public static int accessibility_content_view=0x00040002;
        public static int accessibility_date_picker_month=0x00040012;
        public static int accessibility_date_picker_week=0x00040013;
        public static int accessibility_date_picker_year=0x00040014;
        public static int accessibility_datetime_picker_date=0x00040010;
        public static int accessibility_datetime_picker_time=0x00040011;
        public static int accessibility_time_picker_ampm=0x00040019;
        public static int accessibility_time_picker_hour=0x00040015;
        public static int accessibility_time_picker_milli=0x00040018;
        public static int accessibility_time_picker_minute=0x00040016;
        public static int accessibility_time_picker_second=0x00040017;
        public static int actionbar_share=0x00040000;
        public static int actionbar_web_search=0x00040001;
        public static int color_picker_button_black=0x00040032;
        public static int color_picker_button_blue=0x0004002e;
        public static int color_picker_button_cancel=0x0004002a;
        public static int color_picker_button_cyan=0x0004002d;
        public static int color_picker_button_green=0x0004002f;
        public static int color_picker_button_magenta=0x00040030;
        public static int color_picker_button_more=0x00040025;
        public static int color_picker_button_red=0x0004002c;
        public static int color_picker_button_set=0x00040029;
        public static int color_picker_button_white=0x00040033;
        public static int color_picker_button_yellow=0x00040031;
        public static int color_picker_dialog_title=0x0004002b;
        public static int color_picker_hue=0x00040026;
        public static int color_picker_saturation=0x00040027;
        public static int color_picker_value=0x00040028;
        public static int copy_to_clipboard_failure_message=0x00040034;
        public static int date_picker_dialog_clear=0x00040005;
        public static int date_picker_dialog_other_button_label=0x00040006;
        public static int date_picker_dialog_set=0x00040004;
        public static int date_picker_dialog_title=0x00040003;
        public static int date_time_picker_dialog_title=0x00040007;
        public static int low_memory_error=0x00040023;
        public static int media_player_error_button=0x0004001d;
        public static int media_player_error_text_invalid_progressive_playback=0x0004001b;
        public static int media_player_error_text_unknown=0x0004001c;
        public static int media_player_error_title=0x0004001a;
        public static int media_player_loading_video=0x0004001e;
        public static int month_picker_dialog_title=0x0004000e;
        public static int opening_file_error=0x00040024;
        public static int profiler_error_toast=0x00040022;
        public static int profiler_no_storage_toast=0x00040021;
        public static int profiler_started_toast=0x0004001f;
        public static int profiler_stopped_toast=0x00040020;
        public static int time_picker_dialog_am=0x00040009;
        public static int time_picker_dialog_hour_minute_separator=0x0004000b;
        public static int time_picker_dialog_minute_second_separator=0x0004000c;
        public static int time_picker_dialog_pm=0x0004000a;
        public static int time_picker_dialog_second_subsecond_separator=0x0004000d;
        public static int time_picker_dialog_title=0x00040008;
        /**  Contextual action bar item for sharing a block of text via email, or
         other method. [CHAR-LIMIT=128] 
         */
        public static int webviewchromium_private_browsing_warning=0x00040035;
        public static int week_picker_dialog_title=0x0004000f;
    }
    public static final class style {
        public static int DropdownPopupWindow=0x00070000;
        public static int SelectPopupDialog=0x00070001;
    }
    public static void onResourcesLoaded(int packageId) {
        attr.select_dialog_multichoice = (attr.select_dialog_multichoice & 0x00ffffff) | (packageId << 24);
        attr.select_dialog_singlechoice = (attr.select_dialog_singlechoice & 0x00ffffff) | (packageId << 24);
        color.color_picker_background_color = (color.color_picker_background_color & 0x00ffffff) | (packageId << 24);
        color.color_picker_border_color = (color.color_picker_border_color & 0x00ffffff) | (packageId << 24);
        color.dropdown_dark_divider_color = (color.dropdown_dark_divider_color & 0x00ffffff) | (packageId << 24);
        color.dropdown_divider_color = (color.dropdown_divider_color & 0x00ffffff) | (packageId << 24);
        dimen.color_button_height = (dimen.color_button_height & 0x00ffffff) | (packageId << 24);
        dimen.color_picker_gradient_margin = (dimen.color_picker_gradient_margin & 0x00ffffff) | (packageId << 24);
        dimen.config_min_scaling_span = (dimen.config_min_scaling_span & 0x00ffffff) | (packageId << 24);
        dimen.config_min_scaling_touch_major = (dimen.config_min_scaling_touch_major & 0x00ffffff) | (packageId << 24);
        dimen.dropdown_item_divider_height = (dimen.dropdown_item_divider_height & 0x00ffffff) | (packageId << 24);
        dimen.dropdown_item_height = (dimen.dropdown_item_height & 0x00ffffff) | (packageId << 24);
        dimen.link_preview_overlay_radius = (dimen.link_preview_overlay_radius & 0x00ffffff) | (packageId << 24);
        drawable.bubble = (drawable.bubble & 0x00ffffff) | (packageId << 24);
        drawable.bubble_arrow_up = (drawable.bubble_arrow_up & 0x00ffffff) | (packageId << 24);
        drawable.color_button_background = (drawable.color_button_background & 0x00ffffff) | (packageId << 24);
        drawable.color_picker_advanced_select_handle = (drawable.color_picker_advanced_select_handle & 0x00ffffff) | (packageId << 24);
        drawable.color_picker_border = (drawable.color_picker_border & 0x00ffffff) | (packageId << 24);
        drawable.dropdown_popup_background = (drawable.dropdown_popup_background & 0x00ffffff) | (packageId << 24);
        drawable.dropdown_popup_background_down = (drawable.dropdown_popup_background_down & 0x00ffffff) | (packageId << 24);
        drawable.dropdown_popup_background_up = (drawable.dropdown_popup_background_up & 0x00ffffff) | (packageId << 24);
        drawable.ic_media_video_poster = (drawable.ic_media_video_poster & 0x00ffffff) | (packageId << 24);
        drawable.ic_menu_search_holo_light = (drawable.ic_menu_search_holo_light & 0x00ffffff) | (packageId << 24);
        drawable.ic_menu_share_holo_light = (drawable.ic_menu_share_holo_light & 0x00ffffff) | (packageId << 24);
        drawable.icon_webview = (drawable.icon_webview & 0x00ffffff) | (packageId << 24);
        drawable.ondemand_overlay = (drawable.ondemand_overlay & 0x00ffffff) | (packageId << 24);
        drawable.pageinfo_warning_major = (drawable.pageinfo_warning_major & 0x00ffffff) | (packageId << 24);
        id.ampm = (id.ampm & 0x00ffffff) | (packageId << 24);
        id.arrow_image = (id.arrow_image & 0x00ffffff) | (packageId << 24);
        id.color_button_swatch = (id.color_button_swatch & 0x00ffffff) | (packageId << 24);
        id.color_picker_advanced = (id.color_picker_advanced & 0x00ffffff) | (packageId << 24);
        id.color_picker_simple = (id.color_picker_simple & 0x00ffffff) | (packageId << 24);
        id.date_picker = (id.date_picker & 0x00ffffff) | (packageId << 24);
        id.date_time_suggestion = (id.date_time_suggestion & 0x00ffffff) | (packageId << 24);
        id.date_time_suggestion_label = (id.date_time_suggestion_label & 0x00ffffff) | (packageId << 24);
        id.date_time_suggestion_value = (id.date_time_suggestion_value & 0x00ffffff) | (packageId << 24);
        id.dropdown_label = (id.dropdown_label & 0x00ffffff) | (packageId << 24);
        id.dropdown_menu_text = (id.dropdown_menu_text & 0x00ffffff) | (packageId << 24);
        id.dropdown_popup_window = (id.dropdown_popup_window & 0x00ffffff) | (packageId << 24);
        id.dropdown_sublabel = (id.dropdown_sublabel & 0x00ffffff) | (packageId << 24);
        id.gradient = (id.gradient & 0x00ffffff) | (packageId << 24);
        id.gradient_border = (id.gradient_border & 0x00ffffff) | (packageId << 24);
        id.hour = (id.hour & 0x00ffffff) | (packageId << 24);
        id.icon_view = (id.icon_view & 0x00ffffff) | (packageId << 24);
        id.main_text = (id.main_text & 0x00ffffff) | (packageId << 24);
        id.milli = (id.milli & 0x00ffffff) | (packageId << 24);
        id.minute = (id.minute & 0x00ffffff) | (packageId << 24);
        id.more_colors_button = (id.more_colors_button & 0x00ffffff) | (packageId << 24);
        id.more_colors_button_border = (id.more_colors_button_border & 0x00ffffff) | (packageId << 24);
        id.pickers = (id.pickers & 0x00ffffff) | (packageId << 24);
        id.position_in_year = (id.position_in_year & 0x00ffffff) | (packageId << 24);
        id.second = (id.second & 0x00ffffff) | (packageId << 24);
        id.second_colon = (id.second_colon & 0x00ffffff) | (packageId << 24);
        id.second_dot = (id.second_dot & 0x00ffffff) | (packageId << 24);
        id.seek_bar = (id.seek_bar & 0x00ffffff) | (packageId << 24);
        id.select_action_menu_copy = (id.select_action_menu_copy & 0x00ffffff) | (packageId << 24);
        id.select_action_menu_cut = (id.select_action_menu_cut & 0x00ffffff) | (packageId << 24);
        id.select_action_menu_paste = (id.select_action_menu_paste & 0x00ffffff) | (packageId << 24);
        id.select_action_menu_select_all = (id.select_action_menu_select_all & 0x00ffffff) | (packageId << 24);
        id.select_action_menu_share = (id.select_action_menu_share & 0x00ffffff) | (packageId << 24);
        id.select_action_menu_web_search = (id.select_action_menu_web_search & 0x00ffffff) | (packageId << 24);
        id.selected_color_view = (id.selected_color_view & 0x00ffffff) | (packageId << 24);
        id.selected_color_view_border = (id.selected_color_view_border & 0x00ffffff) | (packageId << 24);
        id.sub_text = (id.sub_text & 0x00ffffff) | (packageId << 24);
        id.text = (id.text & 0x00ffffff) | (packageId << 24);
        id.text_wrapper = (id.text_wrapper & 0x00ffffff) | (packageId << 24);
        id.time_picker = (id.time_picker & 0x00ffffff) | (packageId << 24);
        id.title = (id.title & 0x00ffffff) | (packageId << 24);
        id.top_view = (id.top_view & 0x00ffffff) | (packageId << 24);
        id.year = (id.year & 0x00ffffff) | (packageId << 24);
        layout.color_picker_advanced_component = (layout.color_picker_advanced_component & 0x00ffffff) | (packageId << 24);
        layout.color_picker_dialog_content = (layout.color_picker_dialog_content & 0x00ffffff) | (packageId << 24);
        layout.color_picker_dialog_title = (layout.color_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        layout.date_time_picker_dialog = (layout.date_time_picker_dialog & 0x00ffffff) | (packageId << 24);
        layout.date_time_suggestion = (layout.date_time_suggestion & 0x00ffffff) | (packageId << 24);
        layout.dropdown_item = (layout.dropdown_item & 0x00ffffff) | (packageId << 24);
        layout.multi_field_time_picker_dialog = (layout.multi_field_time_picker_dialog & 0x00ffffff) | (packageId << 24);
        layout.two_field_date_picker = (layout.two_field_date_picker & 0x00ffffff) | (packageId << 24);
        layout.validation_message_bubble = (layout.validation_message_bubble & 0x00ffffff) | (packageId << 24);
        menu.select_action_menu = (menu.select_action_menu & 0x00ffffff) | (packageId << 24);
        string.accessibility_content_view = (string.accessibility_content_view & 0x00ffffff) | (packageId << 24);
        string.accessibility_date_picker_month = (string.accessibility_date_picker_month & 0x00ffffff) | (packageId << 24);
        string.accessibility_date_picker_week = (string.accessibility_date_picker_week & 0x00ffffff) | (packageId << 24);
        string.accessibility_date_picker_year = (string.accessibility_date_picker_year & 0x00ffffff) | (packageId << 24);
        string.accessibility_datetime_picker_date = (string.accessibility_datetime_picker_date & 0x00ffffff) | (packageId << 24);
        string.accessibility_datetime_picker_time = (string.accessibility_datetime_picker_time & 0x00ffffff) | (packageId << 24);
        string.accessibility_time_picker_ampm = (string.accessibility_time_picker_ampm & 0x00ffffff) | (packageId << 24);
        string.accessibility_time_picker_hour = (string.accessibility_time_picker_hour & 0x00ffffff) | (packageId << 24);
        string.accessibility_time_picker_milli = (string.accessibility_time_picker_milli & 0x00ffffff) | (packageId << 24);
        string.accessibility_time_picker_minute = (string.accessibility_time_picker_minute & 0x00ffffff) | (packageId << 24);
        string.accessibility_time_picker_second = (string.accessibility_time_picker_second & 0x00ffffff) | (packageId << 24);
        string.actionbar_share = (string.actionbar_share & 0x00ffffff) | (packageId << 24);
        string.actionbar_web_search = (string.actionbar_web_search & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_black = (string.color_picker_button_black & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_blue = (string.color_picker_button_blue & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_cancel = (string.color_picker_button_cancel & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_cyan = (string.color_picker_button_cyan & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_green = (string.color_picker_button_green & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_magenta = (string.color_picker_button_magenta & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_more = (string.color_picker_button_more & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_red = (string.color_picker_button_red & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_set = (string.color_picker_button_set & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_white = (string.color_picker_button_white & 0x00ffffff) | (packageId << 24);
        string.color_picker_button_yellow = (string.color_picker_button_yellow & 0x00ffffff) | (packageId << 24);
        string.color_picker_dialog_title = (string.color_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        string.color_picker_hue = (string.color_picker_hue & 0x00ffffff) | (packageId << 24);
        string.color_picker_saturation = (string.color_picker_saturation & 0x00ffffff) | (packageId << 24);
        string.color_picker_value = (string.color_picker_value & 0x00ffffff) | (packageId << 24);
        string.copy_to_clipboard_failure_message = (string.copy_to_clipboard_failure_message & 0x00ffffff) | (packageId << 24);
        string.date_picker_dialog_clear = (string.date_picker_dialog_clear & 0x00ffffff) | (packageId << 24);
        string.date_picker_dialog_other_button_label = (string.date_picker_dialog_other_button_label & 0x00ffffff) | (packageId << 24);
        string.date_picker_dialog_set = (string.date_picker_dialog_set & 0x00ffffff) | (packageId << 24);
        string.date_picker_dialog_title = (string.date_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        string.date_time_picker_dialog_title = (string.date_time_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        string.low_memory_error = (string.low_memory_error & 0x00ffffff) | (packageId << 24);
        string.media_player_error_button = (string.media_player_error_button & 0x00ffffff) | (packageId << 24);
        string.media_player_error_text_invalid_progressive_playback = (string.media_player_error_text_invalid_progressive_playback & 0x00ffffff) | (packageId << 24);
        string.media_player_error_text_unknown = (string.media_player_error_text_unknown & 0x00ffffff) | (packageId << 24);
        string.media_player_error_title = (string.media_player_error_title & 0x00ffffff) | (packageId << 24);
        string.media_player_loading_video = (string.media_player_loading_video & 0x00ffffff) | (packageId << 24);
        string.month_picker_dialog_title = (string.month_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        string.opening_file_error = (string.opening_file_error & 0x00ffffff) | (packageId << 24);
        string.profiler_error_toast = (string.profiler_error_toast & 0x00ffffff) | (packageId << 24);
        string.profiler_no_storage_toast = (string.profiler_no_storage_toast & 0x00ffffff) | (packageId << 24);
        string.profiler_started_toast = (string.profiler_started_toast & 0x00ffffff) | (packageId << 24);
        string.profiler_stopped_toast = (string.profiler_stopped_toast & 0x00ffffff) | (packageId << 24);
        string.time_picker_dialog_am = (string.time_picker_dialog_am & 0x00ffffff) | (packageId << 24);
        string.time_picker_dialog_hour_minute_separator = (string.time_picker_dialog_hour_minute_separator & 0x00ffffff) | (packageId << 24);
        string.time_picker_dialog_minute_second_separator = (string.time_picker_dialog_minute_second_separator & 0x00ffffff) | (packageId << 24);
        string.time_picker_dialog_pm = (string.time_picker_dialog_pm & 0x00ffffff) | (packageId << 24);
        string.time_picker_dialog_second_subsecond_separator = (string.time_picker_dialog_second_subsecond_separator & 0x00ffffff) | (packageId << 24);
        string.time_picker_dialog_title = (string.time_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        string.webviewchromium_private_browsing_warning = (string.webviewchromium_private_browsing_warning & 0x00ffffff) | (packageId << 24);
        string.week_picker_dialog_title = (string.week_picker_dialog_title & 0x00ffffff) | (packageId << 24);
        style.DropdownPopupWindow = (style.DropdownPopupWindow & 0x00ffffff) | (packageId << 24);
        style.SelectPopupDialog = (style.SelectPopupDialog & 0x00ffffff) | (packageId << 24);
    }
}
